// SPDX-License-Identifier: Apache-2.0
// Generated by vos.device_regs from the owners below; rtl devicescheck checks it.
// UART: upstream/mocha/hw/vendor/lowrisc_ip/ip/uart/rtl/uart_reg_pkg.sv
// Status fields: upstream/mocha/hw/vendor/lowrisc_ip/ip/uart/data/uart.hjson
// Block: interfaces/block-device-contract.md
// Model bounds: model/model/sys/block_device.sail
package vos_device_regs_pkg;
  localparam logic [63:0] UART_STATUS = 64'h14;
  localparam logic [63:0] UART_RDATA = 64'h18;
  localparam logic [63:0] UART_WDATA = 64'h1c;
  localparam int unsigned UART_TXFULL_BIT = 0;
  localparam int unsigned UART_RXFULL_BIT = 1;
  localparam int unsigned UART_TXEMPTY_BIT = 2;
  localparam int unsigned UART_TXIDLE_BIT = 3;
  localparam int unsigned UART_RXIDLE_BIT = 4;
  localparam int unsigned UART_RXEMPTY_BIT = 5;
  localparam logic [63:0] BLK_VERSION = 64'h0;
  localparam logic [63:0] BLK_BLOCK_BYTES = 64'h8;
  localparam logic [63:0] BLK_BLOCK_COUNT = 64'h10;
  localparam logic [63:0] BLK_STATUS = 64'h18;
  localparam logic [63:0] BLK_RESULT = 64'h20;
  localparam logic [63:0] BLK_BLOCK = 64'h28;
  localparam logic [63:0] BLK_COMMAND = 64'h30;
  localparam logic [63:0] BLK_ACK = 64'h38;
  localparam logic [63:0] BLK_DATA = 64'h100;
  localparam int unsigned BLK_MAX_BYTES = 8192;
  localparam int unsigned BLK_MAX_BLOCK_BYTES = 4096;
endpackage
