# SPDX-License-Identifier: Apache-2.0
# Generated by tools/run.py block-authority emit; do not edit.
# Capability refusals and device-state preservation, M5.3c.
# Input model/config/verifiedos.json: f157070982b84795252b5acdf27221177bf38e3d16b61c2a34011114b91bf424
# Input model/model/core/cap_common.sail: 36405700c6d464141c91efc319217d42e22a4862843803aceedd3a0c39e652cd
# Input model/model/core/cap_causes.sail: 791d73010321f02beba10b65966305a3a26eb872ca1961a603271e2cf38a737b
# Input model/model/core/types_ext.sail: 5a90d253a2877acecba2d4d26a16e5fa261cd9f3c4851f81b300d8d4fa5f1631
# Input model/model/core/types.sail: 7f551abecd9a619feb19100f5bfb58f76f0a9c0e2d1d1d3300a842454e4c56bc
# Input model/model/core/xlen.sail: 8c164c3c26d2cd5983a50bf6eeefa38f3a2abda58b79354ec0fb42f60958126a
# Input model/model/core/types_common.sail: 8aecb1cfa1646ef8babedcf1a1785475c36f16dd00637c61992538f2c5fdfeeb
# Input interfaces/block-device-contract.md: 13eb8075150e45e64eb16dd981af59ce5059cf23ee4cedd872e11e55a5718b99
# Input tools/generated/dialect-table.json: 58f8ed08800814a949ed21e8b1a374acbf54edefbec521ad6dd3f38007879d1a
        .text
        .globl _start
_start:
        cmove c8, c1
        la c11, handler
        cspecialrw cnull, mtcc, c11
        li s2, 0
        li t0, 42991616
        csetaddr c9, c8, t0
        li t0, 4096
        csetbounds c9, c9, t0
        # Positive control: valid authority changes and reads the whole block.
        li gp, 1
        ld t1, 0(c9)
        li t2, 1
        beq t1, t2, continue_1
        j fail
continue_1:
        ld t1, 8(c9)
        li t2, 64
        beq t1, t2, continue_2
        j fail
continue_2:
        ld t1, 16(c9)
        li t2, 2
        beq t1, t2, continue_3
        j fail
continue_3:
        sd zero, 40(c9)
        li t0, 1876304394400937123
        sd t0, 256(c9)
        li t0, 11714285321579215915
        sd t0, 264(c9)
        li t0, 3033465684833453235
        sd t0, 272(c9)
        li t0, 12871728086988442683
        sd t0, 280(c9)
        li t0, 4190907350731052227
        sd t0, 288(c9)
        li t0, 14029170852397669451
        sd t0, 296(c9)
        li t0, 5348350111845311699
        sd t0, 304(c9)
        li t0, 15186613617806896219
        sd t0, 312(c9)
        li t0, 2
        sd t0, 48(c9)
        li t3, 16
poll_1:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_1
        addi t3, t3, -1
        bnez t3, poll_1
        j fail
done_1:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_4
        j fail
continue_4:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_2:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_2
        addi t3, t3, -1
        bnez t3, poll_2
        j fail
done_2:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_5
        j fail
continue_5:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_6
        j fail
continue_6:
        ld t1, 256(c9)
        li t2, 1876304394400937123
        beq t1, t2, continue_7
        j fail
continue_7:
        cgettag t2, c6
        beqz t2, continue_8
        j fail
continue_8:
        ld t1, 264(c9)
        li t2, 11714285321579215915
        beq t1, t2, continue_9
        j fail
continue_9:
        cgettag t2, c6
        beqz t2, continue_10
        j fail
continue_10:
        ld t1, 272(c9)
        li t2, 3033465684833453235
        beq t1, t2, continue_11
        j fail
continue_11:
        cgettag t2, c6
        beqz t2, continue_12
        j fail
continue_12:
        ld t1, 280(c9)
        li t2, 12871728086988442683
        beq t1, t2, continue_13
        j fail
continue_13:
        cgettag t2, c6
        beqz t2, continue_14
        j fail
continue_14:
        ld t1, 288(c9)
        li t2, 4190907350731052227
        beq t1, t2, continue_15
        j fail
continue_15:
        cgettag t2, c6
        beqz t2, continue_16
        j fail
continue_16:
        ld t1, 296(c9)
        li t2, 14029170852397669451
        beq t1, t2, continue_17
        j fail
continue_17:
        cgettag t2, c6
        beqz t2, continue_18
        j fail
continue_18:
        ld t1, 304(c9)
        li t2, 5348350111845311699
        beq t1, t2, continue_19
        j fail
continue_19:
        cgettag t2, c6
        beqz t2, continue_20
        j fail
continue_20:
        ld t1, 312(c9)
        li t2, 15186613617806896219
        beq t1, t2, continue_21
        j fail
continue_21:
        cgettag t2, c6
        beqz t2, continue_22
        j fail
continue_22:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_3:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_3
        addi t3, t3, -1
        bnez t3, poll_3
        j fail
done_3:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_23
        j fail
continue_23:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_24
        j fail
continue_24:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_25
        j fail
continue_25:
        cgettag t2, c6
        beqz t2, continue_26
        j fail
continue_26:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_27
        j fail
continue_27:
        cgettag t2, c6
        beqz t2, continue_28
        j fail
continue_28:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_29
        j fail
continue_29:
        cgettag t2, c6
        beqz t2, continue_30
        j fail
continue_30:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_31
        j fail
continue_31:
        cgettag t2, c6
        beqz t2, continue_32
        j fail
continue_32:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_33
        j fail
continue_33:
        cgettag t2, c6
        beqz t2, continue_34
        j fail
continue_34:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_35
        j fail
continue_35:
        cgettag t2, c6
        beqz t2, continue_36
        j fail
continue_36:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_37
        j fail
continue_37:
        cgettag t2, c6
        beqz t2, continue_38
        j fail
continue_38:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_39
        j fail
continue_39:
        cgettag t2, c6
        beqz t2, continue_40
        j fail
continue_40:
        li t0, 1
        sd t0, 56(c9)
        # untagged: refused block/data stores preserve the complete preparation.
        li gp, 2
        sd zero, 40(c9)
        li t0, 10990883593198449185
        sd t0, 256(c9)
        li t0, 2310345431429397161
        sd t0, 264(c9)
        li t0, 12148326358607675953
        sd t0, 272(c9)
        li t0, 3467506721861913273
        sd t0, 280(c9)
        li t0, 13305769124016902721
        sd t0, 288(c9)
        li t0, 4624948387759512265
        sd t0, 296(c9)
        li t0, 14463211889426129489
        sd t0, 304(c9)
        li t0, 5782391148873771737
        sd t0, 312(c9)
        li t2, 1
        li t0, 42991656
        csetaddr c10, c9, t0
        li a0, 42991656
        li t5, 28
        li t6, 322
        la c11, fault_4
        li s2, 1
fault_4:
        sd t2, 0(c10)
        beqz s2, continue_41
        j fail
continue_41:
        li t2, 0x8877665544332211
        li t0, 42991872
        csetaddr c10, c9, t0
        li a0, 42991872
        li t5, 28
        li t6, 322
        la c11, fault_5
        li s2, 1
fault_5:
        sd t2, 0(c10)
        beqz s2, continue_42
        j fail
continue_42:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_43
        j fail
continue_43:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_44
        j fail
continue_44:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_45
        j fail
continue_45:
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_6:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_6
        addi t3, t3, -1
        bnez t3, poll_6
        j fail
done_6:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_46
        j fail
continue_46:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_47
        j fail
continue_47:
        ld t1, 256(c9)
        li t2, 1876304394400937123
        beq t1, t2, continue_48
        j fail
continue_48:
        cgettag t2, c6
        beqz t2, continue_49
        j fail
continue_49:
        ld t1, 264(c9)
        li t2, 11714285321579215915
        beq t1, t2, continue_50
        j fail
continue_50:
        cgettag t2, c6
        beqz t2, continue_51
        j fail
continue_51:
        ld t1, 272(c9)
        li t2, 3033465684833453235
        beq t1, t2, continue_52
        j fail
continue_52:
        cgettag t2, c6
        beqz t2, continue_53
        j fail
continue_53:
        ld t1, 280(c9)
        li t2, 12871728086988442683
        beq t1, t2, continue_54
        j fail
continue_54:
        cgettag t2, c6
        beqz t2, continue_55
        j fail
continue_55:
        ld t1, 288(c9)
        li t2, 4190907350731052227
        beq t1, t2, continue_56
        j fail
continue_56:
        cgettag t2, c6
        beqz t2, continue_57
        j fail
continue_57:
        ld t1, 296(c9)
        li t2, 14029170852397669451
        beq t1, t2, continue_58
        j fail
continue_58:
        cgettag t2, c6
        beqz t2, continue_59
        j fail
continue_59:
        ld t1, 304(c9)
        li t2, 5348350111845311699
        beq t1, t2, continue_60
        j fail
continue_60:
        cgettag t2, c6
        beqz t2, continue_61
        j fail
continue_61:
        ld t1, 312(c9)
        li t2, 15186613617806896219
        beq t1, t2, continue_62
        j fail
continue_62:
        cgettag t2, c6
        beqz t2, continue_63
        j fail
continue_63:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_7:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_7
        addi t3, t3, -1
        bnez t3, poll_7
        j fail
done_7:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_64
        j fail
continue_64:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_65
        j fail
continue_65:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_66
        j fail
continue_66:
        cgettag t2, c6
        beqz t2, continue_67
        j fail
continue_67:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_68
        j fail
continue_68:
        cgettag t2, c6
        beqz t2, continue_69
        j fail
continue_69:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_70
        j fail
continue_70:
        cgettag t2, c6
        beqz t2, continue_71
        j fail
continue_71:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_72
        j fail
continue_72:
        cgettag t2, c6
        beqz t2, continue_73
        j fail
continue_73:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_74
        j fail
continue_74:
        cgettag t2, c6
        beqz t2, continue_75
        j fail
continue_75:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_76
        j fail
continue_76:
        cgettag t2, c6
        beqz t2, continue_77
        j fail
continue_77:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_78
        j fail
continue_78:
        cgettag t2, c6
        beqz t2, continue_79
        j fail
continue_79:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_80
        j fail
continue_80:
        cgettag t2, c6
        beqz t2, continue_81
        j fail
continue_81:
        li t0, 1
        sd t0, 56(c9)
        sd zero, 40(c9)
        li t0, 12148326358607675953
        sd t0, 256(c9)
        li t0, 3467506721861913273
        sd t0, 264(c9)
        li t0, 13305769124016902721
        sd t0, 272(c9)
        li t0, 4624948387759512265
        sd t0, 280(c9)
        li t0, 14463211889426129489
        sd t0, 288(c9)
        li t0, 5782391148873771737
        sd t0, 296(c9)
        li t0, 15620654654835356257
        sd t0, 304(c9)
        li t0, 6939833914266221289
        sd t0, 312(c9)
        li t2, 1
        li t0, 42991656
        csetaddr c10, c9, t0
        li a0, 42991656
        li t5, 28
        li t6, 322
        la c11, fault_8
        li s2, 1
fault_8:
        sd t2, 0(c10)
        beqz s2, continue_82
        j fail
continue_82:
        li t2, 0x8877665544332211
        li t0, 42991872
        csetaddr c10, c9, t0
        li a0, 42991872
        li t5, 28
        li t6, 322
        la c11, fault_9
        li s2, 1
fault_9:
        sd t2, 0(c10)
        beqz s2, continue_83
        j fail
continue_83:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_84
        j fail
continue_84:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_85
        j fail
continue_85:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_86
        j fail
continue_86:
        li t0, 2
        sd t0, 48(c9)
        li t3, 16
poll_10:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_10
        addi t3, t3, -1
        bnez t3, poll_10
        j fail
done_10:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_87
        j fail
continue_87:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_11:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_11
        addi t3, t3, -1
        bnez t3, poll_11
        j fail
done_11:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_88
        j fail
continue_88:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_89
        j fail
continue_89:
        ld t1, 256(c9)
        li t2, 12148326358607675953
        beq t1, t2, continue_90
        j fail
continue_90:
        cgettag t2, c6
        beqz t2, continue_91
        j fail
continue_91:
        ld t1, 264(c9)
        li t2, 3467506721861913273
        beq t1, t2, continue_92
        j fail
continue_92:
        cgettag t2, c6
        beqz t2, continue_93
        j fail
continue_93:
        ld t1, 272(c9)
        li t2, 13305769124016902721
        beq t1, t2, continue_94
        j fail
continue_94:
        cgettag t2, c6
        beqz t2, continue_95
        j fail
continue_95:
        ld t1, 280(c9)
        li t2, 4624948387759512265
        beq t1, t2, continue_96
        j fail
continue_96:
        cgettag t2, c6
        beqz t2, continue_97
        j fail
continue_97:
        ld t1, 288(c9)
        li t2, 14463211889426129489
        beq t1, t2, continue_98
        j fail
continue_98:
        cgettag t2, c6
        beqz t2, continue_99
        j fail
continue_99:
        ld t1, 296(c9)
        li t2, 5782391148873771737
        beq t1, t2, continue_100
        j fail
continue_100:
        cgettag t2, c6
        beqz t2, continue_101
        j fail
continue_101:
        ld t1, 304(c9)
        li t2, 15620654654835356257
        beq t1, t2, continue_102
        j fail
continue_102:
        cgettag t2, c6
        beqz t2, continue_103
        j fail
continue_103:
        ld t1, 312(c9)
        li t2, 6939833914266221289
        beq t1, t2, continue_104
        j fail
continue_104:
        cgettag t2, c6
        beqz t2, continue_105
        j fail
continue_105:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_12:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_12
        addi t3, t3, -1
        bnez t3, poll_12
        j fail
done_12:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_106
        j fail
continue_106:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_107
        j fail
continue_107:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_108
        j fail
continue_108:
        cgettag t2, c6
        beqz t2, continue_109
        j fail
continue_109:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_110
        j fail
continue_110:
        cgettag t2, c6
        beqz t2, continue_111
        j fail
continue_111:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_112
        j fail
continue_112:
        cgettag t2, c6
        beqz t2, continue_113
        j fail
continue_113:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_114
        j fail
continue_114:
        cgettag t2, c6
        beqz t2, continue_115
        j fail
continue_115:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_116
        j fail
continue_116:
        cgettag t2, c6
        beqz t2, continue_117
        j fail
continue_117:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_118
        j fail
continue_118:
        cgettag t2, c6
        beqz t2, continue_119
        j fail
continue_119:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_120
        j fail
continue_120:
        cgettag t2, c6
        beqz t2, continue_121
        j fail
continue_121:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_122
        j fail
continue_122:
        cgettag t2, c6
        beqz t2, continue_123
        j fail
continue_123:
        li t0, 1
        sd t0, 56(c9)
        # untagged: refused command cannot publish the new staged payload.
        li gp, 3
        sd zero, 40(c9)
        li t0, 5203669766169158353
        sd t0, 256(c9)
        li t0, 15041933272130742873
        sd t0, 264(c9)
        li t0, 6361112531561607905
        sd t0, 272(c9)
        li t0, 16199376037539969641
        sd t0, 280(c9)
        li t0, 7518555296970769137
        sd t0, 288(c9)
        li t0, 17356818802949196409
        sd t0, 296(c9)
        li t0, 8675998062379995649
        sd t0, 304(c9)
        li t0, 67517494648871561
        sd t0, 312(c9)
        li t2, 2
        li t0, 42991664
        csetaddr c10, c9, t0
        li a0, 42991664
        li t5, 28
        li t6, 322
        la c11, fault_13
        li s2, 1
fault_13:
        sd t2, 0(c10)
        beqz s2, continue_124
        j fail
continue_124:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_125
        j fail
continue_125:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_126
        j fail
continue_126:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_127
        j fail
continue_127:
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_14:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_14
        addi t3, t3, -1
        bnez t3, poll_14
        j fail
done_14:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_128
        j fail
continue_128:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_129
        j fail
continue_129:
        ld t1, 256(c9)
        li t2, 12148326358607675953
        beq t1, t2, continue_130
        j fail
continue_130:
        cgettag t2, c6
        beqz t2, continue_131
        j fail
continue_131:
        ld t1, 264(c9)
        li t2, 3467506721861913273
        beq t1, t2, continue_132
        j fail
continue_132:
        cgettag t2, c6
        beqz t2, continue_133
        j fail
continue_133:
        ld t1, 272(c9)
        li t2, 13305769124016902721
        beq t1, t2, continue_134
        j fail
continue_134:
        cgettag t2, c6
        beqz t2, continue_135
        j fail
continue_135:
        ld t1, 280(c9)
        li t2, 4624948387759512265
        beq t1, t2, continue_136
        j fail
continue_136:
        cgettag t2, c6
        beqz t2, continue_137
        j fail
continue_137:
        ld t1, 288(c9)
        li t2, 14463211889426129489
        beq t1, t2, continue_138
        j fail
continue_138:
        cgettag t2, c6
        beqz t2, continue_139
        j fail
continue_139:
        ld t1, 296(c9)
        li t2, 5782391148873771737
        beq t1, t2, continue_140
        j fail
continue_140:
        cgettag t2, c6
        beqz t2, continue_141
        j fail
continue_141:
        ld t1, 304(c9)
        li t2, 15620654654835356257
        beq t1, t2, continue_142
        j fail
continue_142:
        cgettag t2, c6
        beqz t2, continue_143
        j fail
continue_143:
        ld t1, 312(c9)
        li t2, 6939833914266221289
        beq t1, t2, continue_144
        j fail
continue_144:
        cgettag t2, c6
        beqz t2, continue_145
        j fail
continue_145:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_15:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_15
        addi t3, t3, -1
        bnez t3, poll_15
        j fail
done_15:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_146
        j fail
continue_146:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_147
        j fail
continue_147:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_148
        j fail
continue_148:
        cgettag t2, c6
        beqz t2, continue_149
        j fail
continue_149:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_150
        j fail
continue_150:
        cgettag t2, c6
        beqz t2, continue_151
        j fail
continue_151:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_152
        j fail
continue_152:
        cgettag t2, c6
        beqz t2, continue_153
        j fail
continue_153:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_154
        j fail
continue_154:
        cgettag t2, c6
        beqz t2, continue_155
        j fail
continue_155:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_156
        j fail
continue_156:
        cgettag t2, c6
        beqz t2, continue_157
        j fail
continue_157:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_158
        j fail
continue_158:
        cgettag t2, c6
        beqz t2, continue_159
        j fail
continue_159:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_160
        j fail
continue_160:
        cgettag t2, c6
        beqz t2, continue_161
        j fail
continue_161:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_162
        j fail
continue_162:
        cgettag t2, c6
        beqz t2, continue_163
        j fail
continue_163:
        li t0, 1
        sd t0, 56(c9)
        sd zero, 40(c9)
        li t0, 6361112531561607905
        sd t0, 256(c9)
        li t0, 16199376037539969641
        sd t0, 264(c9)
        li t0, 7518555296970769137
        sd t0, 272(c9)
        li t0, 17356818802949196409
        sd t0, 280(c9)
        li t0, 8675998062379995649
        sd t0, 288(c9)
        li t0, 67517494648871561
        sd t0, 296(c9)
        li t0, 9833440827789222417
        sd t0, 304(c9)
        li t0, 1224960260058098329
        sd t0, 312(c9)
        li t2, 2
        li t0, 42991664
        csetaddr c10, c9, t0
        li a0, 42991664
        li t5, 28
        li t6, 322
        la c11, fault_16
        li s2, 1
fault_16:
        sd t2, 0(c10)
        beqz s2, continue_164
        j fail
continue_164:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_165
        j fail
continue_165:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_166
        j fail
continue_166:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_167
        j fail
continue_167:
        li t0, 2
        sd t0, 48(c9)
        li t3, 16
poll_17:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_17
        addi t3, t3, -1
        bnez t3, poll_17
        j fail
done_17:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_168
        j fail
continue_168:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_18:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_18
        addi t3, t3, -1
        bnez t3, poll_18
        j fail
done_18:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_169
        j fail
continue_169:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_170
        j fail
continue_170:
        ld t1, 256(c9)
        li t2, 6361112531561607905
        beq t1, t2, continue_171
        j fail
continue_171:
        cgettag t2, c6
        beqz t2, continue_172
        j fail
continue_172:
        ld t1, 264(c9)
        li t2, 16199376037539969641
        beq t1, t2, continue_173
        j fail
continue_173:
        cgettag t2, c6
        beqz t2, continue_174
        j fail
continue_174:
        ld t1, 272(c9)
        li t2, 7518555296970769137
        beq t1, t2, continue_175
        j fail
continue_175:
        cgettag t2, c6
        beqz t2, continue_176
        j fail
continue_176:
        ld t1, 280(c9)
        li t2, 17356818802949196409
        beq t1, t2, continue_177
        j fail
continue_177:
        cgettag t2, c6
        beqz t2, continue_178
        j fail
continue_178:
        ld t1, 288(c9)
        li t2, 8675998062379995649
        beq t1, t2, continue_179
        j fail
continue_179:
        cgettag t2, c6
        beqz t2, continue_180
        j fail
continue_180:
        ld t1, 296(c9)
        li t2, 67517494648871561
        beq t1, t2, continue_181
        j fail
continue_181:
        cgettag t2, c6
        beqz t2, continue_182
        j fail
continue_182:
        ld t1, 304(c9)
        li t2, 9833440827789222417
        beq t1, t2, continue_183
        j fail
continue_183:
        cgettag t2, c6
        beqz t2, continue_184
        j fail
continue_184:
        ld t1, 312(c9)
        li t2, 1224960260058098329
        beq t1, t2, continue_185
        j fail
continue_185:
        cgettag t2, c6
        beqz t2, continue_186
        j fail
continue_186:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_19:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_19
        addi t3, t3, -1
        bnez t3, poll_19
        j fail
done_19:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_187
        j fail
continue_187:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_188
        j fail
continue_188:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_189
        j fail
continue_189:
        cgettag t2, c6
        beqz t2, continue_190
        j fail
continue_190:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_191
        j fail
continue_191:
        cgettag t2, c6
        beqz t2, continue_192
        j fail
continue_192:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_193
        j fail
continue_193:
        cgettag t2, c6
        beqz t2, continue_194
        j fail
continue_194:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_195
        j fail
continue_195:
        cgettag t2, c6
        beqz t2, continue_196
        j fail
continue_196:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_197
        j fail
continue_197:
        cgettag t2, c6
        beqz t2, continue_198
        j fail
continue_198:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_199
        j fail
continue_199:
        cgettag t2, c6
        beqz t2, continue_200
        j fail
continue_200:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_201
        j fail
continue_201:
        cgettag t2, c6
        beqz t2, continue_202
        j fail
continue_202:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_203
        j fail
continue_203:
        cgettag t2, c6
        beqz t2, continue_204
        j fail
continue_204:
        li t0, 1
        sd t0, 56(c9)
        # bounds: refused block/data stores preserve the complete preparation.
        li gp, 4
        sd zero, 40(c9)
        li t0, 11063223766036525858
        sd t0, 256(c9)
        li t0, 2382685604267473834
        sd t0, 264(c9)
        li t0, 12220666531445752626
        sd t0, 272(c9)
        li t0, 3539846894699989946
        sd t0, 280(c9)
        li t0, 13378109296854979394
        sd t0, 288(c9)
        li t0, 4697288560597588938
        sd t0, 296(c9)
        li t0, 14535552062264206162
        sd t0, 304(c9)
        li t0, 5854731321711848410
        sd t0, 312(c9)
        li t2, 1
        li t0, 42991656
        csetaddr c10, c9, t0
        csetboundsimm c10, c10, 4
        li t5, 28
        li t6, 321
        la c11, fault_20
        li s2, 1
fault_20:
        sd t2, 0(c10)
        beqz s2, continue_205
        j fail
continue_205:
        li t2, 0x8877665544332211
        li t0, 42991872
        csetaddr c10, c9, t0
        csetboundsimm c10, c10, 4
        li t5, 28
        li t6, 321
        la c11, fault_21
        li s2, 1
fault_21:
        sd t2, 0(c10)
        beqz s2, continue_206
        j fail
continue_206:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_207
        j fail
continue_207:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_208
        j fail
continue_208:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_209
        j fail
continue_209:
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_22:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_22
        addi t3, t3, -1
        bnez t3, poll_22
        j fail
done_22:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_210
        j fail
continue_210:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_211
        j fail
continue_211:
        ld t1, 256(c9)
        li t2, 6361112531561607905
        beq t1, t2, continue_212
        j fail
continue_212:
        cgettag t2, c6
        beqz t2, continue_213
        j fail
continue_213:
        ld t1, 264(c9)
        li t2, 16199376037539969641
        beq t1, t2, continue_214
        j fail
continue_214:
        cgettag t2, c6
        beqz t2, continue_215
        j fail
continue_215:
        ld t1, 272(c9)
        li t2, 7518555296970769137
        beq t1, t2, continue_216
        j fail
continue_216:
        cgettag t2, c6
        beqz t2, continue_217
        j fail
continue_217:
        ld t1, 280(c9)
        li t2, 17356818802949196409
        beq t1, t2, continue_218
        j fail
continue_218:
        cgettag t2, c6
        beqz t2, continue_219
        j fail
continue_219:
        ld t1, 288(c9)
        li t2, 8675998062379995649
        beq t1, t2, continue_220
        j fail
continue_220:
        cgettag t2, c6
        beqz t2, continue_221
        j fail
continue_221:
        ld t1, 296(c9)
        li t2, 67517494648871561
        beq t1, t2, continue_222
        j fail
continue_222:
        cgettag t2, c6
        beqz t2, continue_223
        j fail
continue_223:
        ld t1, 304(c9)
        li t2, 9833440827789222417
        beq t1, t2, continue_224
        j fail
continue_224:
        cgettag t2, c6
        beqz t2, continue_225
        j fail
continue_225:
        ld t1, 312(c9)
        li t2, 1224960260058098329
        beq t1, t2, continue_226
        j fail
continue_226:
        cgettag t2, c6
        beqz t2, continue_227
        j fail
continue_227:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_23:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_23
        addi t3, t3, -1
        bnez t3, poll_23
        j fail
done_23:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_228
        j fail
continue_228:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_229
        j fail
continue_229:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_230
        j fail
continue_230:
        cgettag t2, c6
        beqz t2, continue_231
        j fail
continue_231:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_232
        j fail
continue_232:
        cgettag t2, c6
        beqz t2, continue_233
        j fail
continue_233:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_234
        j fail
continue_234:
        cgettag t2, c6
        beqz t2, continue_235
        j fail
continue_235:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_236
        j fail
continue_236:
        cgettag t2, c6
        beqz t2, continue_237
        j fail
continue_237:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_238
        j fail
continue_238:
        cgettag t2, c6
        beqz t2, continue_239
        j fail
continue_239:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_240
        j fail
continue_240:
        cgettag t2, c6
        beqz t2, continue_241
        j fail
continue_241:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_242
        j fail
continue_242:
        cgettag t2, c6
        beqz t2, continue_243
        j fail
continue_243:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_244
        j fail
continue_244:
        cgettag t2, c6
        beqz t2, continue_245
        j fail
continue_245:
        li t0, 1
        sd t0, 56(c9)
        sd zero, 40(c9)
        li t0, 12220666531445752626
        sd t0, 256(c9)
        li t0, 3539846894699989946
        sd t0, 264(c9)
        li t0, 13378109296854979394
        sd t0, 272(c9)
        li t0, 4697288560597588938
        sd t0, 280(c9)
        li t0, 14535552062264206162
        sd t0, 288(c9)
        li t0, 5854731321711848410
        sd t0, 296(c9)
        li t0, 15692994827673432930
        sd t0, 304(c9)
        li t0, 7012174087104297962
        sd t0, 312(c9)
        li t2, 1
        li t0, 42991656
        csetaddr c10, c9, t0
        csetboundsimm c10, c10, 4
        li t5, 28
        li t6, 321
        la c11, fault_24
        li s2, 1
fault_24:
        sd t2, 0(c10)
        beqz s2, continue_246
        j fail
continue_246:
        li t2, 0x8877665544332211
        li t0, 42991872
        csetaddr c10, c9, t0
        csetboundsimm c10, c10, 4
        li t5, 28
        li t6, 321
        la c11, fault_25
        li s2, 1
fault_25:
        sd t2, 0(c10)
        beqz s2, continue_247
        j fail
continue_247:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_248
        j fail
continue_248:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_249
        j fail
continue_249:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_250
        j fail
continue_250:
        li t0, 2
        sd t0, 48(c9)
        li t3, 16
poll_26:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_26
        addi t3, t3, -1
        bnez t3, poll_26
        j fail
done_26:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_251
        j fail
continue_251:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_27:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_27
        addi t3, t3, -1
        bnez t3, poll_27
        j fail
done_27:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_252
        j fail
continue_252:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_253
        j fail
continue_253:
        ld t1, 256(c9)
        li t2, 12220666531445752626
        beq t1, t2, continue_254
        j fail
continue_254:
        cgettag t2, c6
        beqz t2, continue_255
        j fail
continue_255:
        ld t1, 264(c9)
        li t2, 3539846894699989946
        beq t1, t2, continue_256
        j fail
continue_256:
        cgettag t2, c6
        beqz t2, continue_257
        j fail
continue_257:
        ld t1, 272(c9)
        li t2, 13378109296854979394
        beq t1, t2, continue_258
        j fail
continue_258:
        cgettag t2, c6
        beqz t2, continue_259
        j fail
continue_259:
        ld t1, 280(c9)
        li t2, 4697288560597588938
        beq t1, t2, continue_260
        j fail
continue_260:
        cgettag t2, c6
        beqz t2, continue_261
        j fail
continue_261:
        ld t1, 288(c9)
        li t2, 14535552062264206162
        beq t1, t2, continue_262
        j fail
continue_262:
        cgettag t2, c6
        beqz t2, continue_263
        j fail
continue_263:
        ld t1, 296(c9)
        li t2, 5854731321711848410
        beq t1, t2, continue_264
        j fail
continue_264:
        cgettag t2, c6
        beqz t2, continue_265
        j fail
continue_265:
        ld t1, 304(c9)
        li t2, 15692994827673432930
        beq t1, t2, continue_266
        j fail
continue_266:
        cgettag t2, c6
        beqz t2, continue_267
        j fail
continue_267:
        ld t1, 312(c9)
        li t2, 7012174087104297962
        beq t1, t2, continue_268
        j fail
continue_268:
        cgettag t2, c6
        beqz t2, continue_269
        j fail
continue_269:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_28:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_28
        addi t3, t3, -1
        bnez t3, poll_28
        j fail
done_28:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_270
        j fail
continue_270:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_271
        j fail
continue_271:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_272
        j fail
continue_272:
        cgettag t2, c6
        beqz t2, continue_273
        j fail
continue_273:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_274
        j fail
continue_274:
        cgettag t2, c6
        beqz t2, continue_275
        j fail
continue_275:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_276
        j fail
continue_276:
        cgettag t2, c6
        beqz t2, continue_277
        j fail
continue_277:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_278
        j fail
continue_278:
        cgettag t2, c6
        beqz t2, continue_279
        j fail
continue_279:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_280
        j fail
continue_280:
        cgettag t2, c6
        beqz t2, continue_281
        j fail
continue_281:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_282
        j fail
continue_282:
        cgettag t2, c6
        beqz t2, continue_283
        j fail
continue_283:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_284
        j fail
continue_284:
        cgettag t2, c6
        beqz t2, continue_285
        j fail
continue_285:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_286
        j fail
continue_286:
        cgettag t2, c6
        beqz t2, continue_287
        j fail
continue_287:
        li t0, 1
        sd t0, 56(c9)
        # bounds: refused command cannot publish the new staged payload.
        li gp, 5
        sd zero, 40(c9)
        li t0, 5276009939007235026
        sd t0, 256(c9)
        li t0, 15114273444968819546
        sd t0, 264(c9)
        li t0, 6433452704399684578
        sd t0, 272(c9)
        li t0, 16271716210378046314
        sd t0, 280(c9)
        li t0, 7590895469808845810
        sd t0, 288(c9)
        li t0, 17429158975787273082
        sd t0, 296(c9)
        li t0, 8748338235218072322
        sd t0, 304(c9)
        li t0, 139857667486948234
        sd t0, 312(c9)
        li t2, 2
        li t0, 42991664
        csetaddr c10, c9, t0
        csetboundsimm c10, c10, 4
        li t5, 28
        li t6, 321
        la c11, fault_29
        li s2, 1
fault_29:
        sd t2, 0(c10)
        beqz s2, continue_288
        j fail
continue_288:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_289
        j fail
continue_289:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_290
        j fail
continue_290:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_291
        j fail
continue_291:
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_30:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_30
        addi t3, t3, -1
        bnez t3, poll_30
        j fail
done_30:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_292
        j fail
continue_292:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_293
        j fail
continue_293:
        ld t1, 256(c9)
        li t2, 12220666531445752626
        beq t1, t2, continue_294
        j fail
continue_294:
        cgettag t2, c6
        beqz t2, continue_295
        j fail
continue_295:
        ld t1, 264(c9)
        li t2, 3539846894699989946
        beq t1, t2, continue_296
        j fail
continue_296:
        cgettag t2, c6
        beqz t2, continue_297
        j fail
continue_297:
        ld t1, 272(c9)
        li t2, 13378109296854979394
        beq t1, t2, continue_298
        j fail
continue_298:
        cgettag t2, c6
        beqz t2, continue_299
        j fail
continue_299:
        ld t1, 280(c9)
        li t2, 4697288560597588938
        beq t1, t2, continue_300
        j fail
continue_300:
        cgettag t2, c6
        beqz t2, continue_301
        j fail
continue_301:
        ld t1, 288(c9)
        li t2, 14535552062264206162
        beq t1, t2, continue_302
        j fail
continue_302:
        cgettag t2, c6
        beqz t2, continue_303
        j fail
continue_303:
        ld t1, 296(c9)
        li t2, 5854731321711848410
        beq t1, t2, continue_304
        j fail
continue_304:
        cgettag t2, c6
        beqz t2, continue_305
        j fail
continue_305:
        ld t1, 304(c9)
        li t2, 15692994827673432930
        beq t1, t2, continue_306
        j fail
continue_306:
        cgettag t2, c6
        beqz t2, continue_307
        j fail
continue_307:
        ld t1, 312(c9)
        li t2, 7012174087104297962
        beq t1, t2, continue_308
        j fail
continue_308:
        cgettag t2, c6
        beqz t2, continue_309
        j fail
continue_309:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_31:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_31
        addi t3, t3, -1
        bnez t3, poll_31
        j fail
done_31:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_310
        j fail
continue_310:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_311
        j fail
continue_311:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_312
        j fail
continue_312:
        cgettag t2, c6
        beqz t2, continue_313
        j fail
continue_313:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_314
        j fail
continue_314:
        cgettag t2, c6
        beqz t2, continue_315
        j fail
continue_315:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_316
        j fail
continue_316:
        cgettag t2, c6
        beqz t2, continue_317
        j fail
continue_317:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_318
        j fail
continue_318:
        cgettag t2, c6
        beqz t2, continue_319
        j fail
continue_319:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_320
        j fail
continue_320:
        cgettag t2, c6
        beqz t2, continue_321
        j fail
continue_321:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_322
        j fail
continue_322:
        cgettag t2, c6
        beqz t2, continue_323
        j fail
continue_323:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_324
        j fail
continue_324:
        cgettag t2, c6
        beqz t2, continue_325
        j fail
continue_325:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_326
        j fail
continue_326:
        cgettag t2, c6
        beqz t2, continue_327
        j fail
continue_327:
        li t0, 1
        sd t0, 56(c9)
        sd zero, 40(c9)
        li t0, 6433452704399684578
        sd t0, 256(c9)
        li t0, 16271716210378046314
        sd t0, 264(c9)
        li t0, 7590895469808845810
        sd t0, 272(c9)
        li t0, 17429158975787273082
        sd t0, 280(c9)
        li t0, 8748338235218072322
        sd t0, 288(c9)
        li t0, 139857667486948234
        sd t0, 296(c9)
        li t0, 9905781000627299090
        sd t0, 304(c9)
        li t0, 1225242838858247066
        sd t0, 312(c9)
        li t2, 2
        li t0, 42991664
        csetaddr c10, c9, t0
        csetboundsimm c10, c10, 4
        li t5, 28
        li t6, 321
        la c11, fault_32
        li s2, 1
fault_32:
        sd t2, 0(c10)
        beqz s2, continue_328
        j fail
continue_328:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_329
        j fail
continue_329:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_330
        j fail
continue_330:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_331
        j fail
continue_331:
        li t0, 2
        sd t0, 48(c9)
        li t3, 16
poll_33:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_33
        addi t3, t3, -1
        bnez t3, poll_33
        j fail
done_33:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_332
        j fail
continue_332:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_34:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_34
        addi t3, t3, -1
        bnez t3, poll_34
        j fail
done_34:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_333
        j fail
continue_333:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_334
        j fail
continue_334:
        ld t1, 256(c9)
        li t2, 6433452704399684578
        beq t1, t2, continue_335
        j fail
continue_335:
        cgettag t2, c6
        beqz t2, continue_336
        j fail
continue_336:
        ld t1, 264(c9)
        li t2, 16271716210378046314
        beq t1, t2, continue_337
        j fail
continue_337:
        cgettag t2, c6
        beqz t2, continue_338
        j fail
continue_338:
        ld t1, 272(c9)
        li t2, 7590895469808845810
        beq t1, t2, continue_339
        j fail
continue_339:
        cgettag t2, c6
        beqz t2, continue_340
        j fail
continue_340:
        ld t1, 280(c9)
        li t2, 17429158975787273082
        beq t1, t2, continue_341
        j fail
continue_341:
        cgettag t2, c6
        beqz t2, continue_342
        j fail
continue_342:
        ld t1, 288(c9)
        li t2, 8748338235218072322
        beq t1, t2, continue_343
        j fail
continue_343:
        cgettag t2, c6
        beqz t2, continue_344
        j fail
continue_344:
        ld t1, 296(c9)
        li t2, 139857667486948234
        beq t1, t2, continue_345
        j fail
continue_345:
        cgettag t2, c6
        beqz t2, continue_346
        j fail
continue_346:
        ld t1, 304(c9)
        li t2, 9905781000627299090
        beq t1, t2, continue_347
        j fail
continue_347:
        cgettag t2, c6
        beqz t2, continue_348
        j fail
continue_348:
        ld t1, 312(c9)
        li t2, 1225242838858247066
        beq t1, t2, continue_349
        j fail
continue_349:
        cgettag t2, c6
        beqz t2, continue_350
        j fail
continue_350:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_35:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_35
        addi t3, t3, -1
        bnez t3, poll_35
        j fail
done_35:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_351
        j fail
continue_351:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_352
        j fail
continue_352:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_353
        j fail
continue_353:
        cgettag t2, c6
        beqz t2, continue_354
        j fail
continue_354:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_355
        j fail
continue_355:
        cgettag t2, c6
        beqz t2, continue_356
        j fail
continue_356:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_357
        j fail
continue_357:
        cgettag t2, c6
        beqz t2, continue_358
        j fail
continue_358:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_359
        j fail
continue_359:
        cgettag t2, c6
        beqz t2, continue_360
        j fail
continue_360:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_361
        j fail
continue_361:
        cgettag t2, c6
        beqz t2, continue_362
        j fail
continue_362:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_363
        j fail
continue_363:
        cgettag t2, c6
        beqz t2, continue_364
        j fail
continue_364:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_365
        j fail
continue_365:
        cgettag t2, c6
        beqz t2, continue_366
        j fail
continue_366:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_367
        j fail
continue_367:
        cgettag t2, c6
        beqz t2, continue_368
        j fail
continue_368:
        li t0, 1
        sd t0, 56(c9)
        # store: refused block/data stores preserve the complete preparation.
        li gp, 6
        sd zero, 40(c9)
        li t0, 11135563938874602531
        sd t0, 256(c9)
        li t0, 2454744302128839851
        sd t0, 264(c9)
        li t0, 12293006704283829299
        sd t0, 272(c9)
        li t0, 3612187067538066619
        sd t0, 280(c9)
        li t0, 13450449469693056067
        sd t0, 288(c9)
        li t0, 4769628733435665611
        sd t0, 296(c9)
        li t0, 14607892235102282835
        sd t0, 304(c9)
        li t0, 5927071494549925083
        sd t0, 312(c9)
        li t2, 1
        li t0, 42991656
        csetaddr c10, c9, t0
        li t0, -5
        candperm c10, c10, t0
        li t5, 28
        li t6, 339
        la c11, fault_36
        li s2, 1
fault_36:
        sd t2, 0(c10)
        beqz s2, continue_369
        j fail
continue_369:
        li t2, 0x8877665544332211
        li t0, 42991872
        csetaddr c10, c9, t0
        li t0, -5
        candperm c10, c10, t0
        li t5, 28
        li t6, 339
        la c11, fault_37
        li s2, 1
fault_37:
        sd t2, 0(c10)
        beqz s2, continue_370
        j fail
continue_370:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_371
        j fail
continue_371:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_372
        j fail
continue_372:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_373
        j fail
continue_373:
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_38:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_38
        addi t3, t3, -1
        bnez t3, poll_38
        j fail
done_38:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_374
        j fail
continue_374:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_375
        j fail
continue_375:
        ld t1, 256(c9)
        li t2, 6433452704399684578
        beq t1, t2, continue_376
        j fail
continue_376:
        cgettag t2, c6
        beqz t2, continue_377
        j fail
continue_377:
        ld t1, 264(c9)
        li t2, 16271716210378046314
        beq t1, t2, continue_378
        j fail
continue_378:
        cgettag t2, c6
        beqz t2, continue_379
        j fail
continue_379:
        ld t1, 272(c9)
        li t2, 7590895469808845810
        beq t1, t2, continue_380
        j fail
continue_380:
        cgettag t2, c6
        beqz t2, continue_381
        j fail
continue_381:
        ld t1, 280(c9)
        li t2, 17429158975787273082
        beq t1, t2, continue_382
        j fail
continue_382:
        cgettag t2, c6
        beqz t2, continue_383
        j fail
continue_383:
        ld t1, 288(c9)
        li t2, 8748338235218072322
        beq t1, t2, continue_384
        j fail
continue_384:
        cgettag t2, c6
        beqz t2, continue_385
        j fail
continue_385:
        ld t1, 296(c9)
        li t2, 139857667486948234
        beq t1, t2, continue_386
        j fail
continue_386:
        cgettag t2, c6
        beqz t2, continue_387
        j fail
continue_387:
        ld t1, 304(c9)
        li t2, 9905781000627299090
        beq t1, t2, continue_388
        j fail
continue_388:
        cgettag t2, c6
        beqz t2, continue_389
        j fail
continue_389:
        ld t1, 312(c9)
        li t2, 1225242838858247066
        beq t1, t2, continue_390
        j fail
continue_390:
        cgettag t2, c6
        beqz t2, continue_391
        j fail
continue_391:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_39:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_39
        addi t3, t3, -1
        bnez t3, poll_39
        j fail
done_39:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_392
        j fail
continue_392:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_393
        j fail
continue_393:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_394
        j fail
continue_394:
        cgettag t2, c6
        beqz t2, continue_395
        j fail
continue_395:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_396
        j fail
continue_396:
        cgettag t2, c6
        beqz t2, continue_397
        j fail
continue_397:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_398
        j fail
continue_398:
        cgettag t2, c6
        beqz t2, continue_399
        j fail
continue_399:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_400
        j fail
continue_400:
        cgettag t2, c6
        beqz t2, continue_401
        j fail
continue_401:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_402
        j fail
continue_402:
        cgettag t2, c6
        beqz t2, continue_403
        j fail
continue_403:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_404
        j fail
continue_404:
        cgettag t2, c6
        beqz t2, continue_405
        j fail
continue_405:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_406
        j fail
continue_406:
        cgettag t2, c6
        beqz t2, continue_407
        j fail
continue_407:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_408
        j fail
continue_408:
        cgettag t2, c6
        beqz t2, continue_409
        j fail
continue_409:
        li t0, 1
        sd t0, 56(c9)
        sd zero, 40(c9)
        li t0, 12293006704283829299
        sd t0, 256(c9)
        li t0, 3612187067538066619
        sd t0, 264(c9)
        li t0, 13450449469693056067
        sd t0, 272(c9)
        li t0, 4769628733435665611
        sd t0, 280(c9)
        li t0, 14607892235102282835
        sd t0, 288(c9)
        li t0, 5927071494549925083
        sd t0, 296(c9)
        li t0, 15765335000511509603
        sd t0, 304(c9)
        li t0, 7084514259942374635
        sd t0, 312(c9)
        li t2, 1
        li t0, 42991656
        csetaddr c10, c9, t0
        li t0, -5
        candperm c10, c10, t0
        li t5, 28
        li t6, 339
        la c11, fault_40
        li s2, 1
fault_40:
        sd t2, 0(c10)
        beqz s2, continue_410
        j fail
continue_410:
        li t2, 0x8877665544332211
        li t0, 42991872
        csetaddr c10, c9, t0
        li t0, -5
        candperm c10, c10, t0
        li t5, 28
        li t6, 339
        la c11, fault_41
        li s2, 1
fault_41:
        sd t2, 0(c10)
        beqz s2, continue_411
        j fail
continue_411:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_412
        j fail
continue_412:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_413
        j fail
continue_413:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_414
        j fail
continue_414:
        li t0, 2
        sd t0, 48(c9)
        li t3, 16
poll_42:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_42
        addi t3, t3, -1
        bnez t3, poll_42
        j fail
done_42:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_415
        j fail
continue_415:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_43:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_43
        addi t3, t3, -1
        bnez t3, poll_43
        j fail
done_43:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_416
        j fail
continue_416:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_417
        j fail
continue_417:
        ld t1, 256(c9)
        li t2, 12293006704283829299
        beq t1, t2, continue_418
        j fail
continue_418:
        cgettag t2, c6
        beqz t2, continue_419
        j fail
continue_419:
        ld t1, 264(c9)
        li t2, 3612187067538066619
        beq t1, t2, continue_420
        j fail
continue_420:
        cgettag t2, c6
        beqz t2, continue_421
        j fail
continue_421:
        ld t1, 272(c9)
        li t2, 13450449469693056067
        beq t1, t2, continue_422
        j fail
continue_422:
        cgettag t2, c6
        beqz t2, continue_423
        j fail
continue_423:
        ld t1, 280(c9)
        li t2, 4769628733435665611
        beq t1, t2, continue_424
        j fail
continue_424:
        cgettag t2, c6
        beqz t2, continue_425
        j fail
continue_425:
        ld t1, 288(c9)
        li t2, 14607892235102282835
        beq t1, t2, continue_426
        j fail
continue_426:
        cgettag t2, c6
        beqz t2, continue_427
        j fail
continue_427:
        ld t1, 296(c9)
        li t2, 5927071494549925083
        beq t1, t2, continue_428
        j fail
continue_428:
        cgettag t2, c6
        beqz t2, continue_429
        j fail
continue_429:
        ld t1, 304(c9)
        li t2, 15765335000511509603
        beq t1, t2, continue_430
        j fail
continue_430:
        cgettag t2, c6
        beqz t2, continue_431
        j fail
continue_431:
        ld t1, 312(c9)
        li t2, 7084514259942374635
        beq t1, t2, continue_432
        j fail
continue_432:
        cgettag t2, c6
        beqz t2, continue_433
        j fail
continue_433:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_44:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_44
        addi t3, t3, -1
        bnez t3, poll_44
        j fail
done_44:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_434
        j fail
continue_434:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_435
        j fail
continue_435:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_436
        j fail
continue_436:
        cgettag t2, c6
        beqz t2, continue_437
        j fail
continue_437:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_438
        j fail
continue_438:
        cgettag t2, c6
        beqz t2, continue_439
        j fail
continue_439:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_440
        j fail
continue_440:
        cgettag t2, c6
        beqz t2, continue_441
        j fail
continue_441:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_442
        j fail
continue_442:
        cgettag t2, c6
        beqz t2, continue_443
        j fail
continue_443:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_444
        j fail
continue_444:
        cgettag t2, c6
        beqz t2, continue_445
        j fail
continue_445:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_446
        j fail
continue_446:
        cgettag t2, c6
        beqz t2, continue_447
        j fail
continue_447:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_448
        j fail
continue_448:
        cgettag t2, c6
        beqz t2, continue_449
        j fail
continue_449:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_450
        j fail
continue_450:
        cgettag t2, c6
        beqz t2, continue_451
        j fail
continue_451:
        li t0, 1
        sd t0, 56(c9)
        # store: refused command cannot publish the new staged payload.
        li gp, 7
        sd zero, 40(c9)
        li t0, 5348350111845311699
        sd t0, 256(c9)
        li t0, 15186613617806896219
        sd t0, 264(c9)
        li t0, 6505792877237761251
        sd t0, 272(c9)
        li t0, 16344056383216122987
        sd t0, 280(c9)
        li t0, 7663235642646922483
        sd t0, 288(c9)
        li t0, 17501499148625349755
        sd t0, 296(c9)
        li t0, 8820678408056148995
        sd t0, 304(c9)
        li t0, 212197840325024907
        sd t0, 312(c9)
        li t2, 2
        li t0, 42991664
        csetaddr c10, c9, t0
        li t0, -5
        candperm c10, c10, t0
        li t5, 28
        li t6, 339
        la c11, fault_45
        li s2, 1
fault_45:
        sd t2, 0(c10)
        beqz s2, continue_452
        j fail
continue_452:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_453
        j fail
continue_453:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_454
        j fail
continue_454:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_455
        j fail
continue_455:
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_46:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_46
        addi t3, t3, -1
        bnez t3, poll_46
        j fail
done_46:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_456
        j fail
continue_456:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_457
        j fail
continue_457:
        ld t1, 256(c9)
        li t2, 12293006704283829299
        beq t1, t2, continue_458
        j fail
continue_458:
        cgettag t2, c6
        beqz t2, continue_459
        j fail
continue_459:
        ld t1, 264(c9)
        li t2, 3612187067538066619
        beq t1, t2, continue_460
        j fail
continue_460:
        cgettag t2, c6
        beqz t2, continue_461
        j fail
continue_461:
        ld t1, 272(c9)
        li t2, 13450449469693056067
        beq t1, t2, continue_462
        j fail
continue_462:
        cgettag t2, c6
        beqz t2, continue_463
        j fail
continue_463:
        ld t1, 280(c9)
        li t2, 4769628733435665611
        beq t1, t2, continue_464
        j fail
continue_464:
        cgettag t2, c6
        beqz t2, continue_465
        j fail
continue_465:
        ld t1, 288(c9)
        li t2, 14607892235102282835
        beq t1, t2, continue_466
        j fail
continue_466:
        cgettag t2, c6
        beqz t2, continue_467
        j fail
continue_467:
        ld t1, 296(c9)
        li t2, 5927071494549925083
        beq t1, t2, continue_468
        j fail
continue_468:
        cgettag t2, c6
        beqz t2, continue_469
        j fail
continue_469:
        ld t1, 304(c9)
        li t2, 15765335000511509603
        beq t1, t2, continue_470
        j fail
continue_470:
        cgettag t2, c6
        beqz t2, continue_471
        j fail
continue_471:
        ld t1, 312(c9)
        li t2, 7084514259942374635
        beq t1, t2, continue_472
        j fail
continue_472:
        cgettag t2, c6
        beqz t2, continue_473
        j fail
continue_473:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_47:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_47
        addi t3, t3, -1
        bnez t3, poll_47
        j fail
done_47:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_474
        j fail
continue_474:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_475
        j fail
continue_475:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_476
        j fail
continue_476:
        cgettag t2, c6
        beqz t2, continue_477
        j fail
continue_477:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_478
        j fail
continue_478:
        cgettag t2, c6
        beqz t2, continue_479
        j fail
continue_479:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_480
        j fail
continue_480:
        cgettag t2, c6
        beqz t2, continue_481
        j fail
continue_481:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_482
        j fail
continue_482:
        cgettag t2, c6
        beqz t2, continue_483
        j fail
continue_483:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_484
        j fail
continue_484:
        cgettag t2, c6
        beqz t2, continue_485
        j fail
continue_485:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_486
        j fail
continue_486:
        cgettag t2, c6
        beqz t2, continue_487
        j fail
continue_487:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_488
        j fail
continue_488:
        cgettag t2, c6
        beqz t2, continue_489
        j fail
continue_489:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_490
        j fail
continue_490:
        cgettag t2, c6
        beqz t2, continue_491
        j fail
continue_491:
        li t0, 1
        sd t0, 56(c9)
        sd zero, 40(c9)
        li t0, 6505792877237761251
        sd t0, 256(c9)
        li t0, 16344056383216122987
        sd t0, 264(c9)
        li t0, 7663235642646922483
        sd t0, 272(c9)
        li t0, 17501499148625349755
        sd t0, 280(c9)
        li t0, 8820678408056148995
        sd t0, 288(c9)
        li t0, 212197840325024907
        sd t0, 296(c9)
        li t0, 9978121173465375763
        sd t0, 304(c9)
        li t0, 1297583011696323739
        sd t0, 312(c9)
        li t2, 2
        li t0, 42991664
        csetaddr c10, c9, t0
        li t0, -5
        candperm c10, c10, t0
        li t5, 28
        li t6, 339
        la c11, fault_48
        li s2, 1
fault_48:
        sd t2, 0(c10)
        beqz s2, continue_492
        j fail
continue_492:
        ld t1, 24(c9)
        li t2, 0
        beq t1, t2, continue_493
        j fail
continue_493:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_494
        j fail
continue_494:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_495
        j fail
continue_495:
        li t0, 2
        sd t0, 48(c9)
        li t3, 16
poll_49:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_49
        addi t3, t3, -1
        bnez t3, poll_49
        j fail
done_49:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_496
        j fail
continue_496:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_50:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_50
        addi t3, t3, -1
        bnez t3, poll_50
        j fail
done_50:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_497
        j fail
continue_497:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_498
        j fail
continue_498:
        ld t1, 256(c9)
        li t2, 6505792877237761251
        beq t1, t2, continue_499
        j fail
continue_499:
        cgettag t2, c6
        beqz t2, continue_500
        j fail
continue_500:
        ld t1, 264(c9)
        li t2, 16344056383216122987
        beq t1, t2, continue_501
        j fail
continue_501:
        cgettag t2, c6
        beqz t2, continue_502
        j fail
continue_502:
        ld t1, 272(c9)
        li t2, 7663235642646922483
        beq t1, t2, continue_503
        j fail
continue_503:
        cgettag t2, c6
        beqz t2, continue_504
        j fail
continue_504:
        ld t1, 280(c9)
        li t2, 17501499148625349755
        beq t1, t2, continue_505
        j fail
continue_505:
        cgettag t2, c6
        beqz t2, continue_506
        j fail
continue_506:
        ld t1, 288(c9)
        li t2, 8820678408056148995
        beq t1, t2, continue_507
        j fail
continue_507:
        cgettag t2, c6
        beqz t2, continue_508
        j fail
continue_508:
        ld t1, 296(c9)
        li t2, 212197840325024907
        beq t1, t2, continue_509
        j fail
continue_509:
        cgettag t2, c6
        beqz t2, continue_510
        j fail
continue_510:
        ld t1, 304(c9)
        li t2, 9978121173465375763
        beq t1, t2, continue_511
        j fail
continue_511:
        cgettag t2, c6
        beqz t2, continue_512
        j fail
continue_512:
        ld t1, 312(c9)
        li t2, 1297583011696323739
        beq t1, t2, continue_513
        j fail
continue_513:
        cgettag t2, c6
        beqz t2, continue_514
        j fail
continue_514:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_51:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_51
        addi t3, t3, -1
        bnez t3, poll_51
        j fail
done_51:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_515
        j fail
continue_515:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_516
        j fail
continue_516:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_517
        j fail
continue_517:
        cgettag t2, c6
        beqz t2, continue_518
        j fail
continue_518:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_519
        j fail
continue_519:
        cgettag t2, c6
        beqz t2, continue_520
        j fail
continue_520:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_521
        j fail
continue_521:
        cgettag t2, c6
        beqz t2, continue_522
        j fail
continue_522:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_523
        j fail
continue_523:
        cgettag t2, c6
        beqz t2, continue_524
        j fail
continue_524:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_525
        j fail
continue_525:
        cgettag t2, c6
        beqz t2, continue_526
        j fail
continue_526:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_527
        j fail
continue_527:
        cgettag t2, c6
        beqz t2, continue_528
        j fail
continue_528:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_529
        j fail
continue_529:
        cgettag t2, c6
        beqz t2, continue_530
        j fail
continue_530:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_531
        j fail
continue_531:
        cgettag t2, c6
        beqz t2, continue_532
        j fail
continue_532:
        li t0, 1
        sd t0, 56(c9)
        # untagged: refused loads preserve completed control and staging.
        li gp, 8
        sd zero, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_52:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_52
        addi t3, t3, -1
        bnez t3, poll_52
        j fail
done_52:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_533
        j fail
continue_533:
        li t0, 42991616
        csetaddr c10, c9, t0
        li a0, 42991616
        li t5, 28
        li t6, 322
        la c11, fault_53
        li s2, 1
fault_53:
        ld t1, 0(c10)
        beqz s2, continue_534
        j fail
continue_534:
        li t0, 42991872
        csetaddr c10, c9, t0
        li a0, 42991872
        li t5, 28
        li t6, 322
        la c11, fault_54
        li s2, 1
fault_54:
        ld t1, 0(c10)
        beqz s2, continue_535
        j fail
continue_535:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, continue_536
        j fail
continue_536:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_537
        j fail
continue_537:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_538
        j fail
continue_538:
        ld t1, 256(c9)
        li t2, 6505792877237761251
        beq t1, t2, continue_539
        j fail
continue_539:
        ld t1, 264(c9)
        li t2, 16344056383216122987
        beq t1, t2, continue_540
        j fail
continue_540:
        ld t1, 272(c9)
        li t2, 7663235642646922483
        beq t1, t2, continue_541
        j fail
continue_541:
        ld t1, 280(c9)
        li t2, 17501499148625349755
        beq t1, t2, continue_542
        j fail
continue_542:
        ld t1, 288(c9)
        li t2, 8820678408056148995
        beq t1, t2, continue_543
        j fail
continue_543:
        ld t1, 296(c9)
        li t2, 212197840325024907
        beq t1, t2, continue_544
        j fail
continue_544:
        ld t1, 304(c9)
        li t2, 9978121173465375763
        beq t1, t2, continue_545
        j fail
continue_545:
        ld t1, 312(c9)
        li t2, 1297583011696323739
        beq t1, t2, continue_546
        j fail
continue_546:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_55:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_55
        addi t3, t3, -1
        bnez t3, poll_55
        j fail
done_55:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_547
        j fail
continue_547:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_548
        j fail
continue_548:
        ld t1, 256(c9)
        li t2, 6505792877237761251
        beq t1, t2, continue_549
        j fail
continue_549:
        cgettag t2, c6
        beqz t2, continue_550
        j fail
continue_550:
        ld t1, 264(c9)
        li t2, 16344056383216122987
        beq t1, t2, continue_551
        j fail
continue_551:
        cgettag t2, c6
        beqz t2, continue_552
        j fail
continue_552:
        ld t1, 272(c9)
        li t2, 7663235642646922483
        beq t1, t2, continue_553
        j fail
continue_553:
        cgettag t2, c6
        beqz t2, continue_554
        j fail
continue_554:
        ld t1, 280(c9)
        li t2, 17501499148625349755
        beq t1, t2, continue_555
        j fail
continue_555:
        cgettag t2, c6
        beqz t2, continue_556
        j fail
continue_556:
        ld t1, 288(c9)
        li t2, 8820678408056148995
        beq t1, t2, continue_557
        j fail
continue_557:
        cgettag t2, c6
        beqz t2, continue_558
        j fail
continue_558:
        ld t1, 296(c9)
        li t2, 212197840325024907
        beq t1, t2, continue_559
        j fail
continue_559:
        cgettag t2, c6
        beqz t2, continue_560
        j fail
continue_560:
        ld t1, 304(c9)
        li t2, 9978121173465375763
        beq t1, t2, continue_561
        j fail
continue_561:
        cgettag t2, c6
        beqz t2, continue_562
        j fail
continue_562:
        ld t1, 312(c9)
        li t2, 1297583011696323739
        beq t1, t2, continue_563
        j fail
continue_563:
        cgettag t2, c6
        beqz t2, continue_564
        j fail
continue_564:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_56:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_56
        addi t3, t3, -1
        bnez t3, poll_56
        j fail
done_56:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_565
        j fail
continue_565:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_566
        j fail
continue_566:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_567
        j fail
continue_567:
        cgettag t2, c6
        beqz t2, continue_568
        j fail
continue_568:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_569
        j fail
continue_569:
        cgettag t2, c6
        beqz t2, continue_570
        j fail
continue_570:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_571
        j fail
continue_571:
        cgettag t2, c6
        beqz t2, continue_572
        j fail
continue_572:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_573
        j fail
continue_573:
        cgettag t2, c6
        beqz t2, continue_574
        j fail
continue_574:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_575
        j fail
continue_575:
        cgettag t2, c6
        beqz t2, continue_576
        j fail
continue_576:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_577
        j fail
continue_577:
        cgettag t2, c6
        beqz t2, continue_578
        j fail
continue_578:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_579
        j fail
continue_579:
        cgettag t2, c6
        beqz t2, continue_580
        j fail
continue_580:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_581
        j fail
continue_581:
        cgettag t2, c6
        beqz t2, continue_582
        j fail
continue_582:
        li t0, 1
        sd t0, 56(c9)
        # bounds: refused loads preserve completed control and staging.
        li gp, 9
        sd zero, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_57:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_57
        addi t3, t3, -1
        bnez t3, poll_57
        j fail
done_57:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_583
        j fail
continue_583:
        li t0, 42991616
        csetaddr c10, c9, t0
        csetboundsimm c10, c10, 4
        li t5, 28
        li t6, 321
        la c11, fault_58
        li s2, 1
fault_58:
        ld t1, 0(c10)
        beqz s2, continue_584
        j fail
continue_584:
        li t0, 42991872
        csetaddr c10, c9, t0
        csetboundsimm c10, c10, 4
        li t5, 28
        li t6, 321
        la c11, fault_59
        li s2, 1
fault_59:
        ld t1, 0(c10)
        beqz s2, continue_585
        j fail
continue_585:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, continue_586
        j fail
continue_586:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_587
        j fail
continue_587:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_588
        j fail
continue_588:
        ld t1, 256(c9)
        li t2, 6505792877237761251
        beq t1, t2, continue_589
        j fail
continue_589:
        ld t1, 264(c9)
        li t2, 16344056383216122987
        beq t1, t2, continue_590
        j fail
continue_590:
        ld t1, 272(c9)
        li t2, 7663235642646922483
        beq t1, t2, continue_591
        j fail
continue_591:
        ld t1, 280(c9)
        li t2, 17501499148625349755
        beq t1, t2, continue_592
        j fail
continue_592:
        ld t1, 288(c9)
        li t2, 8820678408056148995
        beq t1, t2, continue_593
        j fail
continue_593:
        ld t1, 296(c9)
        li t2, 212197840325024907
        beq t1, t2, continue_594
        j fail
continue_594:
        ld t1, 304(c9)
        li t2, 9978121173465375763
        beq t1, t2, continue_595
        j fail
continue_595:
        ld t1, 312(c9)
        li t2, 1297583011696323739
        beq t1, t2, continue_596
        j fail
continue_596:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_60:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_60
        addi t3, t3, -1
        bnez t3, poll_60
        j fail
done_60:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_597
        j fail
continue_597:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_598
        j fail
continue_598:
        ld t1, 256(c9)
        li t2, 6505792877237761251
        beq t1, t2, continue_599
        j fail
continue_599:
        cgettag t2, c6
        beqz t2, continue_600
        j fail
continue_600:
        ld t1, 264(c9)
        li t2, 16344056383216122987
        beq t1, t2, continue_601
        j fail
continue_601:
        cgettag t2, c6
        beqz t2, continue_602
        j fail
continue_602:
        ld t1, 272(c9)
        li t2, 7663235642646922483
        beq t1, t2, continue_603
        j fail
continue_603:
        cgettag t2, c6
        beqz t2, continue_604
        j fail
continue_604:
        ld t1, 280(c9)
        li t2, 17501499148625349755
        beq t1, t2, continue_605
        j fail
continue_605:
        cgettag t2, c6
        beqz t2, continue_606
        j fail
continue_606:
        ld t1, 288(c9)
        li t2, 8820678408056148995
        beq t1, t2, continue_607
        j fail
continue_607:
        cgettag t2, c6
        beqz t2, continue_608
        j fail
continue_608:
        ld t1, 296(c9)
        li t2, 212197840325024907
        beq t1, t2, continue_609
        j fail
continue_609:
        cgettag t2, c6
        beqz t2, continue_610
        j fail
continue_610:
        ld t1, 304(c9)
        li t2, 9978121173465375763
        beq t1, t2, continue_611
        j fail
continue_611:
        cgettag t2, c6
        beqz t2, continue_612
        j fail
continue_612:
        ld t1, 312(c9)
        li t2, 1297583011696323739
        beq t1, t2, continue_613
        j fail
continue_613:
        cgettag t2, c6
        beqz t2, continue_614
        j fail
continue_614:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_61:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_61
        addi t3, t3, -1
        bnez t3, poll_61
        j fail
done_61:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_615
        j fail
continue_615:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_616
        j fail
continue_616:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_617
        j fail
continue_617:
        cgettag t2, c6
        beqz t2, continue_618
        j fail
continue_618:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_619
        j fail
continue_619:
        cgettag t2, c6
        beqz t2, continue_620
        j fail
continue_620:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_621
        j fail
continue_621:
        cgettag t2, c6
        beqz t2, continue_622
        j fail
continue_622:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_623
        j fail
continue_623:
        cgettag t2, c6
        beqz t2, continue_624
        j fail
continue_624:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_625
        j fail
continue_625:
        cgettag t2, c6
        beqz t2, continue_626
        j fail
continue_626:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_627
        j fail
continue_627:
        cgettag t2, c6
        beqz t2, continue_628
        j fail
continue_628:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_629
        j fail
continue_629:
        cgettag t2, c6
        beqz t2, continue_630
        j fail
continue_630:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_631
        j fail
continue_631:
        cgettag t2, c6
        beqz t2, continue_632
        j fail
continue_632:
        li t0, 1
        sd t0, 56(c9)
        # load: refused loads preserve completed control and staging.
        li gp, 10
        sd zero, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_62:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_62
        addi t3, t3, -1
        bnez t3, poll_62
        j fail
done_62:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_633
        j fail
continue_633:
        li t0, 42991616
        csetaddr c10, c9, t0
        li t0, -3
        candperm c10, c10, t0
        li t5, 28
        li t6, 338
        la c11, fault_63
        li s2, 1
fault_63:
        ld t1, 0(c10)
        beqz s2, continue_634
        j fail
continue_634:
        li t0, 42991872
        csetaddr c10, c9, t0
        li t0, -3
        candperm c10, c10, t0
        li t5, 28
        li t6, 338
        la c11, fault_64
        li s2, 1
fault_64:
        ld t1, 0(c10)
        beqz s2, continue_635
        j fail
continue_635:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, continue_636
        j fail
continue_636:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_637
        j fail
continue_637:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_638
        j fail
continue_638:
        ld t1, 256(c9)
        li t2, 6505792877237761251
        beq t1, t2, continue_639
        j fail
continue_639:
        ld t1, 264(c9)
        li t2, 16344056383216122987
        beq t1, t2, continue_640
        j fail
continue_640:
        ld t1, 272(c9)
        li t2, 7663235642646922483
        beq t1, t2, continue_641
        j fail
continue_641:
        ld t1, 280(c9)
        li t2, 17501499148625349755
        beq t1, t2, continue_642
        j fail
continue_642:
        ld t1, 288(c9)
        li t2, 8820678408056148995
        beq t1, t2, continue_643
        j fail
continue_643:
        ld t1, 296(c9)
        li t2, 212197840325024907
        beq t1, t2, continue_644
        j fail
continue_644:
        ld t1, 304(c9)
        li t2, 9978121173465375763
        beq t1, t2, continue_645
        j fail
continue_645:
        ld t1, 312(c9)
        li t2, 1297583011696323739
        beq t1, t2, continue_646
        j fail
continue_646:
        li t0, 1
        sd t0, 56(c9)
        li t0, 0
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_65:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_65
        addi t3, t3, -1
        bnez t3, poll_65
        j fail
done_65:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_647
        j fail
continue_647:
        ld t1, 40(c9)
        li t2, 0
        beq t1, t2, continue_648
        j fail
continue_648:
        ld t1, 256(c9)
        li t2, 6505792877237761251
        beq t1, t2, continue_649
        j fail
continue_649:
        cgettag t2, c6
        beqz t2, continue_650
        j fail
continue_650:
        ld t1, 264(c9)
        li t2, 16344056383216122987
        beq t1, t2, continue_651
        j fail
continue_651:
        cgettag t2, c6
        beqz t2, continue_652
        j fail
continue_652:
        ld t1, 272(c9)
        li t2, 7663235642646922483
        beq t1, t2, continue_653
        j fail
continue_653:
        cgettag t2, c6
        beqz t2, continue_654
        j fail
continue_654:
        ld t1, 280(c9)
        li t2, 17501499148625349755
        beq t1, t2, continue_655
        j fail
continue_655:
        cgettag t2, c6
        beqz t2, continue_656
        j fail
continue_656:
        ld t1, 288(c9)
        li t2, 8820678408056148995
        beq t1, t2, continue_657
        j fail
continue_657:
        cgettag t2, c6
        beqz t2, continue_658
        j fail
continue_658:
        ld t1, 296(c9)
        li t2, 212197840325024907
        beq t1, t2, continue_659
        j fail
continue_659:
        cgettag t2, c6
        beqz t2, continue_660
        j fail
continue_660:
        ld t1, 304(c9)
        li t2, 9978121173465375763
        beq t1, t2, continue_661
        j fail
continue_661:
        cgettag t2, c6
        beqz t2, continue_662
        j fail
continue_662:
        ld t1, 312(c9)
        li t2, 1297583011696323739
        beq t1, t2, continue_663
        j fail
continue_663:
        cgettag t2, c6
        beqz t2, continue_664
        j fail
continue_664:
        li t0, 1
        sd t0, 56(c9)
        li t0, 1
        sd t0, 40(c9)
        li t0, 1
        sd t0, 48(c9)
        li t3, 16
poll_66:
        ld t1, 24(c9)
        li t2, 2
        beq t1, t2, done_66
        addi t3, t3, -1
        bnez t3, poll_66
        j fail
done_66:
        ld t1, 32(c9)
        li t2, 0
        beq t1, t2, continue_665
        j fail
continue_665:
        ld t1, 40(c9)
        li t2, 1
        beq t1, t2, continue_666
        j fail
continue_666:
        ld t1, 256(c9)
        li t2, 5135868584551137600
        beq t1, t2, continue_667
        j fail
continue_667:
        cgettag t2, c6
        beqz t2, continue_668
        j fail
continue_668:
        ld t1, 264(c9)
        li t2, 5714589967255750984
        beq t1, t2, continue_669
        j fail
continue_669:
        cgettag t2, c6
        beqz t2, continue_670
        j fail
continue_670:
        ld t1, 272(c9)
        li t2, 6293311349960364368
        beq t1, t2, continue_671
        j fail
continue_671:
        cgettag t2, c6
        beqz t2, continue_672
        j fail
continue_672:
        ld t1, 280(c9)
        li t2, 6872032732664977752
        beq t1, t2, continue_673
        j fail
continue_673:
        cgettag t2, c6
        beqz t2, continue_674
        j fail
continue_674:
        ld t1, 288(c9)
        li t2, 7450754115369591136
        beq t1, t2, continue_675
        j fail
continue_675:
        cgettag t2, c6
        beqz t2, continue_676
        j fail
continue_676:
        ld t1, 296(c9)
        li t2, 8029475498074204520
        beq t1, t2, continue_677
        j fail
continue_677:
        cgettag t2, c6
        beqz t2, continue_678
        j fail
continue_678:
        ld t1, 304(c9)
        li t2, 8608196880778817904
        beq t1, t2, continue_679
        j fail
continue_679:
        cgettag t2, c6
        beqz t2, continue_680
        j fail
continue_680:
        ld t1, 312(c9)
        li t2, 9186918263483431288
        beq t1, t2, continue_681
        j fail
continue_681:
        cgettag t2, c6
        beqz t2, continue_682
        j fail
continue_682:
        li t0, 1
        sd t0, 56(c9)
        li gp, 0
        j pass
handler:
        bnez s2, continue_683
        j fail
continue_683:
        csrr t4, mcause
        beq t4, t5, continue_684
        j fail
continue_684:
        csrr t4, mtval
        beq t4, t6, continue_685
        j fail
continue_685:
        csrr t4, mepc
        cgetaddr t3, c11
        beq t4, t3, continue_686
        j fail
continue_686:
        addi t4, t4, 4
        csrw mepc, t4
        li s2, 0
        mret
fail:
        slli t0, gp, 1
        ori t0, t0, 1
        j exit
pass:
        li t0, 1
exit:
        li t1, tohost
        csetaddr c31, c8, t1
        sd t0, 0(c31)
halt:
        j halt
        .data
        .align 3
tohost:
        .dword 0
