# SPDX-License-Identifier: Apache-2.0
"""Emit or check the modeled device register fields and their Gallina accessors."""

import argparse

from vos import corpus, device_registers
from vos.cli import Table, dispatch


def _emit(_args: argparse.Namespace) -> int:
    root = corpus.find_root()
    try:
        artifacts = device_registers.generated(root)
    except ValueError as error:
        print(f"FAIL device-registers: {error}")
        return 1
    for relative, text in artifacts.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="")
    print(f"ok device-registers: emitted {len(artifacts)} artifacts")
    return 0


def _check(_args: argparse.Namespace) -> int:
    try:
        findings = device_registers.check(corpus.find_root())
    except ValueError as error:
        findings = [str(error)]
    if findings:
        print("FAIL device-registers: " + "; ".join(findings))
        return 1
    print("ok device-registers: model coverage and generated bytes agree")
    return 0


TABLE: Table = {
    "emit": (_emit, "emit the checked field accessors and constants"),
    "check": (_check, "check model coverage and generated bytes"),
}


def main(argv: list[str] | None = None) -> int:
    return dispatch(__doc__, TABLE, argv, prog="run.py device-registers")
