# SPDX-License-Identifier: Apache-2.0
"""M1.2f's two loops driven end to end with no backend and no toolchain.

The compiler, the emulator and the Wasm host are each a script written here: one
`ccomp` emits a stream in the frozen dialect, one emits the lp64d stream stock CompCert
writes, and one refuses; the emulator prints the HTIF line and the commit records the
real one prints and writes the terminal log; the Wasm host prints one boolean. What the
cases decide is the driver's own behaviour over those: that a refused stream is reported
by mnemonic, directive and line, that a dialect stream is assembled under the harness and
run, that the two questions are read back as the corpus reads them, that the recorded-run
comparator names the first disagreement, and that the declared component encoding round
trips and its comparator names the first field. The real compiler, the lane's emulator
and the oracle's switch are exercised by hand and quoted in the completion note.
"""

import json
import sys
import tempfile
from contextlib import redirect_stderr, redirect_stdout
from io import StringIO
from pathlib import Path
from typing import Final

from tests.harness import Case, ensure
from vos import trace
from vos.cli import compiler_diff as cd
from vos.jsonc import Json

# A stream in the frozen dialect, in the shape CompCert's printer writes: a tab between
# the mnemonic and its operands, local labels, and the function-info trailer.
DIALECT: Final = """\
# Emitted by a fake ccomp: a stream in the frozen dialect, in CompCert's printer's shape.
\t.text
\t.balign 4
\t.globl\tmain
main:
\tcincoffsetimm\tcsp, csp, -16
\tsc\tcra, 8(csp)
\tli\ta5, 41
\taddi\ta0, a5, 1
\tli\ta4, 42
\tbne\ta0, a4, .L100
\tli\ta0, 0
\tj\t.L101
.L100:
\tli\ta0, 1
.L101:
\tlc\tcra, 8(csp)
\tcincoffsetimm\tcsp, csp, 16
\tret
\t.type\tmain, @function
\t.size\tmain, . - main
"""

# The lp64d stream stock `ccomp -S` writes for the same kind of program: integer-relative
# addressing, `jr`, `sext.w`, and the data directives CompCert spells.
LP64D: Final = """\
# File generated by CompCert 3.17
# Command line: -S g1-00-pointer.c
\t.option nopic
\t.text
\t.balign 2
\t.globl\tmain
main:
\taddi\tsp, sp, -16
\tsd\tra, 8(sp)
\tla\ta5, cells
\tli\ta4, 41
\tsw\ta4, 4(a5)
\tlw\ta4, 4(a5)
\tsext.w\ta4, a4
\tli\ta3, 41
\tbne\ta4, a3, .L100
\tli\ta0, 0
\tj\t.L101
.L100:
\tli\ta0, 1
.L101:
\tld\tra, 8(sp)
\taddi\tsp, sp, 16
\tjr\tra
\t.type\tmain, @function
\t.size\tmain, . - main
\t.local\tcells
\t.comm\tcells, 16, 8
\t.data
\t.balign 8
\t.globl\ttable
table:
\t.quad\tcells
\t.long\t7
\t.short\t3
\t.byte\t1
"""

# What the scan owes over LP64D: each refused head, by kind, found at the line carrying it.
REFUSED: Final = (("directive", ".option"), ("mnemonic", "sext.w"), ("mnemonic", "jr"),
                  ("directive", ".local"), ("directive", ".comm"), ("directive", ".quad"),
                  ("directive", ".long"), ("directive", ".short"))

DIALECT_C: Final = "/* FAKE-CCOMP: dialect */\nint main(void) { return 0; }\n"
LP64D_C: Final = "int main(void) { return 0; }\n"
REFUSING_C: Final = "/* FAKE-CCOMP: refuse */\nint main(void) { return 0; }\n"

# The commit records the fake emulator prints: a tagged write read back tagged at the same
# address, which is the third reading the driver reports beside the digest.
RECORDS: Final = ("I 1 0000000080000000 0002E403", "X 8 1 0000000080000000",
                  "I 2 0000000080000004 00000013", "W 0000000080008010 8 1 000000008000C000",
                  "I 3 0000000080000008 00000013", "R 0000000080008010 8 1 000000008000C000")

FAKE_CCOMP: Final = f"""\
import pathlib, sys
args = sys.argv[1:]
source = pathlib.Path(next(a for a in args if a.endswith(".c")))
out = pathlib.Path(args[args.index("-o") + 1])
text = source.read_text(encoding="utf-8")
if "FAKE-CCOMP: refuse" in text:
    sys.stderr.write("fake ccomp: refused on purpose\\n")
    sys.exit(2)
stream = {DIALECT!r} if "FAKE-CCOMP: dialect" in text else {LP64D!r}
out.write_text(stream, encoding="utf-8", newline="")
"""

FAKE_SIM: Final = f"""\
import pathlib, sys
args = sys.argv[1:]
elf = pathlib.Path(args[-1])
pathlib.Path(args[args.index("--terminal-log") + 1]).write_bytes(b"true\\n")
name = elf.stem
print("HTIF located at 0x80008000")
for record in {RECORDS!r}:
    print(record)
if "fail2" in name:
    print("FAILURE: 2 (0x00000002)")
elif "trap" in name:
    print("FAILURE: 284 (0x0000011c)")
elif "loop" in name:
    print("FAILURE: possible trap loop detected with MEPC=0x80000010")
elif "silent" not in name:
    print("SUCCESS")
"""

# Bytes rather than `print`, because the real host is Node on Linux and writes `\\n`, where
# a Windows interpreter's text-mode stdout would write `\\r\\n` and the encoding is exact.
FAKE_NODE: Final = """\
import sys
module = sys.argv[-1]
if "seeded" in module:
    sys.stdout.buffer.write(b"false\\n")
    sys.exit(1)
sys.stdout.buffer.write(b"true\\n")
"""


def _script(directory: Path, name: str, text: str) -> Path:
    path = directory / f"{name}.py"
    path.write_text(text, encoding="utf-8", newline="\n")
    return path


def _wrapper(directory: Path, name: str, script: Path) -> Path:
    """The script as an executable a `--ccomp` or `--simulator` flag can name."""
    if sys.platform == "win32":
        path = directory / f"{name}.cmd"
        path.write_text(f'@"{sys.executable}" "{script}" %*\r\n', encoding="utf-8",
                        newline="")
        return path
    path = directory / name
    path.write_text(f'#!/bin/sh\nexec "{sys.executable}" "{script}" "$@"\n',
                    encoding="utf-8", newline="")
    path.chmod(0o755)
    return path


def _lines_of(stream: str, head: str) -> list[int]:
    return [n for n, raw in enumerate(stream.splitlines(), 1)
            if raw.replace("\t", " ").strip().split(" ")[0] == head]


def _generator_is_deterministic() -> None:
    first, second = cd.programs(7, 6), cd.programs(7, 6)
    ensure(first == second, "one seed and count must name one campaign")
    ensure(len({p.name for p in first}) == 6, "every program needs a name of its own")
    ensure([p.pattern for p in first] == ["pointer", "struct", "call"] * 2,
           f"the patterns cycle, got {[p.pattern for p in first]}")
    for program in first:
        ensure("int main(void)" in program.source and program.checks > 0,
               f"{program.name} must define main and carry checks")
        ensure("double" not in program.source and "float" not in program.source,
               f"{program.name} must be FP-free (R-15-039)")
    ensure(cd.programs(8, 6) != first, "a different seed draws different constants")


def _scan_names_what_the_dialect_refuses() -> None:
    found = {(r.kind, r.name, r.line) for r in cd.refusals(LP64D)}
    wanted = {(kind, name, line) for kind, name in REFUSED
              for line in _lines_of(LP64D, name)}
    ensure(found == wanted, f"the scan must name exactly the refused heads by line:\n"
                            f"found  {sorted(found)}\nwanted {sorted(wanted)}")
    ensure(cd.refusals(DIALECT) == [], "a dialect stream carries nothing to refuse")
    ensure(cd.refusals("\taddi\tsp, sp, -16\n") == [],
           "a tab between mnemonic and operands is normalized, not refused")
    ensure(cd.refusals("\t.section\t.rodata,\"a\",@progbits\n")
           == [cd.Refusal("section", ".rodata", 1)],
           "a section the image lacks is named by the section")
    ensure(cd.refusals("\t.space\n") == [cd.Refusal("operand", ".space", 1,
                                                    ".space takes a size")],
           "a known directive with a refused operand carries the parser's words")


def _harness_assembles_a_dialect_stream() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        once, twice = scratch / "a.elf", scratch / "b.elf"
        found, size = cd.assemble(DIALECT, "dialect", once)
        ensure(found == [] and size > cd.STACK_BYTES and once.is_file(),
               f"the dialect stream must assemble under the harness, got {found} {size}")
        cd.assemble(DIALECT, "dialect", twice)
        ensure(once.read_bytes() == twice.read_bytes(), "the image must be reproducible")
        composite = cd.compose(DIALECT).splitlines()
        ensure(composite[cd.STREAM_OFFSET] == DIALECT.splitlines()[0],
               "the stream's first line sits at STREAM_OFFSET in the composite")
        ensure(composite[0].startswith("#") and "_start:" in composite
               and "tohost:" in composite, "the harness declares _start and tohost")

        found, _ = cd.assemble("\t.text\n\tret\n", "nomain", scratch / "c.elf")
        ensure([r.kind for r in found] == ["symbol"] and found[0].name == "main",
               f"a stream without main is refused by symbol, got {found}")
        found, _ = cd.assemble("main:\n\tsd\tra, 8(sp), 1\n\tret\n", "bad", scratch / "d.elf")
        ensure(found == [cd.Refusal("operand", "sd", 2, "sd takes 2 operands, given 3")],
               f"an operand the layout refuses is named by the stream's line, got {found}")
        ensure(not (scratch / "d.elf").exists(), "no image is written for a refused stream")


def _loop_over_fake_ccomp_dialect() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        work = scratch / "work"
        work.mkdir()
        profile = scratch / "profile.json"
        run = cd.run_program(cd.Program("d-pass", "given", DIALECT_C, 1), ccomp, work,
                             sim, profile, "")
        ran = run.ran
        if ran is None:
            raise AssertionError(f"a dialect stream must reach the emulator, got "
                                 f"{run.verdict}: {run.detail}")
        ensure(run.verdict == "pass" and ran.code == 0,
               f"a dialect stream runs to a pass, got {run.verdict}: {run.detail}")
        expected = trace.normalize_commit(list(RECORDS))
        ensure(ran.records == len(expected) and ran.digest == trace.digest(expected),
               "the trace is normalized and digested as the corpus digests a member")
        ensure(ran.cap_roundtrip and ran.emitted == b"true\n",
               "a tagged write read back tagged is reported, and the terminal log is read")
        ensure(run.compiled is not None
               and run.compiled.argv == (*ccomp, "-S", "d-pass.c", "-o", "d-pass.s"),
               f"ccomp is asked with names relative to the fresh directory: "
               f"{run.compiled and run.compiled.argv}")
        ensure(sorted(p.name for p in (work / "d-pass").iterdir()) == ["d-pass.c", "d-pass.s"],
               "the fresh directory holds the source and the stream and nothing else")
        ensure(run.image_bytes > cd.STACK_BYTES and (work / "d-pass.elf").is_file(),
               "the image is written beside the stream")

        for name, verdict, code, said in (("d-fail2", "fail", 2, "main returned 2"),
                                          ("d-trap", "trap", 284, "cause 28"),
                                          ("d-silent", "no-verdict", None, "no HTIF verdict"),
                                          ("d-loop", "no-verdict", None, "trap loop")):
            run = cd.run_program(cd.Program(name, "given", DIALECT_C, 1), ccomp, work, sim,
                                 profile, "")
            ensure(run.verdict == verdict and run.ran is not None and run.ran.code == code
                   and said in run.detail,
                   f"{name}: wanted {verdict} {code} {said!r}, got {run.verdict} "
                   f"{run.ran and run.ran.code} {run.detail!r}")

        run = cd.run_program(cd.Program("d-wait", "given", DIALECT_C, 1), ccomp, work,
                             None, profile, "the emulator half waits")
        ensure(run.verdict == "assembled" and "waits" in run.detail and run.ran is None,
               f"with no emulator the image is assembled and the wait is said: {run}")


def _loop_over_fake_ccomp_lp64d() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        work = scratch / "work"
        work.mkdir()
        run = cd.run_program(cd.Program("stock", "given", LP64D_C, 1), ccomp, work,
                             [str(scratch / "no-such-simulator")], scratch / "p.json", "")
        ensure(run.verdict == "dialect-refused" and run.ran is None,
               f"an lp64d stream is the pre-backend refusal, got {run.verdict}: {run.detail}")
        ensure({(r.kind, r.name) for r in run.refusals} == set(REFUSED),
               f"the refusals are the stream's, got {run.refusals}")
        ensure("2 of them mnemonics" in run.detail, f"the detail counts the mnemonics: "
                                                     f"{run.detail}")
        rows = cd.grouped(run.refusals)
        ensure(rows[0][0] == "mnemonic" and rows[0][1] == "jr" and rows[0][2] == [24],
               f"grouped rows put the mnemonics first, by name: {rows[:2]}")
        ensure(not (work / "stock.elf").exists(), "no image is written for a refused stream")

        run = cd.run_program(cd.Program("refused", "given", REFUSING_C, 1), ccomp, work,
                             None, scratch / "p.json", "")
        ensure(run.verdict == "ccomp-refused" and run.compiled is not None
               and run.compiled.exit_code == 2 and "refused on purpose" in run.detail,
               f"a compiler refusal is reported with its words: {run.detail}")
        run = cd.run_program(cd.Program("absent", "given", LP64D_C, 1),
                             [str(scratch / "no-such-ccomp")], work, None,
                             scratch / "p.json", "")
        ensure(run.verdict == "ccomp-refused" and "could not run" in run.detail,
               f"an absent compiler is a refusal naming the cause: {run.detail}")


def _recorded_run_disagreements() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        work = scratch / "work"
        work.mkdir()
        passed = cd.run_program(cd.Program("r-pass", "given", DIALECT_C, 1), ccomp, work,
                                sim, scratch / "p.json", "")
        failed = cd.run_program(cd.Program("r-fail2", "given", DIALECT_C, 1), ccomp, work,
                                sim, scratch / "p.json", "")
        refused = cd.run_program(cd.Program("r-stock", "given", LP64D_C, 1), ccomp, work,
                                 sim, scratch / "p.json", "")
        recorded: dict[str, Json] = {
            "programs": [cd.report_json(r) for r in (passed, failed, refused)]}
        ensure(cd.disagreements([passed, failed, refused], recorded) == [],
               "a run held against its own record agrees")
        renamed = json.loads(json.dumps(cd.report_json(failed)))
        renamed["name"] = "r-pass"
        said = cd.disagreements([passed], {"programs": [renamed]})
        ensure(len(said) == 1 and said[0].startswith("r-pass: HTIF 0 against the recorded 2"),
               f"a changed HTIF code is the first disagreement: {said}")
        moved = json.loads(json.dumps(cd.report_json(passed)))
        moved["run"]["digest"] = "0" * 16
        said = cd.disagreements([passed], {"programs": [moved]})
        ensure(len(said) == 1 and "trace digest" in said[0] and "0000000000000000" in said[0],
               f"a moved digest is named with both digests: {said}")
        stock = json.loads(json.dumps(cd.report_json(passed)))
        stock["name"] = "r-stock"
        said = cd.disagreements([refused], {"programs": [stock]})
        ensure(said == ["r-stock: verdict 'dialect-refused' against the recorded 'pass'"],
               f"a stream refused here and run there is a verdict disagreement: {said}")
        ensure(cd.disagreements([passed], {"programs": []}) == ["r-pass: not in the recorded run"]
               and cd.disagreements([passed], {}) == ["the recorded run carries no `programs` list"],
               "an absent program and an absent list are each named")


def _component_encoding_and_comparator() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        host = cd.output_of("wasm-host", 0, b"true\n", "fake node")
        record = scratch / "host.json"
        record.write_text(json.dumps(host.to_json()), encoding="utf-8")
        ensure(cd.read_output(record) == host, "a record round-trips through its file")
        ensure(host.to_json()["encoding"] == cd.ENCODING and host.output_length == 5,
               "the record names its encoding and measures its bytes")
        record.write_text(json.dumps({"encoding": "other/1"}), encoding="utf-8")
        try:
            cd.read_output(record)
        except ValueError as err:
            ensure(cd.ENCODING in str(err), f"a foreign record is refused by name: {err}")
        else:
            raise AssertionError("a foreign record must be refused")

        same = cd.output_of("purecap", 0, b"true\n", "fake sim")
        ensure(cd.compare_outputs(host, same) is None, "equal sides agree")
        verdict = cd.compare_outputs(host, cd.output_of("purecap", 1, b"true\n", ""))
        ensure(verdict is not None and verdict.field == "verdict"
               and verdict.line() == "verdict: host 0, purecap 1",
               f"the verdict is compared first: {verdict}")
        length = cd.compare_outputs(host, cd.output_of("purecap", 0, b"true", ""))
        ensure(length is not None and length.field == "output_length", f"then length: {length}")
        digest = cd.compare_outputs(host, cd.output_of("purecap", 0, b"trve\n", ""))
        ensure(digest is not None and digest.field == "output_sha256",
               f"then the digest where no bytes are in hand: {digest}")
        byte = cd.compare_outputs(host, cd.output_of("purecap", 0, b"trve\n", ""),
                                  b"true\n", b"trve\n")
        ensure(byte is not None and byte.line() == "output byte 2: host 0x75, purecap 0x76",
               f"and the first differing byte where they are: {byte}")

        node = [sys.executable, str(_script(scratch, "node", FAKE_NODE))]
        got, raw = cd.wasm_output(scratch / "demo.wasm", node, scratch)
        ensure(got.verdict == 0 and raw == b"true\n" and got.output_sha256 == host.output_sha256
               and got.side == "wasm-host", f"the Wasm host's side is read: {got}")
        seeded, _ = cd.wasm_output(scratch / "demo_seeded.wasm", node, scratch)
        ensure(seeded.verdict == 1 and seeded.output_head == "false\n",
               f"a seeded module's red line is read as its verdict: {seeded}")
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        purecap, raw = cd.purecap_output(scratch / "comp.elf", sim, scratch / "p.json", scratch)
        ensure(purecap.side == "purecap" and purecap.verdict == 0 and raw == b"true\n",
               f"the purecap side is the HTIF code and the terminal log: {purecap}")
        ensure(cd.compare_outputs(got, purecap, b"true\n", raw) is None,
               "the two sides agree under the encoding when both say true")
        ensure(cd.compare_outputs(seeded, purecap) is not None,
               "and a seeded host side disagrees")


def _run_cli(argv: list[str]) -> tuple[int, str, str]:
    out, err = StringIO(), StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        code = cd.main(argv)
    return code, out.getvalue(), err.getvalue()


def _cli_program() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = _wrapper(scratch, "ccomp", _script(scratch, "fake_ccomp", FAKE_CCOMP))
        sim = _wrapper(scratch, "sim", _script(scratch, "fake_sim", FAKE_SIM))
        base = ["program", "--ccomp", str(ccomp), "--generate", "2", "--seed", "5", "--json"]
        first = _run_cli([*base, "--expect-refusal"])
        second = _run_cli([*base, "--expect-refusal"])
        ensure(first == second, f"the report must be deterministic:\n{first}\n{second}")
        code, out, _ = first
        payload = json.loads(out)
        ensure(code == 0 and payload["green"] and payload["milestone_acceptance"] == "open"
               and payload["summary"]["dialect-refused"] == 2,
               f"ahead of the backend every stream is refused and that is green: {out[-600:]}")
        ensure(all(any(r["name"] == "jr" and r["kind"] == "mnemonic" for r in p["refusals"])
                   for p in payload["programs"]), "each program's refusals name jr")
        ensure(payload["ccomp"]["sha256"] is not None and payload["simulator"] is None,
               "the compiler is identified and the absent emulator is said")
        ensure(_run_cli(base)[0] == 1, "without --expect-refusal a refused stream is not green")

        given = scratch / "given.c"
        given.write_text(DIALECT_C, encoding="utf-8")
        code, out, _ = _run_cli(["program", "--ccomp", str(ccomp), str(given),
                                 "--simulator", str(sim), "--profile", str(scratch / "p")])
        ensure(code == 0 and "PASS" in out and "capability round trip: yes" in out
               and "every program answered both questions" in out,
               f"a dialect stream runs green through the CLI: {out}")
        code, out, _ = _run_cli(["program", "--ccomp", str(ccomp), str(given),
                                 "--simulator", str(sim), "--json"])
        recorded = scratch / "recorded.json"
        recorded.write_text(out, encoding="utf-8")
        code, out, _ = _run_cli(["program", "--ccomp", str(ccomp), str(given),
                                 "--simulator", str(sim), "--against", str(recorded)])
        ensure(code == 0 and "0 disagreement(s)" in out,
               f"a run held against its own record agrees: {out}")
        code, out, _ = _run_cli(["program", "--ccomp", str(ccomp), "--generate", "1",
                                 "--simulator", str(sim), "--against", str(recorded)])
        ensure(code == 1 and "DISAGREE" in out and "not in the recorded run" in out,
               f"a program the record lacks is a disagreement: {out}")
        ensure(_run_cli(["program", "--ccomp", str(ccomp)])[0] == 2, "nothing to compile is 2")
        ensure(_run_cli(["program", "--ccomp", str(ccomp), str(scratch / "absent.c")])[0] == 2,
               "an unreadable source is 2")


def _cli_component_and_generate() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        node = _script(scratch, "fake_node", FAKE_NODE)
        host, purecap = scratch / "host.json", scratch / "purecap.json"
        code, out, _ = _run_cli(["component", "--wasm", str(scratch / "x.wasm"), "--runner",
                                 sys.executable, "--runner", str(node), "--write-host",
                                 str(host)])
        ensure(code == 0 and "WAITS" in out and "purecap side" in out and host.is_file(),
               f"one side alone is recorded and the other is said to wait: {out}")
        purecap.write_text(json.dumps(cd.output_of("purecap", 0, b"true\n", "by hand").to_json()),
                           encoding="utf-8")
        code, out, _ = _run_cli(["component", "--host-record", str(host), "--purecap-record",
                                 str(purecap)])
        ensure(code == 0 and "AGREE" in out, f"two agreeing records are green: {out}")
        purecap.write_text(json.dumps(cd.output_of("purecap", 3, b"true\n", "by hand").to_json()),
                           encoding="utf-8")
        first = _run_cli(["component", "--host-record", str(host), "--purecap-record",
                          str(purecap), "--json"])
        ensure(first == _run_cli(["component", "--host-record", str(host), "--purecap-record",
                                  str(purecap), "--json"]), "the report is deterministic")
        code, out, _ = first
        payload = json.loads(out)
        ensure(code == 1 and payload["disagreement"] == "verdict: host 0, purecap 3"
               and payload["compared"] and payload["encoding"] == cd.ENCODING,
               f"a verdict disagreement is named: {out}")
        ensure(_run_cli(["component"])[0] == 2, "no side at all is 2")
        purecap.write_text("{}", encoding="utf-8")
        ensure(_run_cli(["component", "--purecap-record", str(purecap)])[0] == 2,
               "a record of the wrong encoding is 2")

        out_dir = scratch / "campaign"
        code, out, _ = _run_cli(["generate", "--out", str(out_dir), "--count", "3", "--seed", "2"])
        manifest = json.loads((out_dir / "manifest.json").read_text(encoding="utf-8"))
        ensure(code == 0 and len(manifest["programs"]) == 3
               and sorted(p.name for p in out_dir.glob("*.c"))
               == sorted(f"{row['name']}.c" for row in manifest["programs"]),
               f"the campaign is written with its manifest: {out}")
        ensure(all(row["sha256"] == cd._sha256((out_dir / f"{row['name']}.c").read_bytes())
                   for row in manifest["programs"]), "each row digests its file")


def cases() -> list[Case]:
    return [
        Case("generator-is-deterministic", _generator_is_deterministic),
        Case("scan-names-what-the-dialect-refuses", _scan_names_what_the_dialect_refuses),
        Case("harness-assembles-a-dialect-stream", _harness_assembles_a_dialect_stream),
        Case("loop-over-fake-ccomp-dialect", _loop_over_fake_ccomp_dialect),
        Case("loop-over-fake-ccomp-lp64d", _loop_over_fake_ccomp_lp64d),
        Case("recorded-run-disagreements", _recorded_run_disagreements),
        Case("component-encoding-and-comparator", _component_encoding_and_comparator),
        Case("cli-program", _cli_program),
        Case("cli-component-and-generate", _cli_component_and_generate),
    ]
