# SPDX-License-Identifier: Apache-2.0
"""M1.2f's two loops driven end to end with no backend and no toolchain.

The compiler, the emulator and the Wasm host are each a script written here: one
`ccomp` emits a stream in the frozen dialect, one emits the lp64d stream stock CompCert
writes, and one refuses; the emulator prints the HTIF line and the commit records the
real one prints and writes the terminal log; the Wasm host prints one boolean. What the
cases decide is the driver's own behaviour over those: that a refused stream is reported
by mnemonic, directive and line, that a dialect stream is assembled under the harness and
run, that the two questions are read back as the corpus reads them, that the recorded-run
comparator names the first disagreement, and that the declared component encoding round
trips and its comparator names the first field. The real compiler, the lane's emulator
and the oracle's switch are exercised by hand and quoted in the completion note.
"""

import json
import re
import sys
import tempfile
from contextlib import redirect_stderr, redirect_stdout
from io import StringIO
from pathlib import Path
from typing import Final

from tests.harness import Case, ensure
from vos import asm, env, trace
from vos.cli import compiler_diff as cd
from vos.cli.model import verified_build
from vos.jsonc import Json

# A stream in the frozen dialect, in the shape CompCert's printer writes: a tab between
# the mnemonic and its operands, local labels, and the function-info trailer.
DIALECT: Final = """\
# Emitted by a fake ccomp: a stream in the frozen dialect, in CompCert's printer's shape.
\t.text
\t.balign 4
\t.globl\tmain
main:
\tcincoffsetimm\tcsp, csp, -16
\tsc\tcra, 8(csp)
\tli\ta5, 41
\taddi\ta0, a5, 1
\tli\ta4, 42
\tbne\ta0, a4, .L100
\tli\ta0, 0
\tj\t.L101
.L100:
\tli\ta0, 1
.L101:
\tlc\tcra, 8(csp)
\tcincoffsetimm\tcsp, csp, 16
\tret
\t.type\tmain, @function
\t.size\tmain, . - main
"""

# The lp64d stream stock `ccomp -S` writes for the same kind of program: integer-relative
# addressing, `jr`, `sext.w`, and the data directives CompCert spells.
LP64D: Final = """\
# File generated by CompCert 3.17
# Command line: -S g1-00-pointer.c
\t.option nopic
\t.text
\t.balign 2
\t.globl\tmain
main:
\taddi\tsp, sp, -16
\tsd\tra, 8(sp)
\tla\ta5, cells
\tli\ta4, 41
\tsw\ta4, 4(a5)
1:\tauipc\tx31, %pcrel_hi(cells)
\tsw\ta4, %pcrel_lo(1b)(x31)
\tlw\ta4, 4(a5)
\tsext.w\ta4, a4
\tli\ta3, 41
\tbne\ta4, a3, .L100
\tli\ta0, 0
\tj\t.L101
.L100:
\tli\ta0, 1
.L101:
\tld\tra, 8(sp)
\taddi\tsp, sp, 16
\tjr\tra
\t.type\tmain, @function
\t.size\tmain, . - main
\t.local\tcells
\t.comm\tcells, 16, 8
\t.data
\t.balign 8
\t.globl\ttable
table:
\t.quad\tcells
\t.long\t7
\t.short\t3
\t.byte\t1
"""

# What the scan owes over LP64D: each refused name, by kind, with the text that finds the
# line carrying it. The PIC pair is the shape the contained ccomp actually emits: a
# numeric local label ahead of `auipc`, and the two relocation operators around it.
REFUSED: Final = (("directive", ".option", ".option"), ("mnemonic", "sext.w", "sext.w"),
                  ("mnemonic", "jr", "jr"), ("directive", ".local", ".local"),
                  ("directive", ".comm", ".comm"), ("directive", ".quad", ".quad"),
                  ("directive", ".long", ".long"), ("directive", ".short", ".short"),
                  ("label", "1:", "1:\tauipc"), ("mnemonic", "auipc", "1:\tauipc"),
                  ("relocation", "%pcrel_hi", "%pcrel_hi"),
                  ("relocation", "%pcrel_lo", "%pcrel_lo"))

DIALECT_C: Final = "/* FAKE-CCOMP: dialect */\nint main(void) { return 0; }\n"
LP64D_C: Final = "int main(void) { return 0; }\n"
REFUSING_C: Final = "/* FAKE-CCOMP: refuse */\nint main(void) { return 0; }\n"

# The commit records the fake emulator prints: a tagged write read back tagged at the same
# address, which is the third reading the driver reports beside the digest.
RECORDS: Final = ("I 1 0000000080000000 0002E403", "X 8 1 0000000080000000",
                  "I 2 0000000080000004 00000013", "W 0000000080008010 8 1 000000008000C000",
                  "I 3 0000000080000008 00000013", "R 0000000080008010 8 1 000000008000C000")

FAKE_CCOMP: Final = f"""\
import hashlib, json, pathlib, re, sys
args = sys.argv[1:]
source = pathlib.Path(next(a for a in args if a.endswith((".c", ".i"))))
text = source.read_text(encoding="utf-8")
if "-fverifiedos-narrowing-plan" in args:
    plan = json.loads(pathlib.Path(args[args.index("-fverifiedos-narrowing-plan") + 1]).read_text())
    if plan["context"]["source_sha256"] != hashlib.sha256(source.read_bytes()).hexdigest():
        sys.stderr.write("fake ccomp: stale source_sha256\\n")
        sys.exit(2)
if "-interp" in args:
    said = re.search(r"FAKE-CCOMP: interp (\\d+)", text)
    print(f"Time 7: program terminated (exit code = {{said.group(1) if said else 0}})")
    sys.exit(0)
out = pathlib.Path(args[args.index("-o") + 1])
if "FAKE-CCOMP: refuse" in text:
    sys.stderr.write("fake ccomp: refused on purpose\\n")
    sys.exit(2)
def exclusive(path, data):
    # the typed route creates its partial assembly and its narrowing sidecars this way
    try:
        with open(path, "x", encoding="utf-8", newline="") as handle:
            handle.write(data)
    except FileExistsError:
        sys.stderr.write(f"ccomp: error: {{path.name}}: File exists\\n")
        sys.exit(2)
stream = {DIALECT!r} if "FAKE-CCOMP: dialect" in text else {LP64D!r}
partial = out.with_name(out.name + ".partial")
exclusive(partial, stream)
if "-fverifiedos-narrowing-output" in args:
    prefix = args[args.index("-fverifiedos-narrowing-output") + 1]
    for suffix in (".plan.json", ".operations.json", ".sites.json"):
        exclusive(pathlib.Path(prefix + suffix),
                  json.dumps({{"sidecar": suffix, "source": hashlib.sha256(
                      source.read_bytes()).hexdigest()}}) + "\\n")
partial.replace(out)
"""

FAKE_SIM: Final = f"""\
import pathlib, sys
args = sys.argv[1:]
elf = pathlib.Path(args[-1])
pathlib.Path(args[args.index("--terminal-log") + 1]).write_bytes(b"true\\n")
name = elf.stem
print("HTIF located at 0x80008000")
for record in {RECORDS!r}:
    print(record)
if "fail2" in name:
    print("FAILURE: 2 (0x00000002)")
elif "trap" in name:
    print("FAILURE: 284 (0x0000011c)")
elif "loop" in name:
    print("FAILURE: possible trap loop detected with MEPC=0x80000010")
elif "silent" not in name:
    print("SUCCESS")
"""

# Bytes rather than `print`, because the real host is Node on Linux and writes `\\n`, where
# a Windows interpreter's text-mode stdout would write `\\r\\n` and the encoding is exact.
FAKE_NODE: Final = """\
import sys
module = sys.argv[-1]
if "seeded" in module:
    sys.stdout.buffer.write(b"false\\n")
    sys.exit(1)
sys.stdout.buffer.write(b"true\\n")
"""


def _script(directory: Path, name: str, text: str) -> Path:
    path = directory / f"{name}.py"
    path.write_text(text, encoding="utf-8", newline="\n")
    return path


def _wrapper(directory: Path, name: str, script: Path) -> Path:
    """The script as an executable a `--ccomp` or `--simulator` flag can name."""
    if sys.platform == "win32":
        path = directory / f"{name}.cmd"
        path.write_text(f'@"{sys.executable}" "{script}" %*\r\n', encoding="utf-8",
                        newline="")
        return path
    path = directory / name
    path.write_text(f'#!/bin/sh\nexec "{sys.executable}" "{script}" "$@"\n',
                    encoding="utf-8", newline="")
    path.chmod(0o755)
    return path


def _lines_of(stream: str, needle: str) -> list[int]:
    return [n for n, raw in enumerate(stream.splitlines(), 1) if needle in raw]


PATTERN_NAMES: Final = ["memory", "struct", "call", "stack", "nullable", "spill", "narrow"]

# A variable declared at file scope: the selected scalar source profile binds a global's
# authority only through a composition, so no generated program may carry one.
FILE_SCOPE_OBJECT: Final = re.compile(r"^(?:static\s+)?(?:volatile\s+)?"
                                      r"(?:long|int|short|char)\b[^(]*;$", re.MULTILINE)


def _generator_is_deterministic() -> None:
    first, second = cd.programs(7, 14), cd.programs(7, 14)
    ensure(first == second, "one seed and count must name one campaign")
    ensure(len({p.name for p in first}) == 14, "every program needs a name of its own")
    ensure([p.pattern for p in first] == PATTERN_NAMES * 2,
           f"the patterns cycle, got {[p.pattern for p in first]}")
    for program in first:
        ensure("int main(void)" in program.source and program.checks > 0
               and program.checks == cd.CHECKS[program.pattern] and program.expect == 0,
               f"{program.name} must define main and carry its pattern's checks")
        ensure(all(f"return {k};" in program.source for k in range(1, program.checks + 1)),
               f"{program.name} must name each of its checks through main's return")
        ensure("double" not in program.source and "float" not in program.source,
               f"{program.name} must be FP-free (R-15-039)")
        ensure("volatile" not in program.source
               and FILE_SCOPE_OBJECT.search(program.source) is None,
               f"{program.name} must declare no global object (selected source profile)")
        ensure((program.narrowing > 0) == (program.pattern == "narrow")
               and program.narrowing % 256 == 0
               and (not program.narrowing
                    or f"csetbounds(values, {program.narrowing}UL)" in program.source),
               f"{program.name}: only the narrowing pattern narrows, by whole 256-byte granules")
    ensure(cd.programs(8, 14) != first, "a different seed draws different constants")
    chosen = cd.programs(7, 4, patterns=["call", "narrow"])
    ensure([p.pattern for p in chosen] == ["call", "narrow"] * 2,
           f"a pattern selection cycles over the selection alone: {chosen}")
    try:
        cd.programs(7, 1, patterns=["nonesuch"])
    except ValueError as err:
        ensure("nonesuch" in str(err), f"an unknown pattern is named: {err}")
    else:
        raise AssertionError("an unknown pattern must be refused")


def _perturbed_twins_move_one_check() -> None:
    ordinary, twins = cd.programs(3, 28), cd.programs(3, 28, perturb=True)
    ensure([p.pattern for p in twins] == [p.pattern for p in ordinary],
           "a perturbed campaign keeps the ordinary campaign's membership")
    moved: set[tuple[str, int]] = set()
    for plain, twin in zip(ordinary, twins, strict=True):
        ensure(1 <= twin.expect <= twin.checks and twin.name == f"{plain.name}-p{twin.expect}",
               f"{twin.name} must name the check it moves")
        before = plain.source.replace(plain.name, "NAME").splitlines()
        after = twin.source.replace(twin.name, "NAME").splitlines()
        changed = [(a, b) for a, b in zip(before, after, strict=True) if a != b]
        ensure(len(changed) == 1, f"{twin.name}: exactly one line moves, got {changed}")
        old, new = changed[0]
        value = int(old.rsplit("!= ", 1)[1].rstrip(")"))
        ensure(new == old.replace(f"!= {value})", f"!= {value + 1})"),
               f"{twin.name}: the moved line is the check's constant plus one: {changed}")
        ensure(after[before.index(old) + 1].strip() == f"return {twin.expect};",
               f"{twin.name}: the moved constant guards check {twin.expect}")
        moved.add((twin.pattern, twin.expect))
    ensure(moved == {(name, check) for name in PATTERN_NAMES
                     for check in range(1, cd.CHECKS[name] + 1)},
           f"28 twins move every check of every pattern at least once, got {sorted(moved)}")


def _scan_names_what_the_dialect_refuses() -> None:
    found = {(r.kind, r.name, r.line) for r in cd.refusals(LP64D)}
    wanted = {(kind, name, line) for kind, name, needle in REFUSED
              for line in _lines_of(LP64D, needle)}
    ensure(found == wanted, f"the scan must name exactly the refused heads by line:\n"
                            f"found  {sorted(found)}\nwanted {sorted(wanted)}")
    ensure(cd.refusals(DIALECT) == [], "a dialect stream carries nothing to refuse")
    ensure(cd.refusals("\taddi\tsp, sp, -16\n") == [],
           "a tab between mnemonic and operands is normalized, not refused")
    ensure(cd.refusals("\t.section\t.rodata,\"a\",@progbits\n")
           == [cd.Refusal("section", ".rodata", 1)],
           "a section the image lacks is named by the section")
    ensure(cd.refusals("\t.space\n") == [cd.Refusal("operand", ".space", 1,
                                                    ".space takes a size")],
           "a known directive with a refused operand carries the parser's words")


def _harness_assembles_a_dialect_stream() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        once, twice = scratch / "a.elf", scratch / "b.elf"
        found, size = cd.assemble(DIALECT, "dialect", once)
        ensure(found == [] and size > cd.STACK_BYTES and once.is_file(),
               f"the dialect stream must assemble under the harness, got {found} {size}")
        cd.assemble(DIALECT, "dialect", twice)
        ensure(once.read_bytes() == twice.read_bytes(), "the image must be reproducible")
        composite = cd.compose(DIALECT).splitlines()
        ensure(composite[cd.STREAM_OFFSET] == DIALECT.splitlines()[0],
               "the stream's first line sits at STREAM_OFFSET in the composite")
        ensure(composite[0].startswith("#") and "_start:" in composite
               and "tohost:" in composite, "the harness declares _start and tohost")

        found, _ = cd.assemble("\t.text\n\tret\n", "nomain", scratch / "c.elf")
        ensure([r.kind for r in found] == ["symbol"] and found[0].name == "main",
               f"a stream without main is refused by symbol, got {found}")
        found, _ = cd.assemble("main:\n\tsd\tra, 8(sp), 1\n\tret\n", "bad", scratch / "d.elf")
        ensure(found == [cd.Refusal("operand", "sd", 2, "sd takes 2 operands, given 3")],
               f"an operand the layout refuses is named by the stream's line, got {found}")
        ensure(not (scratch / "d.elf").exists(), "no image is written for a refused stream")


def _harness_authority_on_sail() -> None:
    """Exercise the test composition's ABI authority, independently of a compiler."""
    environment = env.load()
    verified_build(environment)
    body = """\
        .text
main:
        li a0, 1
        cgetperm t0, csp
        li t1, 0xFE
        bne t0, t1, probe_return
        li a0, 2
        cgetbase t0, csp
        li t1, __vos_stack
        bne t0, t1, probe_return
        cgettop t0, csp
        li t1, __vos_stack_top
        bne t0, t1, probe_return
        cgetaddr t0, csp
        bne t0, t1, probe_return
        cincoffsetimm csp, csp, -16
        sc csp, 0(csp)
        lc c6, 0(csp)
        cseqx t2, c6, csp
        cincoffsetimm csp, csp, 16
        li a0, 3
        beqz t2, probe_return
"""
    # The scalar convention permits main to overwrite every allocatable register.
    body += "".join(f"        li x{register}, 0\n" for register in range(5, 31))
    body += "probe_return:\n        ret\n"
    positive = cd.compose(body)
    controls = (
        ("positive", positive, "pass", 0),
        ("caller-clobbered-root", positive.replace("c4,", "c8,"), "no-verdict", None),
        ("global-stack", positive.replace("li      t1, 0xFFE", "li      t1, 0xFFF"),
         "fail", 1),
        ("unbounded-stack", positive.replace("csetbounds csp, csp, t1", "cmove csp, csp"),
         "fail", 2),
    )
    directory = environment.lane_root / "compiler-harness-controls"
    directory.mkdir(parents=True, exist_ok=True)
    for name, source, verdict, code in controls:
        ensure(name == "positive" or source != positive, f"{name}: mutation did not apply")
        assembly, elf = directory / f"{name}.s", directory / f"{name}.elf"
        assembly.write_text(source, encoding="utf-8", newline="\n")
        asm.assemble_file(assembly, elf)
        result = cd.run_image([str(environment.simulator)], environment.profile, elf,
                              directory, inst_limit=1000)
        ensure((result.verdict, result.code) == (verdict, code) and result.records > 0,
               f"{name}: expected {verdict}/{code}, got {result}")
        if name == "positive":
            ensure(result.cap_roundtrip, "the local stack must store and reload a tagged value")


def _capability_roundtrip_tracks_the_stored_value() -> None:
    def access(kind: str, address: int = 0x80008010, width: int = 8,
               tag: int = 1, value: int = 0x8000C000) -> str:
        return f"{kind} {address:09X} {width} {tag} {value:0{width * 2}X}"

    written, read = access("W"), access("R")
    other = 0x8000D000
    cases: list[tuple[str, list[str], bool]] = [
        ("tagged capability", [written, read], True),
        ("no write", [read], False),
        ("read precedes write", [read, written], False),
        ("untagged write", [access("W", tag=0), read], False),
        ("untagged read", [written, access("R", tag=0)], False),
        ("different payload", [written, access("R", value=other)], False),
        ("different address", [written, access("R", address=0x80008018)], False),
        ("different width", [written, access("R", width=4)], False),
        ("short tagged pair", [access("W", width=4), access("R", width=4)], False),
        ("wide tagged pair", [access("W", width=16), access("R", width=16)], False),
        ("unaligned pair", [access("W", address=0x80008011),
                            access("R", address=0x80008011)], False),
        ("same-slot overwrite", [written, access("W", tag=0), read], False),
        ("last-byte overwrite", [written, access("W", address=0x80008017,
                                                width=1, tag=0, value=0), read], False),
        ("overlap from below", [written, access("W", address=0x8000800C,
                                                tag=0, value=0), read], False),
        ("block overwrite", [written, access("W", address=0x80008000,
                                            width=64, tag=0, value=0), read], False),
        ("tagged replacement differs", [written, access("W", value=other), read], False),
        ("read latest replacement", [written, access("W", value=other),
                                     access("R", value=other)], True),
        ("write before slot", [written, access("W", address=0x80008008, tag=0), read], True),
        ("write after slot", [written, access("W", address=0x80008018, tag=0), read], True),
        ("ordinary read preserves slot", [written, access("R", width=4, tag=0), read], True),
        ("fresh write restores candidate", [written, access("W", tag=0), written, read], True),
        ("second slot survives", [written, access("W", address=0x80008018),
                                  access("W", tag=0),
                                  access("R", address=0x80008018)], True),
        ("register writes alone", ["X 8 1 000000008000C000", read], False),
        ("truncated payload", [written[:-1], read[:-1]], False),
        ("truncated intervening write", [written, access("W", tag=0)[:-1], read], False),
        ("malformed intervening write", [written, "W malformed", read], False),
        ("zero-width intervening write", [written, "W 080008010 0 0 0", read], False),
    ]
    failures = [name for name, records, expected in cases
                if cd.cap_roundtrip(records) != expected]
    ensure(not failures, f"capability round-trip evidence disagrees: {failures}")


def _loop_over_fake_ccomp_dialect() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        work = scratch / "work"
        work.mkdir()
        profile = scratch / "profile.json"
        run = cd.run_program(cd.Program("d-pass", "given", DIALECT_C, 1), ccomp, work,
                             sim, profile, "")
        ran = run.ran
        if ran is None:
            raise AssertionError(f"a dialect stream must reach the emulator, got "
                                 f"{run.verdict}: {run.detail}")
        ensure(run.verdict == "pass" and ran.code == 0,
               f"a dialect stream runs to a pass, got {run.verdict}: {run.detail}")
        expected = trace.normalize_commit(list(RECORDS))
        ensure(ran.records == len(expected) and ran.digest == trace.digest(expected),
               "the trace is normalized and digested as the corpus digests a member")
        ensure(ran.cap_roundtrip and ran.emitted == b"true\n",
               "a tagged write read back tagged is reported, and the terminal log is read")
        ensure(run.compiled is not None
               and run.compiled.argv == (*ccomp, "-S", "d-pass.c", "-o", "d-pass.s"),
               f"ccomp is asked with names relative to the fresh directory: "
               f"{run.compiled and run.compiled.argv}")
        ensure(sorted(p.name for p in (work / "d-pass").iterdir()) == ["d-pass.c", "d-pass.s"],
               "the fresh directory holds the source and the stream and nothing else")
        ensure(run.image_bytes > cd.STACK_BYTES and (work / "d-pass.elf").is_file(),
               "the image is written beside the stream")

        for name, verdict, code, said in (("d-fail2", "fail", 2, "main returned 2"),
                                          ("d-trap", "trap", 284, "cause 28"),
                                          ("d-silent", "no-verdict", None, "no HTIF verdict"),
                                          ("d-loop", "no-verdict", None, "trap loop")):
            run = cd.run_program(cd.Program(name, "given", DIALECT_C, 1), ccomp, work, sim,
                                 profile, "")
            ensure(run.verdict == verdict and run.ran is not None and run.ran.code == code
                   and said in run.detail,
                   f"{name}: wanted {verdict} {code} {said!r}, got {run.verdict} "
                   f"{run.ran and run.ran.code} {run.detail!r}")

        run = cd.run_program(cd.Program("d-wait", "given", DIALECT_C, 1), ccomp, work,
                             None, profile, "the emulator half waits")
        ensure(run.verdict == "assembled" and "waits" in run.detail and run.ran is None,
               f"with no emulator the image is assembled and the wait is said: {run}")


def _loop_over_fake_ccomp_lp64d() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        work = scratch / "work"
        work.mkdir()
        run = cd.run_program(cd.Program("stock", "given", LP64D_C, 1), ccomp, work,
                             [str(scratch / "no-such-simulator")], scratch / "p.json", "")
        ensure(run.verdict == "dialect-refused" and run.ran is None,
               f"an lp64d stream is the pre-backend refusal, got {run.verdict}: {run.detail}")
        ensure({(r.kind, r.name) for r in run.refusals}
               == {(kind, name) for kind, name, _ in REFUSED},
               f"the refusals are the stream's, got {run.refusals}")
        ensure("3 of them mnemonics" in run.detail, f"the detail counts the mnemonics: "
                                                     f"{run.detail}")
        rows = cd.grouped(run.refusals)
        ensure(rows[0][0] == "mnemonic" and rows[0][1] == "auipc"
               and rows[0][2] == _lines_of(LP64D, "1:\tauipc"),
               f"grouped rows put the mnemonics first, by name: {rows[:2]}")
        ensure(not (work / "stock.elf").exists(), "no image is written for a refused stream")

        run = cd.run_program(cd.Program("refused", "given", REFUSING_C, 1), ccomp, work,
                             None, scratch / "p.json", "")
        ensure(run.verdict == "ccomp-refused" and run.compiled is not None
               and run.compiled.exit_code == 2 and "refused on purpose" in run.detail,
               f"a compiler refusal is reported with its words: {run.detail}")
        run = cd.run_program(cd.Program("absent", "given", LP64D_C, 1),
                             [str(scratch / "no-such-ccomp")], work, None,
                             scratch / "p.json", "")
        ensure(run.verdict == "ccomp-refused" and "could not run" in run.detail,
               f"an absent compiler is a refusal naming the cause: {run.detail}")


def _source_interpreter_reading() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        work = scratch / "work"
        work.mkdir()
        profile = scratch / "profile.json"
        agree = cd.run_program(cd.Program("i-pass", "given", DIALECT_C, 1), ccomp, work,
                               sim, profile, "", interp=True)
        read = agree.interpreted
        ensure(agree.verdict == "pass" and read is not None and read.code == 0
               and read.argv[-2:] == ("-interp", "i-pass.c") and cd.as_expected(agree),
               f"an interpreter that agrees leaves the pass standing: {agree}")
        ensure(sorted(p.name for p in (work / "i-pass").iterdir()) == ["i-pass.c", "i-pass.s"]
               and (work / "i-pass.interp" / "i-pass.c").is_file(),
               "the interpreter runs in a directory of its own, beside the compilation")
        three = DIALECT_C + "/* FAKE-CCOMP: interp 3 */\n"
        differ = cd.run_program(cd.Program("i-differ", "given", three, 1), ccomp, work,
                                sim, profile, "", interp=True)
        ensure(differ.verdict == "source-disagrees" and "interpreter reports 3" in differ.detail
               and not cd.as_expected(differ),
               f"an image that disagrees with the interpreter is not a pass: {differ}")
        two = DIALECT_C + "/* FAKE-CCOMP: interp 2 */\n"
        twin = cd.run_program(cd.Program("i-fail2", "given", two, 2, expect=2), ccomp, work,
                              sim, profile, "", interp=True)
        ensure(twin.verdict == "fail" and cd.target_code(twin.ran) == 2 and cd.as_expected(twin),
               f"a perturbed twin failing at its moved check is as expected: {twin}")
        early = cd.run_program(cd.Program("i-pass2", "given", DIALECT_C, 2, expect=2), ccomp,
                               work, sim, profile, "")
        ensure(early.verdict == "pass" and not cd.as_expected(early),
               "a perturbed twin that passes has not failed where its source says")
        twice = _script(scratch, "twice", "print('Time 1: program terminated (exit code = 0)')\n"
                                          "print('Time 2: program terminated (exit code = 0)')\n")
        read = cd.interpret_c([sys.executable, str(twice)], work / "i-pass.c", work / "twice")
        ensure(read.code is None, "two termination lines give no reading")


def _narrowing_program_inputs() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        work = scratch / "work"
        work.mkdir()
        profile = scratch / "profile.json"
        profile.write_text("{}\n", encoding="utf-8")
        narrow = cd.Program("n-pass", "narrow", DIALECT_C, 1, 0, 512)
        run = cd.run_program(narrow, ccomp, work, sim, profile, "", interp=True)
        ensure(run.verdict == "pass" and run.interpreted is None and run.narrowing == 512,
               f"a narrowing program compiles against its plan and has no C reading: {run}")
        base, top = cd.harness_stack()
        ensure(top - base == cd.STACK_BYTES, "the plan's region is the harness stack")
        fresh = work / "n-pass"
        plan = json.loads((fresh / "plan.json").read_text(encoding="utf-8"))
        request = plan["requests"][0]
        ensure(plan["context"]["source_sha256"] == cd._sha256((work / "n-pass.i").read_bytes())
               and plan["context"]["profile_sha256"] == cd._sha256(profile.read_bytes())
               and request["offset"] == top - 512 - base and request["length"] == 512
               and plan["regions"][0]["base"] == base,
               f"the plan binds the bytes read and requests the top of the stack: {plan}")
        composition = json.loads((fresh / "composition.json").read_text(encoding="utf-8"))
        ensure(composition["requested_local_base"] == top - 512
               and composition["initial_csp"] == top and composition["stack_base"] == base,
               f"the composition places the one local at the stack's top: {composition}")
        argv = run.compiled.argv if run.compiled else ()
        ensure("-fverifiedos-narrowing-plan" in argv and argv[-4:-2] == ("-S", "n-pass.i"),
               f"the plan inputs reach the compiler beside the source it reads: {argv}")
        plain = cd.run_program(cd.Program("n-plain", "given", DIALECT_C, 1), ccomp, work, sim,
                               profile, "")
        ensure(plain.compiled is not None
               and "-fverifiedos-narrowing-plan" not in plain.compiled.argv
               and not (work / "n-plain" / "plan.json").exists(),
               "a program that narrows nothing is compiled without plan inputs")


def _narrowing_rerun_in_a_kept_directory() -> None:
    """The compiler creates its partial assembly and its narrowing sidecars exclusively,
    so a rerun in a kept directory must find none of them left by the earlier run, and
    the report binds every file the narrowing compilation read or wrote by digest."""
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        work = scratch / "work"
        work.mkdir()
        profile = scratch / "profile.json"
        profile.write_text("{}\n", encoding="utf-8")
        narrow = cd.Program("n-again", "narrow", DIALECT_C, 1, 0, 256)
        first = cd.run_program(narrow, ccomp, work, sim, profile, "")
        fresh = work / "n-again"
        files = dict(first.narrowing_files)
        wanted = {*cd.NARROWING_INPUTS,
                  *(f"{cd.NARROWING_OUTPUT}{suffix}" for suffix in cd.NARROWING_SIDECARS)}
        ensure(first.verdict == "pass" and set(files) == wanted
               and all(files[name] == cd._sha256((fresh / name).read_bytes())
                       for name in wanted),
               f"a narrowing run binds its plan inputs and sidecars by digest: {first}")
        # what a compiler killed at its timeout leaves beside the sidecars of its last run
        (fresh / "n-again.s.partial").write_text("stale\n", encoding="utf-8")
        second = cd.run_program(narrow, ccomp, work, sim, profile, "")
        ensure(second.verdict == "pass" and second.narrowing_files == first.narrowing_files,
               f"a rerun in the kept directory is not refused for an earlier run's "
               f"files: {second.verdict}: {second.detail}")
        recorded = json.loads(json.dumps(cd.report_json(second)))
        ensure(recorded["narrowing_files"] == files,
               f"the report carries the digests: {recorded['narrowing_files']}")
        plain = cd.run_program(cd.Program("n-plain", "given", DIALECT_C, 1), ccomp, work, sim,
                               profile, "")
        ensure(plain.narrowing_files == ()
               and json.loads(json.dumps(cd.report_json(plain)))["narrowing_files"] is None,
               "a program that narrows nothing binds no narrowing files")


def _component_harness_assembles() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        elf = scratch / "c.elf"
        found, size = cd.assemble(DIALECT, "component", elf, cd.COMPONENT_PROLOGUE)
        ensure(found == [] and size > cd.STACK_BYTES and elf.is_file(),
               f"a dialect stream assembles under the component harness: {found}")
        composite = cd.compose(DIALECT, cd.COMPONENT_PROLOGUE)
        for word in ("true\n", "false\n"):
            ensure(all(f"{cd.HTIF_PUTCHAR | ord(ch):#x}" in composite for ch in word),
                   f"the component harness spells {word!r} on the HTIF console")
        ensure(composite.splitlines()[cd.COMPONENT_PROLOGUE.count("\n")]
               == DIALECT.splitlines()[0], "the stream follows the component prologue")
        found, _ = cd.assemble("main:\n\tsd\tra, 8(sp), 1\n\tret\n", "bad", scratch / "d.elf",
                               cd.COMPONENT_PROLOGUE)
        ensure(found == [cd.Refusal("operand", "sd", 2, "sd takes 2 operands, given 3")],
               f"a layout refusal names the stream's own line under either harness: {found}")


def _component_harness_on_sail() -> None:
    """The component harness's two answers and its trap on the lane's real emulator."""
    environment = env.load()
    verified_build(environment)
    directory = environment.lane_root / "compiler-harness-controls"
    directory.mkdir(parents=True, exist_ok=True)
    controls = (("component-true", "li a0, 0", "pass", 0, b"true\n"),
                ("component-false", "li a0, 5", "fail", 1, b"false\n"),
                ("component-trap", "lc c6, 0(cnull)", "trap", 284, b""))
    for name, instruction, verdict, code, said in controls:
        body = f"        .text\nmain:\n        {instruction}\n        ret\n"
        assembly, elf = directory / f"{name}.s", directory / f"{name}.elf"
        assembly.write_text(cd.compose(body, cd.COMPONENT_PROLOGUE), encoding="utf-8",
                            newline="\n")
        asm.assemble_file(assembly, elf)
        result = cd.run_image([str(environment.simulator)], environment.profile, elf,
                              directory, inst_limit=2000)
        ensure((result.verdict, result.code, result.emitted) == (verdict, code, said)
               and result.records > 0,
               f"{name}: expected {verdict}/{code}/{said!r}, got {result}")


def _recorded_run_disagreements() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = [sys.executable, str(_script(scratch, "ccomp", FAKE_CCOMP))]
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        work = scratch / "work"
        work.mkdir()
        passed = cd.run_program(cd.Program("r-pass", "given", DIALECT_C, 1), ccomp, work,
                                sim, scratch / "p.json", "")
        failed = cd.run_program(cd.Program("r-fail2", "given", DIALECT_C, 1), ccomp, work,
                                sim, scratch / "p.json", "")
        refused = cd.run_program(cd.Program("r-stock", "given", LP64D_C, 1), ccomp, work,
                                 sim, scratch / "p.json", "")
        recorded: dict[str, Json] = {
            "programs": [cd.report_json(r) for r in (passed, failed, refused)]}
        ensure(cd.disagreements([passed, failed, refused], recorded) == [],
               "a run held against its own record agrees")
        renamed = json.loads(json.dumps(cd.report_json(failed)))
        renamed["name"] = "r-pass"
        said = cd.disagreements([passed], {"programs": [renamed]})
        ensure(len(said) == 1 and said[0].startswith("r-pass: HTIF 0 against the recorded 2"),
               f"a changed HTIF code is the first disagreement: {said}")
        moved = json.loads(json.dumps(cd.report_json(passed)))
        moved["run"]["digest"] = "0" * 16
        said = cd.disagreements([passed], {"programs": [moved]})
        ensure(len(said) == 1 and "trace digest" in said[0] and "0000000000000000" in said[0],
               f"a moved digest is named with both digests: {said}")
        stock = json.loads(json.dumps(cd.report_json(passed)))
        stock["name"] = "r-stock"
        stock["source_sha256"] = refused.source_sha256
        said = cd.disagreements([refused], {"programs": [stock]})
        ensure(said == ["r-stock: verdict 'dialect-refused' against the recorded 'pass'"],
               f"a stream refused here and run there is a verdict disagreement: {said}")
        ensure(cd.disagreements([passed], {"programs": []}) == ["r-pass: not in the recorded run"]
               and cd.disagreements([passed], {}) == ["the recorded run carries no `programs` list"],
               "an absent program and an absent list are each named")
        ensure(cd.disagreements([passed], recorded)
               == ["r-fail2: not in the current run", "r-stock: not in the current run"],
               "dropping a recorded program cannot make the campaign agree")
        changed = json.loads(json.dumps(cd.report_json(passed)))
        changed["source_sha256"] = "0" * 64
        ensure("source digest" in cd.disagreements([passed], {"programs": [changed]})[0],
               "the same program name with a different source is a different input")
        duplicated: dict[str, Json] = {
            "programs": [cd.report_json(passed), cd.report_json(passed)]}
        ensure("duplicate name" in cd.disagreements([passed], duplicated)[0],
               "a duplicate name cannot overwrite an earlier recorded result")
        missing = json.loads(json.dumps(cd.report_json(passed)))
        missing["run"] = None
        ensure("emulator evidence" in cd.disagreements([passed], {"programs": [missing]})[0],
               "a pass label alone cannot stand for missing emulator evidence")


def _component_encoding_and_comparator() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        host = cd.output_of("wasm-host", 0, b"true\n", "fake node")
        record = scratch / "host.json"
        record.write_text(json.dumps(host.to_json()), encoding="utf-8")
        ensure(cd.read_output(record) == host, "a record round-trips through its file")
        ensure(host.to_json()["encoding"] == cd.ENCODING and host.output_length == 5,
               "the record names its encoding and measures its bytes")
        record.write_text(json.dumps({"encoding": "other/1"}), encoding="utf-8")
        try:
            cd.read_output(record)
        except ValueError as err:
            ensure(cd.ENCODING in str(err), f"a foreign record is refused by name: {err}")
        else:
            raise AssertionError("a foreign record must be refused")

        same = cd.output_of("purecap", 0, b"true\n", "fake sim")
        ensure(cd.compare_outputs(host, same) is None, "equal sides agree")
        verdict = cd.compare_outputs(host, cd.output_of("purecap", 1, b"true\n", ""))
        ensure(verdict is not None and verdict.field == "verdict"
               and verdict.line() == "verdict: host 0, purecap 1",
               f"the verdict is compared first: {verdict}")
        length = cd.compare_outputs(host, cd.output_of("purecap", 0, b"true", ""))
        ensure(length is not None and length.field == "output_length", f"then length: {length}")
        digest = cd.compare_outputs(host, cd.output_of("purecap", 0, b"trve\n", ""))
        ensure(digest is not None and digest.field == "output_sha256",
               f"then the digest where no bytes are in hand: {digest}")
        byte = cd.compare_outputs(host, cd.output_of("purecap", 0, b"trve\n", ""),
                                  b"true\n", b"trve\n")
        ensure(byte is not None and byte.line() == "output byte 2: host 0x75, purecap 0x76",
               f"and the first differing byte where they are: {byte}")

        node = [sys.executable, str(_script(scratch, "node", FAKE_NODE))]
        got, raw = cd.wasm_output(scratch / "demo.wasm", node, scratch)
        ensure(got.verdict == 0 and raw == b"true\n" and got.output_sha256 == host.output_sha256
               and got.side == "wasm-host", f"the Wasm host's side is read: {got}")
        seeded, _ = cd.wasm_output(scratch / "demo_seeded.wasm", node, scratch)
        ensure(seeded.verdict == 1 and seeded.output_head == "false\n",
               f"a seeded module's red line is read as its verdict: {seeded}")
        sim = [sys.executable, str(_script(scratch, "sim", FAKE_SIM))]
        purecap, raw = cd.purecap_output(scratch / "comp.elf", sim, scratch / "p.json", scratch)
        ensure(purecap.side == "purecap" and purecap.verdict == 0 and raw == b"true\n",
               f"the purecap side is the HTIF code and the terminal log: {purecap}")
        ensure(cd.compare_outputs(got, purecap, b"true\n", raw) is None,
               "the two sides agree under the encoding when both say true")
        ensure(cd.compare_outputs(seeded, purecap) is not None,
               "and a seeded host side disagrees")


def _run_cli(argv: list[str]) -> tuple[int, str, str]:
    out, err = StringIO(), StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        code = cd.main(argv)
    return code, out.getvalue(), err.getvalue()


def _cli_program() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        ccomp = _wrapper(scratch, "ccomp", _script(scratch, "fake_ccomp", FAKE_CCOMP))
        sim = _wrapper(scratch, "sim", _script(scratch, "fake_sim", FAKE_SIM))
        base = ["program", "--ccomp", str(ccomp), "--generate", "2", "--seed", "5", "--json"]
        first = _run_cli([*base, "--expect-refusal"])
        second = _run_cli([*base, "--expect-refusal"])
        ensure(first == second, f"the report must be deterministic:\n{first}\n{second}")
        code, out, _ = first
        payload = json.loads(out)
        ensure(code == 0 and payload["green"] and payload["milestone_acceptance"] == "open"
               and payload["summary"]["dialect-refused"] == 2,
               f"ahead of the backend every stream is refused and that is green: {out[-600:]}")
        ensure(all(any(r["name"] == "jr" and r["kind"] == "mnemonic" for r in p["refusals"])
                   for p in payload["programs"]), "each program's refusals name jr")
        ensure(payload["ccomp"]["sha256"] is not None and payload["simulator"] is None,
               "the compiler is identified and the absent emulator is said")
        ensure(_run_cli(base)[0] == 1, "without --expect-refusal a refused stream is not green")
        baseline = scratch / "refused.json"
        baseline.write_text(first[1], encoding="utf-8")
        code, out, _ = _run_cli([*base, "--expect-refusal", "--against", str(baseline),
                                 "--seed", "6"])
        ensure(code == 1 and not json.loads(out)["green"],
               "--expect-refusal must still fail a requested comparison that disagrees")

        given = scratch / "given.c"
        given.write_text(DIALECT_C, encoding="utf-8")
        code, out, _ = _run_cli(["program", "--ccomp", str(ccomp), str(given),
                                 "--simulator", str(sim), "--profile", str(scratch / "p")])
        ensure(code == 0 and "PASS" in out and "capability round trip: yes" in out
               and "every program answered both questions" in out,
               f"a dialect stream runs green through the CLI: {out}")
        code, out, _ = _run_cli(["program", "--ccomp", str(ccomp), str(given),
                                 "--simulator", str(sim), "--json",
                                 "--ccomp-arg=-fverifiedos-typed",
                                 "--ccomp-arg=one argument with spaces"])
        argv = json.loads(out)["programs"][0]["ccomp"]["argv"]
        ensure(argv[1:3] == ["-fverifiedos-typed", "one argument with spaces"],
               "compiler arguments reach the process unchanged and remain in its receipt")
        recorded = scratch / "recorded.json"
        recorded.write_text(out, encoding="utf-8")
        code, out, _ = _run_cli(["program", "--ccomp", str(ccomp), str(given),
                                 "--simulator", str(sim), "--against", str(recorded)])
        ensure(code == 0 and "0 disagreement(s)" in out,
               f"a run held against its own record agrees: {out}")
        code, out, _ = _run_cli(["program", "--ccomp", str(ccomp), "--generate", "1",
                                 "--simulator", str(sim), "--against", str(recorded)])
        ensure(code == 1 and "DISAGREE" in out and "not in the recorded run" in out,
               f"a program the record lacks is a disagreement: {out}")
        ensure(_run_cli(["program", "--ccomp", str(ccomp)])[0] == 2, "nothing to compile is 2")
        ensure(_run_cli(["program", "--ccomp", str(ccomp), str(scratch / "absent.c")])[0] == 2,
               "an unreadable source is 2")
        ensure(_run_cli(["program", "--ccomp", str(ccomp), str(given), str(given)])[0] == 2,
               "duplicate input names must be refused before they reuse output paths")


def _fresh_compilation_and_complete_execution() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        source = scratch / "kept.c"
        source.write_text(DIALECT_C, encoding="utf-8")
        compiler = [sys.executable, str(_script(scratch, "compiler", FAKE_CCOMP))]
        fresh = scratch / "kept"
        ensure(cd.compile_c(compiler, source, fresh).stream is not None,
               "the first compiler invocation leaves an assembly stream")
        silent = [sys.executable, str(_script(scratch, "silent", "pass\n"))]
        got = cd.compile_c(silent, source, fresh)
        ensure(got.stream is None and not (fresh / "kept.s").exists(),
               "a compiler that writes nothing cannot reuse a kept assembly stream")
        ensure(cd.htif_verdict("SUCCESS\n", 1)[0] == "no-verdict",
               "a crashed emulator cannot pass using an earlier success line")
        ensure(cd.htif_verdict("NOT SUCCESS\n", 0)[0] == "no-verdict",
               "a success substring is not the HTIF success line")
        ensure(cd.htif_verdict("SUCCESS\nFAILURE: 2\n", 0)[0] == "fail",
               "a failure cannot be masked by a success line")
        simulator = [sys.executable, str(_script(scratch, "no_trace", "print('SUCCESS')\n"))]
        run = cd.run_image(simulator, scratch / "p.json", scratch / "x.elf", scratch)
        ensure(run.verdict == "no-verdict" and run.code is None and "commit trace" in run.detail,
               "HTIF success alone cannot supply the trace half of a program result")


def _component_rejects_missing_or_wrong_evidence() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        host, purecap = scratch / "host.json", scratch / "purecap.json"
        absent_host = cd.output_of("wasm-host", None, b"", "failed to launch")
        absent_purecap = cd.output_of("purecap", None, b"", "failed to launch")
        host.write_text(json.dumps(absent_host.to_json()), encoding="utf-8")
        purecap.write_text(json.dumps(absent_purecap.to_json()), encoding="utf-8")
        args = ["component", "--host-record", str(host), "--purecap-record", str(purecap)]
        for extra in ([], ["--json"]):
            code, _, _ = _run_cli([*args, *extra])
            ensure(code == 1, "two failed runs with no verdict cannot agree")
            ensure(_run_cli(["component", "--host-record", str(host), *extra])[0] == 1,
                   "an incomplete single-side capture must also report failure")
        valid = cd.output_of("wasm-host", 0, b"true\n", "node")
        host.write_text(json.dumps(valid.to_json()), encoding="utf-8")
        ensure(_run_cli(["component", "--host-record", str(host), "--purecap-record",
                         str(host)])[0] == 2,
               "a host record cannot stand in for an independent purecap result")
        for field, value in (("verdict", False), ("output_length", True),
                             ("output_length", -1), ("output_sha256", "")):
            malformed = valid.to_json()
            malformed[field] = value
            host.write_text(json.dumps(malformed), encoding="utf-8")
            ensure(_run_cli(["component", "--host-record", str(host)])[0] == 2,
                   f"malformed {field} must be rejected before comparison")


def _cli_component_and_generate() -> None:
    with tempfile.TemporaryDirectory(prefix="vos-test-") as td:
        scratch = Path(td)
        node = _script(scratch, "fake_node", FAKE_NODE)
        host, purecap = scratch / "host.json", scratch / "purecap.json"
        code, out, _ = _run_cli(["component", "--wasm", str(scratch / "x.wasm"), "--runner",
                                 sys.executable, "--runner", str(node), "--write-host",
                                 str(host)])
        ensure(code == 0 and "WAITS" in out and "purecap side" in out and host.is_file(),
               f"one side alone is recorded and the other is said to wait: {out}")
        purecap.write_text(json.dumps(cd.output_of("purecap", 0, b"true\n", "by hand").to_json()),
                           encoding="utf-8")
        code, out, _ = _run_cli(["component", "--host-record", str(host), "--purecap-record",
                                 str(purecap)])
        ensure(code == 0 and "AGREE" in out, f"two agreeing records are green: {out}")
        purecap.write_text(json.dumps(cd.output_of("purecap", 3, b"true\n", "by hand").to_json()),
                           encoding="utf-8")
        first = _run_cli(["component", "--host-record", str(host), "--purecap-record",
                          str(purecap), "--json"])
        ensure(first == _run_cli(["component", "--host-record", str(host), "--purecap-record",
                                  str(purecap), "--json"]), "the report is deterministic")
        code, out, _ = first
        payload = json.loads(out)
        ensure(code == 1 and payload["disagreement"] == "verdict: host 0, purecap 3"
               and payload["compared"] and payload["encoding"] == cd.ENCODING,
               f"a verdict disagreement is named: {out}")
        ensure(_run_cli(["component"])[0] == 2, "no side at all is 2")
        purecap.write_text("{}", encoding="utf-8")
        ensure(_run_cli(["component", "--purecap-record", str(purecap)])[0] == 2,
               "a record of the wrong encoding is 2")

        ccomp = _wrapper(scratch, "ccomp", _script(scratch, "fake_ccomp", FAKE_CCOMP))
        sim = _wrapper(scratch, "sim", _script(scratch, "fake_sim", FAKE_SIM))
        given = scratch / "comp.c"
        given.write_text(DIALECT_C, encoding="utf-8")
        lowered = ["component", "--wasm", str(scratch / "x.wasm"), "--runner", sys.executable,
                   "--runner", str(node), "--c", str(given), "--ccomp", str(ccomp),
                   "--simulator", str(sim), "--profile", str(scratch / "p.json"),
                   "--interp", "--json"]
        code, out, _ = _run_cli(lowered)
        payload = json.loads(out)
        bound = payload["bindings"]
        ensure(code == 0 and payload["disagreement"] is None and not payload["source_disagrees"]
               and bound["elf_sha256"] and bound["stream_sha256"]
               and bound["c_source"]["sha256"] == cd._sha256(given.read_bytes())
               and bound["interp"]["code"] == 0 and bound["wasm_module"]["sha256"] is None,
               f"a component lowered from C agrees and binds each stage by digest: {out}")
        given.write_text(DIALECT_C + "/* FAKE-CCOMP: interp 4 */\n", encoding="utf-8")
        code, out, _ = _run_cli(lowered)
        ensure(code == 1 and json.loads(out)["source_disagrees"],
               f"an image the interpreter disagrees with is not agreement: {out}")
        given.write_text(REFUSING_C, encoding="utf-8")
        code, out, _ = _run_cli(lowered)
        ensure(code == 1 and json.loads(out)["purecap"]["verdict"] is None
               and "lowering stopped" in json.loads(out)["purecap"]["produced_by"],
               f"a refused lowering gives the purecap side no verdict: {out}")
        ensure(_run_cli(["component", "--c", str(given)])[0] == 2,
               "a C component with no compiler is 2")

        out_dir = scratch / "campaign"
        code, out, _ = _run_cli(["generate", "--out", str(out_dir), "--count", "3", "--seed", "2"])
        manifest = json.loads((out_dir / "manifest.json").read_text(encoding="utf-8"))
        ensure(code == 0 and len(manifest["programs"]) == 3
               and sorted(p.name for p in out_dir.glob("*.c"))
               == sorted(f"{row['name']}.c" for row in manifest["programs"]),
               f"the campaign is written with its manifest: {out}")
        ensure(all(row["sha256"] == cd._sha256((out_dir / f"{row['name']}.c").read_bytes())
                   for row in manifest["programs"]), "each row digests its file")


def cases() -> list[Case]:
    return [
        Case("generator-is-deterministic", _generator_is_deterministic),
        Case("perturbed-twins-move-one-check", _perturbed_twins_move_one_check),
        Case("scan-names-what-the-dialect-refuses", _scan_names_what_the_dialect_refuses),
        Case("harness-assembles-a-dialect-stream", _harness_assembles_a_dialect_stream),
        Case("component-harness-assembles", _component_harness_assembles),
        Case("harness-authority-on-sail", _harness_authority_on_sail,
             slow=True, lane="toolchain"),
        Case("component-harness-on-sail", _component_harness_on_sail,
             slow=True, lane="toolchain"),
        Case("source-interpreter-reading", _source_interpreter_reading),
        Case("narrowing-program-inputs", _narrowing_program_inputs),
        Case("narrowing-rerun-in-a-kept-directory", _narrowing_rerun_in_a_kept_directory),
        Case("capability-roundtrip-tracks-the-stored-value",
             _capability_roundtrip_tracks_the_stored_value),
        Case("loop-over-fake-ccomp-dialect", _loop_over_fake_ccomp_dialect),
        Case("loop-over-fake-ccomp-lp64d", _loop_over_fake_ccomp_lp64d),
        Case("recorded-run-disagreements", _recorded_run_disagreements),
        Case("component-encoding-and-comparator", _component_encoding_and_comparator),
        Case("cli-program", _cli_program),
        Case("fresh-compilation-and-complete-execution", _fresh_compilation_and_complete_execution),
        Case("component-rejects-missing-or-wrong-evidence", _component_rejects_missing_or_wrong_evidence),
        Case("cli-component-and-generate", _cli_component_and_generate),
    ]
