# SPDX-License-Identifier: Apache-2.0
"""The emission receipt refuses missing, changed and misattributed generated bytes."""

import json
import tempfile
from collections.abc import Callable
from pathlib import Path

import fiat_crypto_emit as fiat

from tests.harness import Case, ensure


def _refuses(action: Callable[[], object]) -> None:
    try:
        action()
    except (ValueError, OSError):
        return
    raise AssertionError("invalid emission was accepted")


def _headers() -> None:
    with tempfile.TemporaryDirectory() as temporary:
        folder = Path(temporary)
        generated = dict.fromkeys(fiat.RECIPES, b"/* literal generator bytes */\n")
        recorded = {"schema": 1, "source_pin": fiat.PIN, "recipes": fiat.RECIPES,
                    "outputs": {name: {"raw_sha256": fiat.digest(raw),
                                       "header_sha256": fiat.digest(fiat.wrap(name, raw))}
                                for name, raw in generated.items()}}
        for name, raw in generated.items():
            (folder / name).write_bytes(fiat.wrap(name, raw))
        fiat.verify_outputs(folder, recorded, generated)
        first = folder / next(iter(generated))
        before = first.read_bytes()
        first.write_bytes(before.replace(b"literal", b"altered"))
        _refuses(lambda: fiat.verify_outputs(folder, recorded, generated))
        first.write_bytes(before)
        _refuses(lambda: fiat.verify_outputs(folder, recorded, {}))
        first.unlink()
        _refuses(lambda: fiat.verify_outputs(folder, recorded, generated))


def _sources() -> None:
    with tempfile.TemporaryDirectory() as temporary:
        folder = Path(temporary)
        archive = folder / "source.tar"
        archive.write_bytes(b"archived source fixture")
        receipt = folder / "source.json"
        rows = [{"path": ".", "revision": fiat.PIN, "archive": archive.name}]
        receipt.write_text(json.dumps(rows), encoding="utf-8")
        before = fiat.source_receipt(receipt)
        archive.write_bytes(b"changed archived source")
        ensure(fiat.source_receipt(receipt) != before, "archive content must bind the receipt")
        rows[0]["revision"] = "0" * 40
        receipt.write_text(json.dumps(rows), encoding="utf-8")
        _refuses(lambda: fiat.source_receipt(receipt))
        rows[0]["revision"] = fiat.PIN
        rows[0]["archive"] = "../source.tar"
        receipt.write_text(json.dumps(rows), encoding="utf-8")
        _refuses(lambda: fiat.source_receipt(receipt))
        receipt.write_text("[null]", encoding="utf-8")
        _refuses(lambda: fiat.source_receipt(receipt))


def cases() -> list[Case]:
    return [Case("header-and-receipt-drift", _headers), Case("source-pin-and-archive", _sources)]
