# SPDX-License-Identifier: Apache-2.0
"""Check authored proof citations and the boundary around generated references.

K-103 resolves every requirement citation outside derived regions against the live
register. Its subject is the index's proof files; an empty, unreadable or citation-free
set fails. Generated references are excluded so the manifest cannot choose its own
membership. Legacy transcriptions cannot introduce their transitive citations either.

K-108 validates balanced delimiters, permitted generated content and the requirement
set that authored citations can introduce. Its executable probes keep the exclusion
tested even when no region is present. K-109, in headers.py, checks exact generated bytes
and repairs them after arithmetic. Citation choices and authored rationale are never
repaired by either rule.
"""

import re
from typing import TYPE_CHECKING

from vos import proofcites
from vos.register import REGISTER

# `Context` lives in this package's __init__, which imports this module in turn.
# Guarded, so the annotations below cost no import at run time: under PEP 649 an
# annotation is not evaluated unless something asks for it, and nothing here does.
if TYPE_CHECKING:
    from vos.register import Register

    from . import Context

HEADING = "=== citations: what the proof artifacts cite, against the register ==="

MODULE = "tools/vos/proofcites.py"

# One artifact as this group reads it: where it is, what it says, and where its derived
# regions are. The delimiter parse is made once in `run` and handed to both rules below,
# which is what keeps the exclusion at one whole-text pass over each file rather than at
# one per rule reading through it.
type Artifact = tuple[str, str, proofcites.Derived]

# The vernaculars a derived region may not open a line with, and the shape one takes.
# `proofcites.DEFINERS` is every sentence that binds a top-level name, and the four
# commands beside it are what a region that has swallowed the file it sits in carries
# first. The shape is what keeps the reading sharp: a definer counts only where a name
# follows it, and the four stand alone before their period, so an ordinary English
# sentence opening with one of these words inside a transcription is not read as code.
_COMMANDS = ("Require", "Import", "Export", "Axiom", "Parameter", "Hypothesis",
             "Ltac", "Notation")
_STANDALONE = ("Proof", "Qed", "Defined", "Admitted")
_VERNACULAR_RE = re.compile(
    rf"^\s*(?:{proofcites.MODIFIERS}"
    rf"(?:{'|'.join((*proofcites.DEFINERS, *_COMMANDS))})\s+[\w'(]"
    rf"|(?:{'|'.join(_STANDALONE)})\s*\.)")

_ID = r"R-\d\d-\d+[a-z]?"
_MANIFEST_RE = re.compile(
    rf"\s*Owner: {re.escape(REGISTER)}\r?\n"
    rf"[ \t]+Requirements: {_ID}(?:[ \t\r\n]+{_ID})*\r?\n"
    r"[ \t]+SHA256: [0-9a-f]{64}\s*\Z")


def _manifest(body: str) -> bool:
    """Recognize an attempted manifest, including one with missing or broken fields."""
    return any(line.lstrip().startswith(("Owner:", "Requirements:", "SHA256:"))
               for line in body.splitlines())

# The two ids the probe is written over. They are shaped like requirement ids and are
# deliberately not read against the register: what the probe decides is the exclusion's
# behaviour over a text this rule composes, and a live id here would make it look like a
# reading of the corpus, which it is not.
_OUTSIDE = "R-99-001"
_INSIDE = "R-99-002"


def run(ctx: Context) -> None:
    rep = ctx.rep
    rep.line(HEADING)

    rels = [rel for rel in ctx.corpus.tracked if proofcites.is_source(rel)]
    # An artifact this run could not open is handed to both rules, because neither can
    # decide about a file it has no bytes of; the empty index is spelled at each rule
    # instead, in the terms that rule reads, since what is missing there is not the same
    # thing twice.
    pairs, faults = proofcites.read(ctx.root, rels)
    read = [(rel, text, proofcites.derived(text)) for rel, text in pairs]

    _cited(ctx, rels, read, faults)
    _regions(ctx, rels, read, faults)
    rep.line()


def _absent(what: str) -> list[str]:
    """The finding an index carrying no proof artifact at all is, in a rule's own terms."""
    return [f"the git index carries no {proofcites.SUFFIX} file under "
            f"{proofcites.PROOFS}/, so there is no proof artifact for this rule to "
            f"{what}"]


def _cited(ctx: Context, rels: list[str], read: list[Artifact],
           faults: list[str]) -> None:
    """K-103: every citation a shipped proof artifact makes names a live requirement."""
    rep, reg = ctx.rep, ctx.reg
    findings = list(faults) if rels else _absent("read a citation out of") + faults

    total = 0
    distinct: set[str] = set()
    for rel, text, region in read:
        cited = proofcites.ids(text, region)
        total += len(cited)
        distinct |= set(cited)
        findings += [f"{rel} cites {ident}, which names no live requirement: the "
                     "register declares no such entry, or has struck it"
                     for ident in sorted(set(cited)) if ident not in reg.id_set]

    if rels and not total:
        findings.append(f"the {len(read)} proof artifacts make no requirement citation "
                        "at all, so this rule would agree with every one of no citations")

    rep.report("K-103", "proof citation(s) naming no live requirement:", findings,
               f"all {total} requirement citations the {len(read)} proof artifacts "
               f"make, {len(distinct)} of them distinct, name a live requirement of the "
               "register")


def _transcribable(reg: Register, cited: set[str]) -> set[str]:
    """IDs permitted in legacy normative transcriptions, excluding criteria."""
    named = set(cited)
    for ident in cited:
        body = reg.body.get(ident)
        if body:
            named |= set(proofcites.ids(body))
    return named


def _content(rel: str, text: str, span: tuple[int, int]) -> list[str]:
    """Permit a compact reference manifest or a legacy normative transcription.

    A blank line is admitted, a line naming a requirement is a transcribed entry line,
    and an indented line under one is its continuation, which is how a long normative
    line arrives inside a header wrapped. Anything else is prose a regeneration would
    delete or code it would delete, and the two are told apart because the finding a
    reader gets should say which of the two it is looking at.
    """
    body = text[span[0]:span[1]]
    if _manifest(body):
        if _MANIFEST_RE.fullmatch(body):
            return []
        return [f"{rel}:{proofcites.line_at(text, span[0])} has a malformed reference "
                "manifest; only its register Owner, Requirements IDs and SHA256 "
                "fields are permitted"]
    found: list[str] = []
    entry = False
    for n, line in enumerate(text[span[0]:span[1]].splitlines(),
                             start=proofcites.line_at(text, span[0])):
        if not line.strip():
            continue
        if _VERNACULAR_RE.match(line):
            found.append(f"{rel}:{n} opens a vernacular inside a derived region, which "
                         "is either the region swallowing the file it sits in or a "
                         "definition the next regeneration would delete")
            continue
        if proofcites.ids(line):
            entry = True
            continue
        if not (entry and line[:1].isspace()):
            found.append(f"{rel}:{n} is inside a derived region and names no "
                         "requirement, so it is neither a transcribed entry line nor "
                         "the continuation of one")
    return found


def _probe() -> tuple[int, list[str]]:
    """The exclusion held against its own contract, which is this rule's floor.

    A tree with no regions still tests the shared parse against texts composed from
    the module's delimiters. Four readings, because the
    exclusion can fail in four directions and only one of them is the obvious one: it
    can stop excluding, it can over-reach past a region, it can reach text no delimiter
    marks, and it can swallow an imbalance instead of reporting it.
    """
    plain = f"an artifact citing {_OUTSIDE} and {_INSIDE}\n"
    region = (f"an artifact citing {_OUTSIDE}\n{proofcites.DERIVED_BEGIN}\n"
              f"**{_INSIDE}** MUST be transcribed here.\n{proofcites.DERIVED_END}\n")
    unclosed = (f"an artifact citing {_OUTSIDE}\n{proofcites.DERIVED_BEGIN}\n"
                f"**{_INSIDE}** MUST be transcribed here.\n")

    readings: list[tuple[str, bool]] = [
        ("text no delimiter marks is read whole",
         proofcites.ids(plain) == [_OUTSIDE, _INSIDE]),
        ("what a region carries is held out of the citation reading",
         proofcites.ids(region) == [_OUTSIDE]),
        ("a well-formed region is one span and no fault",
         len(proofcites.derived(region).spans) == 1
         and not proofcites.derived(region).faults),
        ("an unclosed region is a fault and excludes nothing",
         bool(proofcites.derived(unclosed).faults)
         and proofcites.ids(unclosed) == [_OUTSIDE, _INSIDE]),
    ]
    return len(readings), [f"{MODULE} no longer holds that {what}, so the exclusion "
                           "this rule guards has moved under it"
                           for what, held in readings if not held]


def _regions(ctx: Context, rels: list[str], read: list[Artifact],
             faults: list[str]) -> None:
    """K-108: a derived region references what its artifact already cites.

    Fail-closed where K-103 is: an index carrying no artifact leaves this rule nothing
    to read a region out of, and an artifact whose bytes this run could not get is one
    whose regions are undecided rather than absent. Floored on the probe rather than on
    a member count, so a tree with no derived region at all still decides that the
    exclusion excludes, which is the property that stops it widening while nobody looks.
    """
    rep, reg = ctx.rep, ctx.reg
    findings = list(faults) if rels else _absent("read a derived region out of") + faults

    probes, moved = _probe()
    findings += moved

    regions = lines = 0
    for rel, text, region in read:
        findings += [f"{rel}: {fault}" for fault in region.faults]
        if not region.spans:
            continue
        cited = set(proofcites.ids(text, region))
        for span in region.spans:
            allowed = cited if _manifest(text[span[0]:span[1]]) else _transcribable(reg, cited)
            regions += 1
            lines += sum(1 for line in text[span[0]:span[1]].splitlines() if line.strip())
            findings += _content(rel, text, span)
            findings += [
                f"{rel} names {ident} inside a derived region beyond its permitted "
                "authored citations or legacy transcriptions, so the region is "
                "holding a citation out of K-103's reading"
                for ident in sorted(set(proofcites.cited_within(text, span)))
                if ident not in allowed]

    rep.report("K-108", "derived region(s) the citation exclusion cannot be held to:",
               findings,
               f"the {len(read)} proof artifacts' derived-region delimiters balance, "
               f"the {lines} lines their {regions} regions carry reference only "
               f"permitted entries, and the exclusion holding a region out "
               f"of K-103's reading answers at each of its {probes} probes")
