# SPDX-License-Identifier: Apache-2.0
"""keccak: the two transcriptions of FIPS 202 against the answers both of them quote.

M3.4a authored [proofs/Keccak.v](../../../proofs/Keccak.v) as a second transcription of
FIPS 202, deliberately against the same standard and the same published known answers
as the Sail unit under
[model/model/extensions/keccak/](../../../model/model/extensions/keccak/), so that the
two are a differential pair rather than two independent chances to be wrong. What makes
them a pair is a shared answer: three all-zero permutation states appear as constants in
both files, one per frozen round count plus the doubled application, and each file's own
gate decides its transcription against its own copy of them.

**A discipline with no holder is a sentence.** Each gate is green on its own copy, so a
constant edited on one side alone leaves both gates green and the pair silently reduced
to two independent transcriptions: the Coq file still compiles and still proves its
`Example`, the Sail unit still passes its harness, and the one property the pair was
built for, that both were checked against the same answer, has gone without anything
saying so. That is the defect this rule holds, and it is a cross-artifact fact no other
rule reaches: K-88 and K-89 hold generated artifacts against their generators, and
neither of these files is generated by anything.

**Neither side is normalized into the other's shape by hand.** The two files write the
same state in two orders and two radices: the Sail literal is twenty-five sixty-four-bit
words in the standard's lane order, and the Coq `Example` is two hundred bytes, eight per
lane with the least significant first, which is FIPS 202 sB.1. Both are decoded to the
same twenty-five integers here and compared as numbers, so a rewrite of either file's
presentation that preserves the state is not a finding and a byte that moved is, whichever
side it moved on.

**Reaching into `proofs/` costs no corpus-window change**, which is the precedent
[bindings.py](bindings.py) already sets by reading the apex statement off `ctx.root`: this
checker's corpus is the git index and is the subject of the total-class rules, where a
rule that names two paths reads them itself. Membership is by name accordingly, three
pairs of named constants held in this module, so nothing about the pair can quietly
narrow by a document being edited.

Fail-closed in five places on K-67's and K-75's ground. A file the index does not carry is
outside this checker's corpus and every claim about it is vacuous; a file the working tree
does not carry has no bytes to read; a literal or an `Example` this module cannot locate by
name is a finding rather than a pair dropped out of the comparison; a literal that does not
decode to twenty-five lanes, or an `Example` to two hundred bytes, is the same; and the
pair table reading empty would leave the rule agreeing with every one of no answers, so its
size is a floor stated here rather than a count taken from a document.

**`--fix` does not repair it**, on the ground K-89 and the co-read ledger already state:
either side may be the one that is right, the interesting fact is which file moved, and a
known answer rewritten by the wave that was supposed to report it is a differential pair
repaired into agreement with itself.
"""

import re
from typing import TYPE_CHECKING

from vos.corpus import staged_bytes

# `Context` lives in this package's __init__, which imports this module in turn.
if TYPE_CHECKING:
    from . import Context

HEADING = "=== keccak: the two FIPS 202 transcriptions against the answers both quote ==="

GALLINA = "proofs/Keccak.v"
SAIL = "model/model/unit_tests/test_keccak.sail"

LANES = 25
LANE_BYTES = 8

# The three answers both files carry: the Coq `Example` that states one, the Sail literal
# that states the same one, and what the state is of. Held here rather than located by a
# pattern, so the set cannot narrow under an edit to either file.
PAIRS: list[tuple[str, str, str]] = [
    ("keccak_f1600_of_the_all_zero_state",
     "keccak_kat_zero_24",
     "Keccak-f[1600] of the all-zero state"),
    ("keccak_f1600_applied_twice_to_the_all_zero_state",
     "keccak_kat_zero_24_twice",
     "Keccak-f[1600] applied twice to the all-zero state"),
    ("keccak_p1600_12_of_the_all_zero_state",
     "keccak_kat_zero_12",
     "Keccak-p[1600,12] of the all-zero state"),
]

_BYTE_RE = re.compile(r"0x([0-9A-Fa-f]{2})\b")
_WORD_RE = re.compile(r"0x([0-9A-Fa-f]{16})\b")


def _gallina_state(raw: str, name: str) -> tuple[list[int] | None, str]:
    """The twenty-five lanes one `Example` states, or why they could not be read.

    The statement's right-hand side is two hundred byte literals, eight per lane with the
    least significant first, so the lanes are recomposed here rather than compared as
    bytes: the Sail side has no bytes to compare against.
    """
    m = re.search(rf"(?s)^Example {re.escape(name)}\s*:(.*?)^Proof\.", raw, re.MULTILINE)
    if m is None:
        return None, f"{GALLINA} states no Example named {name}"
    body = m.group(1)
    eq = body.find("=")
    if eq < 0:
        return None, f"{GALLINA}'s {name} states no equation to read an answer out of"
    octets = [int(b, 16) for b in _BYTE_RE.findall(body[eq:])]
    if len(octets) != LANES * LANE_BYTES:
        return None, (f"{GALLINA}'s {name} states {len(octets)} byte(s) where a 1600-bit "
                      f"state is {LANES * LANE_BYTES}")
    return [sum(octets[i * LANE_BYTES + j] << (8 * j) for j in range(LANE_BYTES))
            for i in range(LANES)], ""


def _sail_state(raw: str, name: str) -> tuple[list[int] | None, str]:
    """The twenty-five lanes one Sail literal states, or why they could not be read.

    Written in the standard's lane order and read through `keccak_state_of_literal`, a
    Sail vector literal being `dec`-ordered, so the order the words are written in is the
    lane order and this reads them as written.
    """
    m = re.search(rf"(?s)\blet {re.escape(name)}\s*:\s*keccak_state\s*=\s*\[(.*?)\]", raw)
    if m is None:
        return None, f"{SAIL} states no keccak_state literal named {name}"
    words = [int(w, 16) for w in _WORD_RE.findall(m.group(1))]
    if len(words) != LANES:
        return None, (f"{SAIL}'s {name} states {len(words)} lane(s) where a 1600-bit "
                      f"state is {LANES}")
    return words, ""


def run(ctx: Context) -> None:
    rep = ctx.rep
    rep.line(HEADING)

    findings: list[str] = []
    texts: dict[str, str] = {}
    for path in (GALLINA, SAIL):
        if staged_bytes(ctx.root, path) is None:
            findings.append(f"the git index does not carry {path}, so nothing this rule "
                            f"decides about the pair means anything")
            continue
        here = ctx.root / path
        if not here.is_file():
            findings.append(f"{path} is in the index and not in the working tree, so "
                            f"there are no bytes here to read")
            continue
        texts[path] = here.read_text(encoding="utf-8")

    if not PAIRS:
        findings.append("the known-answer pair table is empty, so this rule would agree "
                        "with every one of no answers")

    decided = 0
    if len(texts) == 2:
        for coq_name, sail_name, what in PAIRS:
            got, why = _gallina_state(texts[GALLINA], coq_name)
            if got is None:
                findings.append(why)
                continue
            want, why = _sail_state(texts[SAIL], sail_name)
            if want is None:
                findings.append(why)
                continue
            off = [i for i in range(LANES) if got[i] != want[i]]
            if off:
                i = off[0]
                findings.append(
                    f"{what} differs between the two transcriptions at {len(off)} lane(s), "
                    f"the first being lane {i}: {GALLINA}'s {coq_name} states "
                    f"{got[i]:#018x} where {SAIL}'s {sail_name} states {want[i]:#018x}")
            else:
                decided += 1

    rep.report("K-91", "known answer(s) the two FIPS 202 transcriptions disagree about:",
               findings,
               f"the {decided} known answer(s) {GALLINA} and {SAIL} both quote are the "
               f"same {LANES}-lane state, read through each file's own order")
    rep.line()
