# SPDX-License-Identifier: Apache-2.0
"""ring: the generated interface artifact against the two owners it is a function of.

The typed IDL profile's rule is that the declaration is the one authored owner of
everything a composition fixes and the artifact is a function of that declaration and
of the register alone, so no hand edit of the artifact survives. That rule needs a
holder or it is a sentence: a generated Gallina file renders correctly, compiles, and
passes the proof gate whatever a person typed into it, and the two closed enumerations
it carries from the register are exactly the kind of transcription this repository
catches elsewhere by re-deriving rather than by comparing two copies.

**This rule re-runs the generator.** It does not compare the artifact against a
recorded digest, because a digest is a third copy of the same fact and goes stale in
the same edit; it emits the artifact again from `interfaces/ring-reference.json` and
from the register's own entry lines, and holds the working tree's bytes against what
came back. So a status added at R-12-093, a state reordered at R-12-094, a constant
moved in the declaration, and a token typed into the artifact by hand are one finding
each, at the gate the edit lands at.

**Why the generator rather than a second parse.** The emitter lives in
[vos/cli/ring.py](../cli/ring.py) and this rule imports it. Writing a checker-side
re-derivation would be the two-copies-of-one-parse defect these tools exist to catch,
in the tools, and it would decide agreement between two things this repository wrote
rather than between the artifact and its owners.

**Fail-closed, on the ground the generated group already states.** An artifact the git
index does not carry is outside the checker's corpus and every claim about it is
vacuous; an artifact absent from the working tree has no bytes to read; and a generator
that raises is an owner that no longer carries what the emitter reads out of it, which
is this rule's finding rather than this rule's crash. The third is caught on the
emitter's own refusal *and* on every other exception, because those are one fact
arriving twice: the emitter names in [vos/cli/ring.py](../cli/ring.py) every key it
reads and refuses on each, and an owner shaped in a way none of those guards reaches
would otherwise leave the whole run dead rather than one rule red.

**`--fix` does not repair it**, deliberately, and the ground is the one the co-read
ledger already states for blessing. The repair is `run.py ring emit`, which rewrites
the artifact from the owners; running it from inside the checker would let an edit to
the artifact be absorbed silently by the same wave that was supposed to report it, and
the interesting case is not the drift but which owner moved.
"""

from typing import TYPE_CHECKING

from vos.cli import ring as emitter
from vos.corpus import staged_bytes

# `Context` lives in this package's __init__, which imports this module in turn.
if TYPE_CHECKING:
    from . import Context

HEADING = "=== ring: the generated interface artifact against its owners ==="

REPAIR = "run.py ring emit"


def run(ctx: Context) -> None:
    rep = ctx.rep
    rep.line(HEADING)

    findings: list[str] = []
    owners = 0
    try:
        wanted = emitter.emit(ctx.root, register=ctx.reg)
        owners = len(emitter.OWNED_ENTRIES)
    except emitter.RingError as exc:
        findings.append(f"{emitter.ARTIFACT} cannot be emitted: {exc}")
        wanted = None
    # The emitter's own refusal is above; this is the same fact arriving as any other
    # exception, which is what an owner shaped in a way no guard names looks like from
    # here. Both are this rule's finding, because a checker that dies on one owner
    # decides nothing about the rest of the run.
    except Exception as exc:
        findings.append(f"{emitter.ARTIFACT} cannot be emitted: the emitter raised "
                        f"{type(exc).__name__}: {exc}, so an owner no longer carries "
                        f"what it reads out of it in a shape any guard names")
        wanted = None

    if wanted is not None:
        if staged_bytes(ctx.root, emitter.ARTIFACT) is None:
            findings.append(
                f"{emitter.ARTIFACT} is generated by `{REPAIR}` and the git index does "
                f"not carry it, so nothing this checker decides about it means anything")
        else:
            path = ctx.root / emitter.ARTIFACT
            got = path.read_text(encoding="utf-8") if path.is_file() else None
            if got is None:
                findings.append(f"{emitter.ARTIFACT} is in the index and not in the "
                                f"working tree, so there is no artifact here to read")
            elif got != wanted:
                want_lines, got_lines = wanted.splitlines(), got.splitlines()
                where = next((i for i, (a, b) in enumerate(
                    zip(want_lines, got_lines, strict=False)) if a != b),
                    min(len(want_lines), len(got_lines)))
                findings.append(
                    f"{emitter.ARTIFACT}:{where + 1} is not what `{REPAIR}` writes from "
                    f"{emitter.DECLARATION} and the register; either an owner moved and "
                    f"the artifact was not regenerated, or the artifact was edited by "
                    f"hand")

    rep.report("K-89", "generated interface artifact(s) adrift from an owner:", findings,
               f"{emitter.ARTIFACT} is what `{REPAIR}` writes from "
               f"{emitter.DECLARATION} and the {owners} register entries it reads")
    rep.line()
