# SPDX-License-Identifier: Apache-2.0
"""Architectural block-image persistence through two independent HTIF runs.

This is the device half of M5.3d, not storage authentication or recovery. The
programs are generated from the same admitted geometry as block-authority and
assembled by the existing purecap assembler. Every read compares the complete
medium, including untouched blocks. Image receipts bind the process boundary.
"""

import hashlib
import json
import subprocess
import time
from pathlib import Path
from typing import cast

from vos import asm, block_authority, config, receipts, trace


def payload(length: int) -> bytes:
    return bytes((0xA7 + 29 * i) % 256 for i in range(length))


def expected_image(root: Path) -> bytes:
    f = block_authority.fixture(root)
    return (b"VOSBLK01" + f.block_bytes.to_bytes(8, "little")
            + f.block_count.to_bytes(8, "little") + bytes(8)
            + f.backing[:-f.block_bytes] + payload(f.block_bytes))


def program(root: Path, phase: str, *, wrong_byte: bool = False) -> str:
    """Emit a writer without status observation, a flush writer, or a reader."""
    if phase not in {"durable", "flush", "reopen"}:
        raise ValueError("unknown block persistence phase")
    f = block_authority.fixture(root)
    profile = root / block_authority.CONFIG
    ticks = config.integer(profile, "platform", "instructions_per_tick")
    write_steps = config.integer(profile, "platform", "blkdev", "write_steps")
    flush_steps = config.integer(profile, "platform", "blkdev", "flush_steps")
    if ticks is None or write_steps is None or flush_steps is None:
        raise ValueError("missing block-device timing")
    # Resource bound of the finite generated campaign, not a device contract.
    delay = ticks * write_steps + 1
    if delay > 100000 or ticks * flush_steps > 100000:
        raise ValueError("block persistence timing exceeds the campaign bound")
    poll_limit = max(f.poll_limit, ticks * flush_steps + 8)
    lines = ["# SPDX-License-Identifier: Apache-2.0",
             "# Generated by vos.block_persistence.program.",
             "        .text", "        .globl _start", "_start:",
             "        cmove c8, c1", "        li gp, 1",
             f"        li t0, {f.base}", "        csetaddr c9, c8, t0",
             f"        li t0, {f.size}", "        csetbounds c9, c9, t0"]
    serial = 0

    def put(*items: str) -> None:
        nonlocal serial
        # A large fixture can exceed the conditional branch displacement.
        for item in items:
            if item.endswith(", fail") and item.startswith("bne "):
                serial += 1
                lines.extend(("        beq " + item[4:-6] + f", next_{serial}",
                              "        j fail", f"next_{serial}:"))
            else:
                lines.append("        " + item)

    def equal(offset: int, value: int) -> None:
        put(f"ld t1, {offset}(c9)", f"li t2, {value}", "bne t1, t2, fail")

    def ack() -> None:
        put("li t0, 1", "sd t0, 56(c9)")

    def submit(command: int) -> None:
        put(f"li t0, {command}", "sd t0, 48(c9)")

    def complete() -> None:
        nonlocal serial
        serial += 1
        label = serial
        put(f"li t3, {poll_limit}")
        lines.append(f"poll_{label}:")
        put("ld t1, 24(c9)", "li t2, 2", f"beq t1, t2, done_{label}",
            "addi t3, t3, -1", f"bnez t3, poll_{label}", "j fail")
        lines.append(f"done_{label}:")
        equal(32, 0)

    for offset, value in ((0, 1), (8, f.block_bytes), (16, f.block_count),
                          (24, 0), (32, 0), (40, 0)):
        equal(offset, value)
    put("li gp, 2")
    if phase in {"durable", "flush"}:
        put(f"li t0, {f.block_count - 1}", "sd t0, 40(c9)")
        raw = payload(f.block_bytes)
        for offset in range(0, f.block_bytes, 8):
            put(f"li t0, {int.from_bytes(raw[offset:offset + 8], 'little')}",
                f"sd t0, {256 + offset}(c9)")
        submit(2)
        if phase == "durable":
            # Executor ticks, not status loads, advance the device. There is no
            # status observation or ACK after submission in this program.
            put(f"li t3, {delay}")
            lines.append("wait_write:")
            put("addi t3, t3, -1", "bnez t3, wait_write")
        else:
            complete()
            ack()
            put("li gp, 3", f"li t0, {f.block_count}", "sd t0, 40(c9)")
            submit(3)
            complete()
    else:
        expected = bytearray(expected_image(root)[32:])
        if wrong_byte:
            expected[-1] ^= 1
        for block in range(f.block_count):
            put(f"li gp, {block + 2}", f"li t0, {block}", "sd t0, 40(c9)")
            submit(1)
            complete()
            for offset in range(0, f.block_bytes, 8):
                at = block * f.block_bytes + offset
                equal(256 + offset, int.from_bytes(expected[at:at + 8], "little"))
                # The integer load above writes t1/c6 and must clear its tag.
                put("cgettag t1, c6", "li t2, 0", "bne t1, t2, fail")
            ack()
    put("li t0, 1", "j exit")
    lines.append("fail:")
    put("slli t0, gp, 1", "ori t0, t0, 1")
    lines.append("exit:")
    put("li t1, tohost", "csetaddr c31, c8, t1", "sd t0, 0(c31)")
    lines.append("halt:")
    put("j halt", ".data", ".align 3")
    lines.append("tohost:")
    put(".dword 0")
    source = "\n".join(lines) + "\n"
    asm.Assembler(source, f"block-persistence-{phase}.s").assemble()
    return source


def read_receipt(path: Path) -> list[dict[str, object]]:
    """Require complete identities and successful persistence answers."""
    records: list[dict[str, object]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        value: object = json.loads(line)
        if not isinstance(value, dict):
            raise ValueError("block receipt record is not an object")
        records.append(cast("dict[str, object]", value))
    if (len(records) < 2 or records[0].get("event") != "open"
            or records[-1].get("event") != "close"
            or records[-1].get("healthy") is not True):
        raise ValueError("block receipt lacks a healthy open/close boundary")
    for record in (records[0], records[-1]):
        digest = record.get("sha256")
        if (not isinstance(digest, str) or len(digest) != 64
                or any(c not in "0123456789abcdef" for c in digest)):
            raise ValueError("block receipt lacks a valid image identity")
    if any(r.get("event") == "persist" and r.get("durable") is not True for r in records):
        raise ValueError("block receipt reports a persistence failure")
    return records


def run(root: Path, simulator: Path, profile: Path, output: Path,
        timeout: int = 120) -> dict[str, object]:
    """Run the actual emulator; retain every program, trace, image and receipt.

    The caller owns simulator freshness. Output must be a new lane directory,
    because neither a previous image nor a receipt is eligible as new evidence.
    """
    output.mkdir(parents=True, exist_ok=False)
    results: list[dict[str, object]] = []
    expected = expected_image(root)
    expected_digest = hashlib.sha256(expected).hexdigest()
    f = block_authority.fixture(root)
    initial = (b"VOSBLK01" + f.block_bytes.to_bytes(8, "little")
               + f.block_count.to_bytes(8, "little") + bytes(8) + f.backing)
    initial_digest = hashlib.sha256(initial).hexdigest()
    if expected == initial:
        raise ValueError("persistence payload does not distinguish the fixture")

    def execute(name: str, phase: str, image: Path | None, create: bool = False,
                negative: bool = False) -> list[dict[str, object]]:
        source, elf = output / f"{name}.s", output / f"{name}.elf"
        source.write_text(program(root, phase, wrong_byte=name == "wrong-byte"),
                          encoding="utf-8", newline="\n")
        asm.assemble_file(source, elf)
        receipt = output / f"{name}.receipt.jsonl"
        argv = [str(simulator), "--config", str(profile), "--trace-commit",
                "--inst-limit", "1000000"]
        if image is not None:
            argv += ["--blkdev-image-create" if create else "--blkdev-image",
                     str(image), "--blkdev-receipt", str(receipt)]
        argv += [str(elf)]
        started = time.monotonic()
        done = subprocess.run(argv, capture_output=True, text=True, errors="replace",
                              timeout=timeout, check=False, cwd=output)
        text = done.stdout + done.stderr
        (output / f"{name}.log").write_text(text, encoding="utf-8")
        normalized = trace.normalize_commit(text.splitlines())
        passed = done.returncode == 0 and "SUCCESS" in text and bool(normalized)
        rejected = "FAILURE:" in text and bool(normalized) and not passed
        results.append({"name": name, "argv": argv, "returncode": done.returncode,
                        "elapsed_seconds": round(time.monotonic() - started, 3),
                        "records": len(normalized), "trace_sha256": trace.digest(normalized),
                        "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                        "expected": "HTIF refusal" if negative else "HTIF success",
                        "passed": rejected if negative else passed})
        if not (rejected if negative else passed):
            raise ValueError(f"{name}: missing expected HTIF verdict and nonempty trace")
        return read_receipt(receipt) if image is not None else []

    report: dict[str, object] = {
        "schema": "verifiedos-block-persistence-1", "scope": "architectural device persistence",
        "simulator_sha256": hashlib.sha256(simulator.read_bytes()).hexdigest(),
        "profile_sha256": hashlib.sha256(profile.read_bytes()).hexdigest(),
        "inputs": receipts.inputs(root, "tools/vos/block_persistence.py",
                                   "tools/vos/block_authority.py", "tools/vos/asm.py",
                                   "model/config/verifiedos.json"),
        "initial_image_sha256": initial_digest, "expected_image_sha256": expected_digest,
        "cases": results, "passed": False,
    }
    try:
        for phase in ("durable", "flush"):
            image = output / f"{phase}.img"
            writer = execute(phase, phase, image, create=True)
            if (writer[0]["sha256"] != initial_digest or writer[-1]["sha256"] != expected_digest
                    or image.read_bytes() != expected):
                raise ValueError(f"{phase}: writer did not persist exactly the expected image")
            writes = [r for r in writer if r.get("event") == "persist" and r.get("kind") == "write"]
            flushes = [r for r in writer if r.get("event") == "persist" and r.get("kind") == "flush"]
            if len(writes) != 1 or len(flushes) != (1 if phase == "flush" else 0):
                raise ValueError(f"{phase}: receipt lacks the exact write/flush operations")
            reader = execute(phase + "-reopen", "reopen", image)
            if (reader[0]["sha256"] != writer[-1]["sha256"]
                    or reader[-1]["sha256"] != expected_digest or image.read_bytes() != expected):
                raise ValueError(f"{phase}: reopen changed or substituted the image")
        execute("wrong-byte", "reopen", output / "durable.img", negative=True)
        execute("fixture-reload", "reopen", None, negative=True)
        report["passed"] = True
    except (OSError, ValueError, subprocess.TimeoutExpired) as error:
        report["error"] = str(error)
    receipts.write(output / "results.json", report)
    return report
