# SPDX-License-Identifier: Apache-2.0
"""Generate the finite block-device architectural authority campaign (M5.3c)."""

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

from vos import asm, capcauses, config

ARTIFACT = "corpus/block-authority.s"
CONFIG = "model/config/verifiedos.json"
PERMISSIONS = "model/model/core/cap_common.sail"
OWNERS = tuple(dict.fromkeys((CONFIG, PERMISSIONS, *capcauses.OWNERS,
                              "interfaces/block-device-contract.md",
                              "tools/generated/dialect-table.json")))
# A generator resource bound, not a declaration of model capacity or admission.
MAX_CAMPAIGN_BYTES = 256


@dataclass(frozen=True)
class Fixture:
    base: int
    size: int
    block_bytes: int
    block_count: int
    backing: bytes
    poll_limit: int


def fixture(root: Path) -> Fixture:
    """Bound generation; the actual emulator owns configuration admission."""
    path = root / CONFIG
    if config.value(path, "platform", "blkdev", "supported") is not True:
        raise ValueError("block authority requires enabled device dispatch")
    values: dict[str, int] = {}
    for key in ("base", "size", "block_bytes", "block_count", "read_steps",
                "write_steps", "flush_steps"):
        value = config.integer(path, "platform", "blkdev", key)
        if value is None or value <= 0:
            raise ValueError(f"block authority requires positive {key}")
        values[key] = value
    backing = config.value(path, "platform", "blkdev", "backing")
    length, count = values["block_bytes"], values["block_count"]
    if (values["base"] % 8 or length % 8 or count < 2
            or length * count > MAX_CAMPAIGN_BYTES or values["size"] < 0x100 + length):
        raise ValueError("block authority fixture exceeds the bounded multi-block campaign")
    if not isinstance(backing, list) or len(backing) != length * count:
        raise ValueError("block authority requires exact fixture backing")
    byte_values: list[int] = []
    for byte in backing:
        if not isinstance(byte, int) or isinstance(byte, bool) or not 0 <= byte < 256:
            raise ValueError("block authority backing must contain bytes")
        byte_values.append(byte)
    raw = bytes(byte_values)
    ticks = config.integer(path, "platform", "instructions_per_tick")
    if ticks is None or ticks <= 0:
        raise ValueError("block authority requires positive instructions_per_tick")
    return Fixture(values["base"], values["size"], length, count, raw,
                   ticks * max(values[k] for k in ("read_steps", "write_steps")) + 8)


def _number(text: str, pattern: str, label: str, base: int = 10) -> int:
    values = re.findall(pattern, text, re.MULTILINE)
    if len(values) != 1:
        raise ValueError(f"block authority: cannot resolve exactly one {label}")
    return int(values[0], base)


def emit(root: Path) -> str:
    """Resolve profile owners and emit a self-checking, position-fixed program."""
    f = fixture(root)
    # Reuse the exception owner's fail-closed parser, including its packing check.
    exception = capcauses.emit(root)
    cause = _number(exception, r"CAP_EXCEPTION = (\d+);", "CHERI cause")
    width = _number(exception, r"CapExCodeWidth = (\d+);", "violation width")
    violations = {name: _number(exception, rf"CapEx_{name}\s*= \d+'b([01]+)",
                                name, 2)
                  for name in ("TagViolation", "LengthViolation", "PermitLoadViolation",
                               "PermitStoreViolation")}
    permissions = (root / PERMISSIONS).read_text(encoding="utf-8")
    permission_bits = {kind: _number(permissions,
        rf"^function cap_permit_{kind}\(cap : Capability\) -> bool = "
        r"bit_to_bool\(getCapPerms\(cap\)\[(\d+)\]\)", f"permit-{kind} bit")
                       for kind in ("load", "store")}
    lines = ["# SPDX-License-Identifier: Apache-2.0",
             "# Generated by tools/run.py block-authority emit; do not edit.",
             "# Capability refusals and device-state preservation, M5.3c."]
    for owner in OWNERS:
        # Normalize text line endings, so the same checkout on both OSes emits
        # the same fingerprint. The model owners retain their verbatim bytes.
        text = (root / owner).read_text(encoding="utf-8")
        lines.append(f"# Input {owner}: {hashlib.sha256(text.encode()).hexdigest()}")
    lines += ["        .text", "        .globl _start", "_start:",
              "        cmove c8, c1", "        la c11, handler",
              "        cspecialrw cnull, mtcc, c11", "        li s2, 0",
              f"        li t0, {f.base}", "        csetaddr c9, c8, t0",
              f"        li t0, {f.size}", "        csetbounds c9, c9, t0"]
    serial = 0
    failure_serial = 0
    expected = bytearray(f.backing)

    def put(*statements: str) -> None:
        nonlocal failure_serial
        inverses = {"bne": "beq", "bnez": "beqz", "beqz": "bnez"}
        for statement in statements:
            mnemonic = statement.split()[0]
            if mnemonic in inverses and statement.endswith(", fail"):
                failure_serial += 1
                label = f"continue_{failure_serial}"
                operands = statement.removeprefix(mnemonic).removesuffix(", fail")
                lines.extend((f"        {inverses[mnemonic]}{operands}, {label}",
                              "        j fail", label + ":"))
            else:
                lines.append("        " + statement)

    def equal(offset: int, value: int) -> None:
        put(f"ld t1, {offset}(c9)", f"li t2, {value}", "bne t1, t2, fail")

    def ack() -> None:
        put("li t0, 1", "sd t0, 56(c9)")

    def complete(command: int) -> None:
        nonlocal serial
        serial += 1
        put(f"li t0, {command}", "sd t0, 48(c9)", f"li t3, {f.poll_limit}")
        lines.append(f"poll_{serial}:")
        put("ld t1, 24(c9)", "li t2, 2", f"beq t1, t2, done_{serial}",
            "addi t3, t3, -1", f"bnez t3, poll_{serial}", "j fail")
        lines.append(f"done_{serial}:")
        equal(32, 0)

    def stage(seed: int) -> bytes:
        payload = bytes((seed + i * 17) % 256 for i in range(f.block_bytes))
        put("sd zero, 40(c9)")
        for offset in range(0, f.block_bytes, 8):
            put(f"li t0, {int.from_bytes(payload[offset:offset + 8], 'little')}",
                f"sd t0, {256 + offset}(c9)")
        return payload

    def readback() -> None:
        # Inspect every persistent byte, including all untouched blocks. Reading
        # also makes all staging bytes observable through authorized loads.
        for block in range(f.block_count):
            put(f"li t0, {block}", "sd t0, 40(c9)")
            complete(1)
            equal(40, block)
            for offset in range(0, f.block_bytes, 8):
                start = block * f.block_bytes + offset
                equal(256 + offset, int.from_bytes(expected[start:start + 8], "little"))
                put("cgettag t2, c6", "bnez t2, fail")
            ack()

    def authority(kind: str, offset: int) -> None:
        put(f"li t0, {f.base + offset}", "csetaddr c10, c9, t0")
        if kind == "untagged":
            # Integer writes clear the merged register's capability tag.
            put(f"li a0, {f.base + offset}")
        elif kind == "bounds":
            put("csetboundsimm c10, c10, 4")
        else:
            bit = permission_bits["load" if kind == "load" else "store"]
            put(f"li t0, {-1 - (1 << bit)}", "candperm c10, c10, t0")

    def refuse(kind: str, offset: int, instruction: str) -> None:
        nonlocal serial
        serial += 1
        authority(kind, offset)
        code = violations[{"untagged": "TagViolation", "bounds": "LengthViolation",
                           "load": "PermitLoadViolation", "store": "PermitStoreViolation"}[kind]]
        put(f"li t5, {cause}", f"li t6, {(10 << width) | code}",
            f"la c11, fault_{serial}", "li s2, 1")
        lines.append(f"fault_{serial}:")
        put(instruction, "bnez s2, fail")

    put("# Positive control: valid authority changes and reads the whole block.", "li gp, 1")
    equal(0, 1)
    equal(8, f.block_bytes)
    equal(16, f.block_count)
    expected[:f.block_bytes] = stage(0xA3)
    complete(2)
    ack()
    readback()
    check = 1
    for index, kind in enumerate(("untagged", "bounds", "store")):
        check += 1
        put(f"# {kind}: refused block/data stores preserve the complete preparation.",
            f"li gp, {check}")
        # First observe the medium without a successful WRITE overwriting the
        # selected block. The second trial below preserves staging for WRITE.
        stage(0x21 + index)
        put("li t2, 1")
        refuse(kind, 40, "sd t2, 0(c10)")
        put("li t2, 0x8877665544332211")
        refuse(kind, 256, "sd t2, 0(c10)")
        equal(24, 0)
        equal(32, 0)
        equal(40, 0)
        readback()
        payload = stage(0x31 + index)
        # t2 survives construction and the handler. A mistaken accepted BLOCK
        # store clears staging; a mistaken DATA store corrupts a distinguishable word.
        put("li t2, 1")
        refuse(kind, 40, "sd t2, 0(c10)")
        put("li t2, 0x8877665544332211")
        refuse(kind, 256, "sd t2, 0(c10)")
        equal(24, 0)
        equal(32, 0)
        equal(40, 0)
        complete(2)
        expected[:f.block_bytes] = payload
        ack()
        readback()

        check += 1
        put(f"# {kind}: refused command cannot publish the new staged payload.",
            f"li gp, {check}")
        stage(0xD1 + index)
        put("li t2, 2")
        refuse(kind, 48, "sd t2, 0(c10)")
        equal(24, 0)
        equal(32, 0)
        equal(40, 0)
        readback()
        # A second trial retains the preparation instead of discarding it for
        # the unchanged-medium observation. Completion must consume every old
        # staged word with its original value and bitmap membership intact.
        payload = stage(0xE1 + index)
        put("li t2, 2")
        refuse(kind, 48, "sd t2, 0(c10)")
        equal(24, 0)
        equal(32, 0)
        equal(40, 0)
        complete(2)
        expected[:f.block_bytes] = payload
        ack()
        readback()

    for kind in ("untagged", "bounds", "load"):
        check += 1
        put(f"# {kind}: refused loads preserve completed control and staging.",
            f"li gp, {check}", "sd zero, 40(c9)")
        complete(1)
        for offset in (0, 256):
            refuse(kind, offset, "ld t1, 0(c10)")
        equal(24, 2)
        equal(32, 0)
        equal(40, 0)
        for offset in range(0, f.block_bytes, 8):
            equal(256 + offset, int.from_bytes(expected[offset:offset + 8], "little"))
        ack()
        readback()

    put("li gp, 0", "j pass")
    lines += ["handler:"]
    put("beqz s2, fail", "csrr t4, mcause", "bne t4, t5, fail",
        "csrr t4, mtval", "bne t4, t6, fail", "csrr t4, mepc",
        "cgetaddr t3, c11", "bne t4, t3, fail", "addi t4, t4, 4",
        "csrw mepc, t4", "li s2, 0", "mret")
    lines += ["fail:"]
    put("slli t0, gp, 1", "ori t0, t0, 1", "j exit")
    lines += ["pass:"]
    put("li t0, 1")
    lines += ["exit:"]
    put("li t1, tohost", "csetaddr c31, c8, t1", "sd t0, 0(c31)")
    lines += ["halt:"]
    put("j halt", ".data", ".align 3")
    lines += ["tohost:"]
    put(".dword 0")
    output = "\n".join(lines) + "\n"
    # Use the existing assembler/profile encoder, and refuse a fixture whose
    # unrolled campaign cannot fit the corpus's fixed image layout.
    asm.Assembler(output, ARTIFACT).assemble()
    return output


def check(root: Path) -> list[str]:
    wanted = emit(root)
    path = root / ARTIFACT
    if not path.is_file() or path.read_text(encoding="utf-8") != wanted:
        return [f"{ARTIFACT}: regenerate with tools/run.py block-authority emit"]
    return []
