# SPDX-License-Identifier: Apache-2.0
"""M3.5b's target chain campaign: its cases, its host oracle, its staged inputs and its join.

[The boot-handoff contract](../../docs/implementation/contracts/boot-handoff.md)'s section
9 is the predicate this module serves. It owns four things, each host Python that needs
neither the contained compiler nor the emulator:

1. **The case realization.** `CASES` states how each row of section 9.12's case table is
   realized, and `require_cases` holds the set against `boot_handoff.chain_cases`, the
   table's own parse, so a row the table gains or loses refuses every run.
2. **The host oracle** of section 9.2: from a case's inputs it computes, over `hashlib`'s
   SHAKE256 and independently of the firmware C, every byte that crosses a run boundary
   and every verdict, by sections 9.5 to 9.8: the state records, the capture head's
   compared fields, the handoff record, the placed M-mode window, the item-6 request and
   response, the M-mode capture and the main-die exit codes. A signature verdict is the
   one fact it does not compute: it is the campaign's disposable OpenSSL keys' verdict,
   recorded per exact (key, prefix, signature) at staging and looked up here.
3. **The staged inputs** (section 9.14): `staged` holds `firmware/chain/target/` to its
   manifest, to this checkout's sources and to section 9.13's identity freeze with
   M7.1f's staged manifest, as `boot_crypto_target.staged` holds the signature streams.
4. **The join** of shard receipts into one campaign receipt (F-718's identities).

Every constant is read from `firmware/chain/vos_chain.h` and `vos_boot.h` through
`boot_handoff.chain_layout`; the composition facts the oracle needs beside them (the
lifecycle state, the entropy root's source count, the watchdog's bounds) are read from
the shipped RoT configuration. Staging and execution live in `boot_chain_target`.

**What the contract leaves silent the oracle names rather than guesses.** Section 9.11
compares a refusal's capture head byte for byte but does not say whether a refusal
writes a digest, version or length it computed before refusing. For those fields alone
the comparison admits zero or the value the check reached and records which it saw
(`SILENT`); every other byte, gaps included, is compared exactly or, for the watchdog's
clock-dependent fields, by section 9.11's predicates.
"""

import hashlib
import json
from collections.abc import Callable, Mapping
from dataclasses import asdict, dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, cast

from vos import boot_crypto_target, config, jsonc, receipts
from vos import boot_handoff as bh
from vos.cli import compiler_diff as cd

STAGED = "firmware/chain/target"
MANIFEST = f"{STAGED}/manifest.json"
IMAGES = f"{STAGED}/images.json"
GENERATOR = "run.py boot-handoff chain-stage"
HEADER = ("# SPDX-License-Identifier: Apache-2.0\n"
          f"# Generated by {GENERATOR} from the target chain's C.\n"
          "# The contained compiler's stream follows byte for byte; manifest.json binds it.\n")
# The compiled units, each one staged stream. The two runtime mutants are section 9.10's
# text substitutions of the runtime source, named by the RoT lane's RUNTIME_MUTANTS keys.
UNITS = ("rom", "runtime", "runtime-stall", "runtime-early-pet", "mmode")
MUTANTS = {"runtime-stall": "stall", "runtime-early-pet": "early-pet"}
# The signed images section 9.12 names: stage 0, the three stage-1 slots, slot A's
# below-floor variant and the stage-2 kernel image.
IMAGE_NAMES = ("stage0", "mmode-a", "mmode-b", "mmode-recovery", "mmode-a-below-floor", "kernel")
STAGED_FILES = ("manifest.json", "images.json", *(f"{unit}.s" for unit in UNITS))
# Absence of the whole staged directory is admitted until the integrator first stages
# it; the commit that stages sets this, after which absence is K-88's finding.
STAGED_REQUIRED = False
# F: the floor the ROM establishes by advancing counter 0 in the same power-on, and the
# security version every image is signed at (section 9.12). The campaign's choice.
FLOOR = 2
# Where a case flips one byte: inside a signature, inside a payload, and inside the
# kernel digest a nonbinding item-6 response is computed for. Staging verifies the
# flipped signatures with OpenSSL, so the oracle's refusals rest on that verdict too.
SIGNATURE_FLIP_AT = 100
PAYLOAD_FLIP_AT = 0
DIGEST_FLIP_AT = 0
# Section 9.13's freeze: the six sources whose digests must equal M7.1f's manifest's.
FROZEN = ("firmware/crypto/keccak.c", "firmware/crypto/slh256s.c", "firmware/crypto/mldsa87.c",
          "firmware/include/vos_boot.h", "firmware/include/vos_keccak.h",
          "firmware/include/vos_signature.h")
REQUIRED_ARGUMENTS = ("-fverifiedos-typed", "-Ifirmware/include")
SOURCE_INPUTS = ("firmware", "tools/vos", "tools/generated/dialect-table.json")
# The configuration's lifecycle names, in rot.sail's lifecycle_to_index order, which is
# boot_handoff.LIFECYCLES's.
LIFECYCLE_STATES = ("Lifecycle_Raw", "Lifecycle_Test", "Lifecycle_Development",
                    "Lifecycle_Production", "Lifecycle_RMA")
SLH, MLDSA = "slh-internal", "mldsa-internal"


# --- the case realization -----------------------------------------------------------


@dataclass(frozen=True)
class Spec:
    """How one row of section 9.12's case table is realized.

    `run` is the table's run kind. A joined case's inputs are the boot-control values at
    power-on, the lifecycle state (None for the shipped one), the injected entropy
    failure, and which store image is altered and how; a main-die case alters the
    stage-2 image or the item-6 response over `cold-boot`'s R1 and R2; a runtime-only
    case names its runtime mutant and whether the external clock runs.
    """

    name: str
    run: str
    boot_target: int = 0
    slot: int = 0
    at_bound: bool = False
    lifecycle: str | None = None
    entropy_failed: bool = False
    stage0: str = "valid"
    slot_a: str = "valid"
    kernel: str = "valid"
    response: str = "bound"
    mutant: str | None = None
    clock: bool = True

    def ending(self) -> str:
        """A runtime-only case's required ending."""
        if self.mutant == "early-pet":
            return "bite-early"
        return "bite-late" if self.clock else "limit"

    def inputs(self) -> dict[str, object]:
        return {key: value for key, value in asdict(self).items() if key != "name"}


CASES: tuple[Spec, ...] = (
    Spec("cold-boot", "joined"),
    Spec("recovery-latched", "joined", boot_target=1),
    Spec("revert-past-bound", "joined", at_bound=True),
    Spec("entropy-halt", "joined", entropy_failed=True),
    Spec("lifecycle-raw", "joined", lifecycle="raw"),
    Spec("runtime-signature-corrupt", "joined", stage0="signature-flipped"),
    Spec("runtime-digest-mismatch", "joined", stage0="payload-flipped"),
    Spec("mmode-below-floor", "joined", slot_a="below-floor"),
    Spec("mmode-signature-corrupt", "joined", slot_a="signature-flipped"),
    Spec("kernel-signature-corrupt", "main-die", kernel="signature-flipped"),
    Spec("kernel-digest-mismatch", "main-die", kernel="payload-flipped"),
    Spec("item6-response-nonbinding", "main-die", response="nonbinding"),
    Spec("watchdog-stalled-step", "runtime-only", mutant="stall"),
    Spec("watchdog-early-pet", "runtime-only", mutant="early-pet"),
    Spec("watchdog-stalled-no-clock", "runtime-only", mutant="stall", clock=False),
)
SPECS = {spec.name: spec for spec in CASES}
GROUPS = {"main-die": tuple(spec.name for spec in CASES if spec.run == "main-die"),
          "watchdog": tuple(spec.name for spec in CASES if spec.run == "runtime-only")}
COLD_BOOT = "cold-boot"


def require_cases(root: Path) -> list[bh.ChainCase]:
    """Section 9.12's rows, which must be exactly the cases realized here."""
    rows = bh.chain_cases(root)
    names = [row.name for row in rows]
    if len(set(names)) != len(names) or set(names) != set(SPECS):
        raise ValueError(f"{bh.CONTRACT}'s chain case table names {sorted(set(names) ^ set(SPECS))} "
                         "unlike the campaign's realized cases")
    for row in rows:
        if row.run != SPECS[row.name].run:
            raise ValueError(f"{bh.CONTRACT}: {row.name} runs as {row.run}, realized as "
                             f"{SPECS[row.name].run}")
    return rows


# --- the composition facts ----------------------------------------------------------


@dataclass(frozen=True)
class Facts:
    """What the oracle reads from the owners: the layout, the verdict codes, the
    measurement domains and slot tags, and the shipped RoT composition's inputs."""

    lay: bh.Layout
    codes: dict[str, int]
    extend_domain: bytes
    chain_domain: bytes
    tags: tuple[bytes, bytes, bytes]
    lifecycle: int
    health: int
    early: int
    late: int
    floor: int

    def __getitem__(self, name: str) -> int:
        return self.lay[name]


def _walk(data: object, *keys: str) -> object:
    for key in keys:
        if not isinstance(data, dict) or key not in data:
            raise ValueError(f"the configuration declares no {'.'.join(keys)}")
        data = cast("dict[str, object]", data)[key]
    return data


def _integer(data: object, *keys: str) -> int:
    found = _walk(data, *keys)
    if not isinstance(found, int) or isinstance(found, bool):
        raise TypeError(f"the configuration's {'.'.join(keys)} is not an integer")
    return found


def facts(root: Path, floor: int = FLOOR) -> Facts:
    lay = bh.chain_layout(root)
    domains = bh.string_constants(root)
    chain_strings = bh.string_constants(root, bh.CHAIN_HEADER)
    shipped = jsonc.load(root / bh.ROT_CONFIG)
    state = _walk(shipped, "platform", "otp", "lifecycle_state")
    if state not in LIFECYCLE_STATES:
        raise ValueError(f"{bh.ROT_CONFIG}'s lifecycle state {state!r} is not one rot.sail names")
    sources = _integer(shipped, "platform", "trng", "noise_sources")
    if not 1 <= sources <= 32:
        raise ValueError(f"{bh.ROT_CONFIG} declares {sources} noise sources")
    # platform.sail's health door: one started bit per source, then the completion bit
    # 32 and the fail-stop bit 33 that section 9.5's verdict reads.
    health = ((1 << sources) - 1) | (1 << 32)
    tags = tuple(chain_strings[name].encode("ascii") for name in (
        "VOS_CHAIN_SLOT_TAG_A", "VOS_CHAIN_SLOT_TAG_B", "VOS_CHAIN_SLOT_TAG_RECOVERY"))
    if floor < 1:
        raise ValueError("the floor must be at least one counter advance")
    return Facts(lay, bh.verdict_codes(root), domains["VOS_MEASURE_EXTEND_DOMAIN"].encode(),
                 domains["VOS_MEASURE_CHAIN_DOMAIN"].encode(), (tags[0], tags[1], tags[2]),
                 LIFECYCLE_STATES.index(cast("str", state)), health,
                 _integer(shipped, "platform", "watchdog", "early_ticks"),
                 _integer(shipped, "platform", "watchdog", "late_ticks"), floor)


# --- section 5's encoding and the records ---------------------------------------------


def _word(data: bytes, at: int) -> int:
    return int.from_bytes(data[at:at + 8], "little")


def _put(buffer: bytearray, at: int, value: int | bytes) -> None:
    blob = value.to_bytes(8, "little") if isinstance(value, int) else value
    buffer[at:at + len(blob)] = blob


@dataclass(frozen=True)
class Measured:
    """The two registers and the log, extended by section 5's encoding."""

    generation: bytes
    device: bytes
    log: tuple[int, ...] = ()

    @staticmethod
    def reset(f: Facts) -> Measured:
        return Measured(bytes(f["MEASURE_BYTES"]), bytes(f["MEASURE_BYTES"]))

    def extend(self, f: Facts, code: int, data: bytes) -> Measured:
        if len(self.log) >= f["MEASURE_LOG_CAPACITY"]:
            raise ValueError("the oracle's log cannot record another item")
        to_generation = code >= f["ITEM_STAGE_ROT_RUNTIME"]
        register = self.generation if to_generation else self.device
        value = hashlib.shake_256(f.extend_domain + register + bytes([code])
                                  + len(data).to_bytes(4, "little") + data).digest(f["MEASURE_BYTES"])
        return Measured(value if to_generation else self.generation,
                        self.device if to_generation else value, (*self.log, code))

    def chain(self, f: Facts) -> bytes:
        return hashlib.shake_256(f.chain_domain + self.generation + self.device).digest(
            f["MEASURE_BYTES"])

    def log_bytes(self, f: Facts) -> bytes:
        return bytes(self.log).ljust(f["CHAIN_STATE_LOG_BYTES"], b"\0")


def shake(f: Facts, data: bytes) -> bytes:
    return hashlib.shake_256(data).digest(f["BOOT_DIGEST_BYTES"])


def device_prologue(f: Facts, lifecycle: int, entropy_ok: int, boot_target: int) -> Measured:
    """Items 1 to 3, each one byte, as boot_verify.c extends them."""
    return (Measured.reset(f).extend(f, f["ITEM_LIFECYCLE"], bytes([lifecycle]))
            .extend(f, f["ITEM_ENTROPY_VERDICT"], bytes([entropy_ok]))
            .extend(f, f["ITEM_BOOT_TARGET"], bytes([boot_target & 1])))


@dataclass(frozen=True)
class State:
    """A state record's fields (section 9.5)."""

    run_kind: int
    lifecycle: int
    entropy_ok: int
    boot_target: int
    floor: int
    measured: Measured


def state_record(f: Facts, state: State) -> bytes:
    record = bytearray(f["CHAIN_STATE_BYTES"])
    for macro, value in (("CHAIN_STATE_MAGIC_AT", f["CHAIN_STATE_MAGIC"]),
                         ("CHAIN_STATE_VERSION_AT", f["CHAIN_STATE_VERSION"]),
                         ("CHAIN_STATE_RUN_KIND_AT", state.run_kind),
                         ("CHAIN_STATE_LIFECYCLE_AT", state.lifecycle),
                         ("CHAIN_STATE_ENTROPY_AT", state.entropy_ok),
                         ("CHAIN_STATE_BOOT_TARGET_AT", state.boot_target),
                         ("CHAIN_STATE_FLOOR_AT", state.floor),
                         ("CHAIN_STATE_MEASURE_COUNT_AT", len(state.measured.log))):
        _put(record, f[macro], value)
    _put(record, f["CHAIN_STATE_LOG_AT"], state.measured.log_bytes(f))
    _put(record, f["CHAIN_STATE_GENERATION_AT"], state.measured.generation)
    _put(record, f["CHAIN_STATE_DEVICE_AT"], state.measured.device)
    return bytes(record)


def parse_state(f: Facts, record: bytes) -> State | None:
    """The record's fields, or None where its magic or version is not section 9.5's."""
    if (len(record) < f["CHAIN_STATE_BYTES"]
            or _word(record, f["CHAIN_STATE_MAGIC_AT"]) != f["CHAIN_STATE_MAGIC"]
            or _word(record, f["CHAIN_STATE_VERSION_AT"]) != f["CHAIN_STATE_VERSION"]):
        return None
    count = _word(record, f["CHAIN_STATE_MEASURE_COUNT_AT"])
    if count > f["CHAIN_STATE_LOG_BYTES"]:
        return None
    width = f["MEASURE_BYTES"]
    log_at, generation_at = f["CHAIN_STATE_LOG_AT"], f["CHAIN_STATE_GENERATION_AT"]
    device_at = f["CHAIN_STATE_DEVICE_AT"]
    measured = Measured(record[generation_at:generation_at + width],
                        record[device_at:device_at + width],
                        tuple(record[log_at:log_at + count]))
    return State(_word(record, f["CHAIN_STATE_RUN_KIND_AT"]),
                 _word(record, f["CHAIN_STATE_LIFECYCLE_AT"]),
                 _word(record, f["CHAIN_STATE_ENTROPY_AT"]),
                 _word(record, f["CHAIN_STATE_BOOT_TARGET_AT"]),
                 _word(record, f["CHAIN_STATE_FLOOR_AT"]), measured)


def as_service(f: Facts, record: bytes) -> bytes:
    """A boot run's state record carried into a service run (section 9.11's R2)."""
    out = bytearray(record)
    _put(out, f["CHAIN_STATE_RUN_KIND_AT"], f["CHAIN_RUN_SERVICE"])
    return bytes(out)


def handoff_record(f: Facts, state: State, version: int, length: int, digest: bytes,
                   measured: Measured) -> bytes:
    """Section 6's record at version 1 with section 9.9's chain values."""
    record = bytearray(f["HANDOFF_BYTES"])
    for macro, value in (("HANDOFF_MAGIC_AT", f["HANDOFF_MAGIC"]),
                         ("HANDOFF_VERSION_AT", f["HANDOFF_VERSION"]),
                         ("HANDOFF_LIFECYCLE_AT", state.lifecycle),
                         ("HANDOFF_ENTROPY_AT", state.entropy_ok),
                         ("HANDOFF_BOOT_TARGET_AT", state.boot_target),
                         ("HANDOFF_SECURITY_VERSION_AT", version),
                         ("HANDOFF_FLOOR_AT", state.floor),
                         ("HANDOFF_LOAD_BASE_AT", f["CHAIN_MMODE_LOAD_BASE"]),
                         ("HANDOFF_PAYLOAD_LENGTH_AT", length)):
        _put(record, f[macro], value)
    _put(record, f["HANDOFF_IMAGE_DIGEST_AT"], digest)
    _put(record, f["HANDOFF_GENERATION_AT"], measured.generation)
    _put(record, f["HANDOFF_DEVICE_AT"], measured.device)
    _put(record, f["HANDOFF_CHAIN_AT"], measured.chain(f))
    return bytes(record)


def item6_request(f: Facts, digest: bytes) -> bytes:
    request = bytearray(f["CHAIN_REQUEST_BYTES"])
    _put(request, f["CHAIN_REQUEST_MAGIC_AT"], f["CHAIN_REQUEST_MAGIC"])
    _put(request, f["CHAIN_REQUEST_STAGE_AT"], f["BOOT_STAGE_CORE_KERNELS"])
    _put(request, f["CHAIN_REQUEST_DIGEST_AT"], digest)
    return bytes(request)


def item6_response(f: Facts, digest: bytes, measured: Measured) -> bytes:
    """The response a service run writes, `measured` being the registers after item 6."""
    response = bytearray(f["CHAIN_RESPONSE_BYTES"])
    _put(response, f["CHAIN_RESPONSE_MAGIC_AT"], f["CHAIN_RESPONSE_MAGIC"])
    _put(response, f["CHAIN_RESPONSE_STAGE_AT"], f["BOOT_STAGE_CORE_KERNELS"])
    _put(response, f["CHAIN_RESPONSE_DIGEST_AT"], digest)
    _put(response, f["CHAIN_RESPONSE_GENERATION_AT"], measured.generation)
    _put(response, f["CHAIN_RESPONSE_DEVICE_AT"], measured.device)
    _put(response, f["CHAIN_RESPONSE_CHAIN_AT"], measured.chain(f))
    _put(response, f["CHAIN_RESPONSE_MEASURE_COUNT_AT"], len(measured.log))
    _put(response, f["CHAIN_RESPONSE_LOG_AT"], measured.log_bytes(f))
    return bytes(response)


# --- the images and their checks ----------------------------------------------------


def build_image(f: Facts, payload: bytes, *, stage: int, version: int, signer: bytes,
                sign: Callable[[bytes, bytes], bytes]) -> bytes:
    """Section 4's header for stages 0 and 1, or section 9.3's for stage 2."""
    kernel = stage == f["BOOT_STAGE_CORE_KERNELS"]
    size = f["CHAIN_KSTAGE_HEADER_BYTES"] if kernel else f["BOOT_HEADER_BYTES"]
    header = bytearray(size)
    for macro, value in (("BOOT_HDR_MAGIC", f["CHAIN_KSTAGE_MAGIC"] if kernel else f["BOOT_MAGIC"]),
                         ("BOOT_HDR_STAGE", stage), ("BOOT_HDR_SECURITY_VERSION", version),
                         ("BOOT_HDR_PAYLOAD_OFFSET", size),
                         ("BOOT_HDR_PAYLOAD_LENGTH", len(payload))):
        _put(header, f[macro], value)
    _put(header, f["BOOT_HDR_PAYLOAD_DIGEST"], shake(f, payload))
    signature = sign(signer, bytes(header[:f["BOOT_SIGNED_BYTES"]]))
    if len(signature) != size - f["BOOT_HDR_SIGNATURE"]:
        raise ValueError("the signer returned a signature of the wrong length")
    _put(header, f["BOOT_HDR_SIGNATURE"], signature)
    return bytes(header) + payload


def flip(data: bytes, at: int) -> bytes:
    return bh.flip(data, at)


@dataclass(frozen=True)
class Checked:
    """One image's checks in section 3's order: the verdict, and what was reached."""

    verdict: str
    version: int | None = None
    length: int | None = None
    payload: bytes | None = None
    digest: bytes | None = None


type Verify = Callable[[str, bytes, bytes, bytes], bool]


def check_image(f: Facts, image: bytes, *, stage: int, region: int, floor: int,
                root_key: bytes | None, verify: Verify) -> Checked:
    """ReadHeader, CheckFloor, VerifySignature, placement and Measure, stopping at the
    first refusal. The stage decides the header: section 4's, or section 9.3's for 2."""
    kernel = stage == f["BOOT_STAGE_CORE_KERNELS"]
    size = f["CHAIN_KSTAGE_HEADER_BYTES"] if kernel else f["BOOT_HEADER_BYTES"]
    if len(image) < size:
        return Checked("refuse-truncated")
    prefix = image[:f["BOOT_SIGNED_BYTES"]]
    if _word(prefix, f["BOOT_HDR_MAGIC"]) != (f["CHAIN_KSTAGE_MAGIC"] if kernel else f["BOOT_MAGIC"]):
        return Checked("refuse-magic")
    if _word(prefix, f["BOOT_HDR_STAGE"]) != stage:
        return Checked("refuse-stage")
    if _word(prefix, f["BOOT_HDR_PAYLOAD_OFFSET"]) != size:
        return Checked("refuse-offset")
    length = _word(prefix, f["BOOT_HDR_PAYLOAD_LENGTH"])
    if length == 0 or length > region:
        return Checked("refuse-length")
    if len(image) - size < length:
        return Checked("refuse-truncated")
    version = _word(prefix, f["BOOT_HDR_SECURITY_VERSION"])
    if version < floor:
        return Checked("refuse-floor", version, length)
    if root_key is None or not verify(MLDSA if kernel else SLH, root_key, prefix,
                                      image[f["BOOT_HDR_SIGNATURE"]:size]):
        return Checked("refuse-signature", version, length)
    payload = image[size:size + length]
    digest = shake(f, payload)
    at = f["BOOT_HDR_PAYLOAD_DIGEST"]
    if digest != prefix[at:at + f["BOOT_DIGEST_BYTES"]]:
        return Checked("refuse-digest", version, length, None, digest)
    return Checked("release", version, length, payload, digest)


def verdict_key(scheme: str, public: bytes, prefix: bytes, signature: bytes) -> str:
    return "/".join([scheme, *(hashlib.sha256(part).hexdigest() for part in (public, prefix, signature))])


def recorded_verify(manifest: Mapping[str, Any]) -> Verify:
    """The OpenSSL verdicts staging recorded, as the oracle's signature decision. A
    triple staging never verified has no verdict here, and the oracle refuses it."""
    recorded: dict[str, bool] = {}
    for entry in manifest.get("signature_verdicts", []):
        recorded[str(entry["key"])] = entry["accepted"] is True

    def verify(scheme: str, public: bytes, prefix: bytes, signature: bytes) -> bool:
        key = verdict_key(scheme, public, prefix, signature)
        if key not in recorded:
            raise ValueError(f"staging recorded no OpenSSL verdict for {key}")
        return recorded[key]
    return verify


# --- the oracle: sections 9.5 to 9.8 ------------------------------------------------


@dataclass(frozen=True)
class RomOutcome:
    verdict: str
    measured: Measured
    state: bytes                  # the record the ROM leaves; zero after a refusal
    checked: Checked | None       # stage 0's checks, where the ROM reached ReadHeader


def rom(f: Facts, *, lifecycle: int, entropy_ok: int, boot_target: int, stage0: bytes,
        roots: Mapping[int, bytes], verify: Verify) -> RomOutcome:
    """Section 9.5: items 1 to 3, the entropy and root refusals, stage 0's checks, item 4."""
    measured = device_prologue(f, lifecycle, entropy_ok, boot_target)
    empty = bytes(f["CHAIN_STATE_BYTES"])
    if not entropy_ok:
        return RomOutcome("refuse-entropy", measured, empty, None)
    if lifecycle not in roots:
        return RomOutcome("refuse-no-root", measured, empty, None)
    checked = check_image(f, stage0, stage=f["BOOT_STAGE_ROT_RUNTIME"],
                          region=f["CHAIN_ROT_RUNTIME_REGION_BYTES"], floor=f.floor,
                          root_key=roots[lifecycle], verify=verify)
    if checked.verdict != "release" or checked.digest is None:
        return RomOutcome(checked.verdict, measured, empty, checked)
    measured = measured.extend(f, f["ITEM_STAGE_ROT_RUNTIME"], checked.digest)
    state = State(f["CHAIN_RUN_BOOT"], lifecycle, entropy_ok, boot_target & 1, f.floor, measured)
    return RomOutcome("release", measured, state_record(f, state), checked)


@dataclass(frozen=True)
class Selection:
    selected: int    # the slot code verified
    slot: int        # the slot door after the runtime's writes
    attempts: int    # the attempt door after them
    charged: bool
    reverted: bool


def select(f: Facts, boot_target: int, slot: int, attempts: int) -> Selection:
    """Section 9.6's selection and counting, RotFirmware.v's spec_revert and spec_charge."""
    if boot_target & 1:
        return Selection(f["CHAIN_SLOT_RECOVERY"], slot, attempts, False, False)
    reverted = attempts >= f["CHAIN_BOOT_ATTEMPT_BOUND"]
    if reverted:
        slot = f["CHAIN_SLOT_B"] if slot == f["CHAIN_SLOT_A"] else f["CHAIN_SLOT_A"]
        attempts = 0
    return Selection(slot, slot, attempts + 1, True, reverted)


@dataclass(frozen=True)
class RuntimeOutcome:
    verdict: str
    selection: Selection | None
    measured: Measured
    state: bytes        # the state record as the run leaves it
    record: bytes       # the handoff record; zero unless released
    window: bytes       # the placed M-mode window; zero unless released
    checked: Checked | None


def runtime(f: Facts, state: bytes, *, boot_target: int, slot: int, attempts: int,
            stores: Mapping[int, bytes], roots: Mapping[int, bytes],
            verify: Verify) -> RuntimeOutcome:
    """Section 9.6: the state check, selection and charge, stage 1's checks, item 5, the
    record and the window."""
    zero_record, zero_window = bytes(f["HANDOFF_BYTES"]), bytes(f["CHAIN_MMODE_REGION_BYTES"])
    parsed = parse_state(f, state)
    if parsed is None or parsed.run_kind != f["CHAIN_RUN_BOOT"]:
        measured = parsed.measured if parsed is not None else Measured.reset(f)
        return RuntimeOutcome("refuse-state", None, measured, state, zero_record, zero_window, None)
    chosen = select(f, boot_target, slot, attempts)
    checked = check_image(f, stores[chosen.selected], stage=f["BOOT_STAGE_MMODE_IMAGE"],
                          region=f["CHAIN_MMODE_REGION_BYTES"], floor=parsed.floor,
                          root_key=roots.get(parsed.lifecycle), verify=verify)
    if (checked.verdict != "release" or checked.payload is None or checked.digest is None
            or checked.version is None or checked.length is None):
        return RuntimeOutcome(checked.verdict, chosen, parsed.measured, state, zero_record,
                              zero_window, checked)
    measured = parsed.measured.extend(f, f["ITEM_STAGE_MMODE_IMAGE"], checked.digest)
    after = State(parsed.run_kind, parsed.lifecycle, parsed.entropy_ok, parsed.boot_target,
                  parsed.floor, measured)
    record = handoff_record(f, after, checked.version, checked.length, checked.digest, measured)
    window = checked.payload + bytes(f["CHAIN_MMODE_REGION_BYTES"] - len(checked.payload))
    return RuntimeOutcome("release", chosen, measured, state_record(f, after), record, window,
                          checked)


@dataclass(frozen=True)
class ServiceOutcome:
    verdict: str
    response: bytes
    state: bytes


def service(f: Facts, state: bytes, request: bytes) -> ServiceOutcome:
    """Section 9.7's item-6 service: the state and request checks, item 6, the response."""
    zero = bytes(f["CHAIN_RESPONSE_BYTES"])
    parsed = parse_state(f, state)
    if parsed is None or parsed.run_kind != f["CHAIN_RUN_SERVICE"]:
        return ServiceOutcome("refuse-state", zero, state)
    if (_word(request, f["CHAIN_REQUEST_MAGIC_AT"]) != f["CHAIN_REQUEST_MAGIC"]
            or _word(request, f["CHAIN_REQUEST_STAGE_AT"]) != f["BOOT_STAGE_CORE_KERNELS"]
            or len(parsed.measured.log) >= f["MEASURE_LOG_CAPACITY"]):
        return ServiceOutcome("refuse-request", zero, state)
    at = f["CHAIN_REQUEST_DIGEST_AT"]
    digest = request[at:at + f["BOOT_DIGEST_BYTES"]]
    measured = parsed.measured.extend(f, f["ITEM_STAGE_CORE_KERNELS"], digest)
    after = State(parsed.run_kind, parsed.lifecycle, parsed.entropy_ok, parsed.boot_target,
                  parsed.floor, measured)
    return ServiceOutcome("release", item6_response(f, digest, measured), state_record(f, after))


def nonbinding_response(f: Facts, state: bytes, digest: bytes) -> bytes:
    """Section 9.12's self-consistent response for a digest one byte off, over the state
    a service run starts from: its registers and chain are its own, so only the echo and
    the generation recomputation can refuse it."""
    parsed = parse_state(f, state)
    if parsed is None:
        raise ValueError("a nonbinding response needs a well-formed service state")
    other = flip(digest, DIGEST_FLIP_AT)
    return item6_response(f, other, parsed.measured.extend(f, f["ITEM_STAGE_CORE_KERNELS"], other))


@dataclass(frozen=True)
class MmodeOutcome:
    verdict: str
    exit_code: int        # the HTIF exit: 0, or the exit base plus the refusal code
    request: bytes        # the request slot after the run; zero where nothing was written
    checked: Checked | None
    bound: bool


def binds(f: Facts, record: bytes, response: bytes, digest: bytes) -> bool:
    """Section 9.7's binding check over the record and the stage's own digest."""
    width = f["MEASURE_BYTES"]

    def blob(at: str) -> bytes:
        return response[f[at]:f[at] + width]
    generation_at, device_at = f["HANDOFF_GENERATION_AT"], f["HANDOFF_DEVICE_AT"]
    base = Measured(record[generation_at:generation_at + width],
                    record[device_at:device_at + width])
    expected = base.extend(f, f["ITEM_STAGE_CORE_KERNELS"], digest)
    return (_word(response, f["CHAIN_RESPONSE_MAGIC_AT"]) == f["CHAIN_RESPONSE_MAGIC"]
            and _word(response, f["CHAIN_RESPONSE_STAGE_AT"]) == f["BOOT_STAGE_CORE_KERNELS"]
            and response[f["CHAIN_RESPONSE_DIGEST_AT"]:f["CHAIN_RESPONSE_DIGEST_AT"]
                         + f["BOOT_DIGEST_BYTES"]] == digest
            and blob("CHAIN_RESPONSE_GENERATION_AT") == expected.generation
            and blob("CHAIN_RESPONSE_DEVICE_AT") == base.device
            and blob("CHAIN_RESPONSE_CHAIN_AT") == expected.chain(f))


def mmode(f: Facts, record: bytes, kernel_root: bytes, kernel_image: bytes, response: bytes,
          verify: Verify) -> MmodeOutcome:
    """Section 9.8's steps 1 to 6."""
    zero = bytes(f["CHAIN_REQUEST_BYTES"])

    def refused(verdict: str, checked: Checked | None, request: bytes = zero) -> MmodeOutcome:
        return MmodeOutcome(verdict, f["CHAIN_MMODE_EXIT_BASE"] + f.codes[verdict], request,
                            checked, False)
    if (_word(record, f["HANDOFF_MAGIC_AT"]) != f["HANDOFF_MAGIC"]
            or _word(record, f["HANDOFF_VERSION_AT"]) != f["HANDOFF_VERSION"]):
        return refused("refuse-record", None)
    checked = check_image(f, kernel_image, stage=f["BOOT_STAGE_CORE_KERNELS"],
                          region=f["CHAIN_KERNEL_REGION_BYTES"],
                          floor=_word(record, f["HANDOFF_FLOOR_AT"]), root_key=kernel_root,
                          verify=verify)
    if checked.verdict != "release" or checked.digest is None:
        return refused(checked.verdict, checked)
    request = item6_request(f, checked.digest)
    if not binds(f, record, response, checked.digest):
        return refused("refuse-response", checked, request)
    return MmodeOutcome("release", 0, request, checked, True)


# --- what each case expects ----------------------------------------------------------


@dataclass(frozen=True)
class Inputs:
    """The staged inputs every oracle run reads: the images, the keys and the verdicts."""

    images: Mapping[str, bytes]
    roots: Mapping[int, bytes]
    kernel_root: bytes
    verify: Verify


def store_images(f: Facts, spec: Spec, inputs: Inputs) -> tuple[bytes, dict[int, bytes]]:
    """A case's stage-0 store window and its three stage-1 store windows."""
    stage0 = inputs.images["stage0"]
    header = f["BOOT_HEADER_BYTES"]
    if spec.stage0 == "signature-flipped":
        stage0 = flip(stage0, f["BOOT_HDR_SIGNATURE"] + SIGNATURE_FLIP_AT)
    elif spec.stage0 == "payload-flipped":
        stage0 = flip(stage0, header + PAYLOAD_FLIP_AT)
    slot_a = {"valid": inputs.images["mmode-a"],
              "below-floor": inputs.images["mmode-a-below-floor"],
              "signature-flipped": flip(inputs.images["mmode-a"],
                                        f["BOOT_HDR_SIGNATURE"] + SIGNATURE_FLIP_AT)}[spec.slot_a]
    return stage0, {f["CHAIN_SLOT_A"]: slot_a, f["CHAIN_SLOT_B"]: inputs.images["mmode-b"],
                    f["CHAIN_SLOT_RECOVERY"]: inputs.images["mmode-recovery"]}


def kernel_image(f: Facts, spec: Spec, inputs: Inputs) -> bytes:
    image = inputs.images["kernel"]
    if spec.kernel == "signature-flipped":
        return flip(image, f["BOOT_HDR_SIGNATURE"] + SIGNATURE_FLIP_AT)
    if spec.kernel == "payload-flipped":
        # Never inside the kernel data extent's first word: that is the HTIF word, and
        # the M-mode stage places by doublewords, so a nonzero word there would issue an
        # HTIF command during placement rather than reach the digest comparison.
        if f["CHAIN_KERNEL_DATA_AT"] <= PAYLOAD_FLIP_AT < f["CHAIN_KERNEL_DATA_AT"] + 8:
            raise ValueError("the kernel payload flip would land in tohost")
        return flip(image, f["CHAIN_KSTAGE_HEADER_BYTES"] + PAYLOAD_FLIP_AT)
    return image


@dataclass(frozen=True)
class Plan:
    """The oracle's whole expectation for one joined or main-die case."""

    spec: Spec
    lifecycle: int
    entropy_ok: int
    attempts: int
    stage0: bytes
    stores: dict[int, bytes]
    rom: RomOutcome
    runtime: RuntimeOutcome | None
    request: bytes | None = None
    service: ServiceOutcome | None = None
    service_state: bytes | None = None
    kernel_image: bytes | None = None
    response: bytes | None = None
    mmode: MmodeOutcome | None = None

    @property
    def released(self) -> bool:
        return self.runtime is not None and self.runtime.verdict == "release"

    @property
    def verdict(self) -> str:
        return self.runtime.verdict if self.runtime is not None else self.rom.verdict


def plan(f: Facts, spec: Spec, inputs: Inputs) -> Plan:
    """Run the oracle over a case: R1's ROM and runtime, then on a release R2's service
    and R3's M-mode stage. A main-die case is `cold-boot`'s R1 and R2 with its own
    stage-2 image or response."""
    if spec.run == "runtime-only":
        raise ValueError(f"{spec.name} is a runtime-only case, which has no boot plan")
    boot = spec if spec.run == "joined" else SPECS[COLD_BOOT]
    lifecycle = (bh.LIFECYCLES.index(boot.lifecycle) if boot.lifecycle is not None
                 else f.lifecycle)
    entropy_ok = 0 if boot.entropy_failed else 1
    attempts = f["CHAIN_BOOT_ATTEMPT_BOUND"] if boot.at_bound else 0
    stage0, stores = store_images(f, boot, inputs)
    rom_out = rom(f, lifecycle=lifecycle, entropy_ok=entropy_ok, boot_target=boot.boot_target,
                  stage0=stage0, roots=inputs.roots, verify=inputs.verify)
    if rom_out.verdict != "release":
        return Plan(spec, lifecycle, entropy_ok, attempts, stage0, stores, rom_out, None)
    runtime_out = runtime(f, rom_out.state, boot_target=boot.boot_target, slot=boot.slot,
                          attempts=attempts, stores=stores, roots=inputs.roots,
                          verify=inputs.verify)
    if runtime_out.verdict != "release":
        return Plan(spec, lifecycle, entropy_ok, attempts, stage0, stores, rom_out, runtime_out)
    valid = check_image(f, inputs.images["kernel"], stage=f["BOOT_STAGE_CORE_KERNELS"],
                        region=f["CHAIN_KERNEL_REGION_BYTES"], floor=f.floor,
                        root_key=inputs.kernel_root, verify=inputs.verify)
    if valid.digest is None:
        raise ValueError(f"the staged kernel image does not verify: {valid.verdict}")
    request = item6_request(f, valid.digest)
    service_state = as_service(f, runtime_out.state)
    service_out = service(f, service_state, request)
    image = kernel_image(f, spec, inputs)
    response = (nonbinding_response(f, service_state, valid.digest)
                if spec.response == "nonbinding" else service_out.response)
    mmode_out = mmode(f, runtime_out.record, inputs.kernel_root, image, response, inputs.verify)
    return Plan(spec, lifecycle, entropy_ok, attempts, stage0, stores, rom_out, runtime_out,
                request, service_out, service_state, image, response, mmode_out)


def vacuity_findings(f: Facts, inputs: Inputs) -> list[str]:
    """Section 9.12's selection control, over the oracle's expectations: the three
    releasing cases' image digests and generation registers all differ, revert-past-bound's
    device register is cold-boot's, and recovery-latched's differs from it in item 3
    alone, so a capture that matches the oracle reads the selection off the measurement."""
    names = (COLD_BOOT, "recovery-latched", "revert-past-bound")
    released = {name: plan(f, SPECS[name], inputs).runtime for name in names}
    found: list[str] = []
    if any(out is None or out.verdict != "release" for out in released.values()):
        return [f"the oracle does not release all of {', '.join(names)}"]
    outs = {name: cast("RuntimeOutcome", out) for name, out in released.items()}
    at, width = f["HANDOFF_IMAGE_DIGEST_AT"], f["BOOT_DIGEST_BYTES"]
    if (len({out.record[at:at + width] for out in outs.values()}) != len(names)
            or len({out.measured.generation for out in outs.values()}) != len(names)):
        found.append("the releasing cases' image digests or generation registers coincide")
    cold = outs[COLD_BOOT].measured.device
    if outs["revert-past-bound"].measured.device != cold:
        found.append("revert-past-bound's device register is not cold-boot's")
    latched = device_prologue(f, f.lifecycle, 1, 1).device
    if outs["recovery-latched"].measured.device != latched or latched == cold:
        found.append("recovery-latched's device register does not differ from cold-boot's in "
                     "item 3 alone")
    return found


def runtime_only_state(f: Facts, payload: bytes) -> bytes:
    """The state record a ROM run would leave for this stage-0 payload."""
    measured = device_prologue(f, f.lifecycle, 1, 0).extend(f, f["ITEM_STAGE_ROT_RUNTIME"],
                                                            shake(f, payload))
    return state_record(f, State(f["CHAIN_RUN_BOOT"], f.lifecycle, 1, 0, f.floor, measured))


# --- the table's columns, held against the oracle -----------------------------------


def _items(log: tuple[int, ...], f: Facts) -> tuple[str, str]:
    device = ",".join(str(code) for code in log if code < f["ITEM_STAGE_ROT_RUNTIME"])
    generation = ",".join(str(code) for code in log if code >= f["ITEM_STAGE_ROT_RUNTIME"])
    return device, generation or "none"


def table_findings(f: Facts, row: bh.ChainCase, spec: Spec, case: Plan | None) -> list[str]:
    """Where section 9.12's row and the oracle's expectation for it disagree."""
    found: list[str] = []
    where = f"{bh.CONTRACT}'s {row.name}"
    if case is None:
        verdict = {"bite-late": "bite", "bite-early": "bite", "limit": "no-verdict"}[spec.ending()]
        if (row.verdict, row.items, row.boot_control, row.main_die) != (verdict, "n/a", "n/a", "none"):
            found.append(f"{where} row does not state a {spec.ending()} runtime-only case")
        return found
    if row.verdict != case.verdict:
        found.append(f"{where} states {row.verdict}; the oracle decides {case.verdict}")
    log = case.runtime.measured.log if case.runtime is not None else case.rom.measured.log
    device, generation = _items(log, f)
    then = ""
    if case.service is not None and case.service.verdict == "release":
        then = f" then {f['ITEM_STAGE_CORE_KERNELS']}"
    if row.items != f"{device}; {generation}{then}":
        found.append(f"{where} lists items {row.items!r}; the oracle measures "
                     f"{device}; {generation}{then}")
    slot, attempts = ((case.runtime.selection.slot, case.runtime.selection.attempts)
                      if case.runtime is not None and case.runtime.selection is not None
                      else (spec.slot, case.attempts))
    letter = "A" if slot == f["CHAIN_SLOT_A"] else "B"
    if row.boot_control != f"{letter}, {attempts}":
        found.append(f"{where} leaves boot control {row.boot_control!r}; the oracle leaves "
                     f"{letter}, {attempts}")
    main = "none"
    if case.mmode is not None:
        main = "`SUCCESS`" if case.mmode.exit_code == 0 else f"`FAILURE: {case.mmode.exit_code}`"
    if row.main_die != main:
        found.append(f"{where} expects the main die {row.main_die}; the oracle expects {main}")
    return found


# --- captures: the bytes owed, and the fields decided otherwise -----------------------

_WIDTHS = {"log": "CHAIN_STATE_LOG_BYTES", "generation": "MEASURE_BYTES", "device": "MEASURE_BYTES",
           "chain": "MEASURE_BYTES", "runtime_digest": "BOOT_DIGEST_BYTES",
           "mmode_digest": "BOOT_DIGEST_BYTES", "kernel_digest": "BOOT_DIGEST_BYTES"}
HEAD = ("verdict", "phase", "released", "lifecycle", "health", "boot_target", "floor",
        "slot_initial", "attempts_initial", "slot_selected", "slot_final", "attempts_final",
        "pets_accepted", "pets_skipped", "nonce_at_arm", "bitten", "ticks_at_end",
        "steps_completed", "measure_count", "log", "generation", "device", "chain",
        "runtime_digest", "mmode_digest", "mmode_security_version", "mmode_payload_length")
MCAPTURE = ("verdict", "kernel_digest", "security_version", "payload_length", "request_written",
            "response_bound")


def head_field(f: Facts, name: str, prefix: str = "CHAIN_CAPTURE") -> tuple[int, int]:
    """A capture field's offset and width, from vos_chain.h's macros."""
    width = f[_WIDTHS[name]] if name in _WIDTHS else 8
    return f[f"{prefix}_{name.upper()}_AT"], width


type Relation = tuple[str, tuple[str, ...], Callable[[dict[str, int]], bool]]


@dataclass
class Expected:
    """A capture's owed bytes, with the fields decided by an admitted alternative, by a
    predicate, or not at all, each by name. Everything else, gaps included, must equal
    `data` exactly."""

    data: bytearray
    fields: dict[str, tuple[int, int]] = field(default_factory=dict)
    alternatives: dict[str, tuple[bytes, ...]] = field(default_factory=dict)
    relations: list[Relation] = field(default_factory=list)
    ignored: set[str] = field(default_factory=set)

    def put(self, name: str, value: int | bytes) -> None:
        at, width = self.fields[name]
        blob = value.to_bytes(width, "little") if isinstance(value, int) else value
        if len(blob) != width:
            raise ValueError(f"{name} is {len(blob)} bytes, not {width}")
        self.data[at:at + width] = blob

    def admit(self, name: str, value: int | bytes | None) -> None:
        """A field the contract leaves silent: zero, or `value` where a check reached it."""
        if value is None:
            return
        _, width = self.fields[name]
        self.alternatives[name] = (value.to_bytes(width, "little") if isinstance(value, int)
                                   else value,)

    def relate(self, text: str, names: tuple[str, ...], holds: Callable[[dict[str, int]], bool]) -> None:
        self.relations.append((text, names, holds))


def compare(label: str, owed: Expected, actual: bytes) -> tuple[list[str], dict[str, object]]:
    """The problems a capture shows against what is owed, and what the alternatives and
    predicates observed."""
    if len(actual) != len(owed.data):
        return [f"{label} capture is {len(actual)} bytes, not {len(owed.data)}"], {}
    problems: list[str] = []
    seen: dict[str, object] = {}
    masked = bytearray(actual)
    words: dict[str, int] = {}
    for name, (at, width) in owed.fields.items():
        got, want = actual[at:at + width], bytes(owed.data[at:at + width])
        if width == 8:
            words[name] = int.from_bytes(got, "little")
        masked[at:at + width] = want
        if name in owed.ignored:
            continue
        if name in owed.alternatives:
            if got != want and got not in owed.alternatives[name]:
                problems.append(f"{label} {name} is neither zero nor the value its check reached")
            seen[name] = "zero" if got == want else "reached"
        elif not any(name in names for _, names, _ in owed.relations) and got != want:
            problems.append(f"{label} {name} differs from the oracle's")
    for text, names, holds in owed.relations:
        values = {name: words[name] for name in names}
        seen.update(values)
        if not holds(values):
            problems.append(f"{label} {', '.join(names)} = {values} fails: {text}")
    if masked != owed.data:
        first = next(i for i, (a, b) in enumerate(zip(masked, owed.data, strict=True)) if a != b)
        problems.append(f"{label} bytes outside every field differ from zero, first at {first:#x}")
    return problems, seen


def _rot_expected(f: Facts) -> Expected:
    owed = Expected(bytearray(f["CHAIN_CAPTURE_BYTES"]))
    for name in HEAD:
        owed.fields[name] = head_field(f, name)
    for name, macro, width in (("record", "CHAIN_CAPTURE_RECORD_AT", "HANDOFF_BYTES"),
                               ("response", "CHAIN_CAPTURE_RESPONSE_AT", "CHAIN_RESPONSE_BYTES"),
                               ("request", "CHAIN_CAPTURE_REQUEST_AT", "CHAIN_REQUEST_BYTES"),
                               ("state", "CHAIN_CAPTURE_STATE_AT", "CHAIN_STATE_BYTES"),
                               ("window", "CHAIN_CAPTURE_WINDOW_AT", "CHAIN_MMODE_REGION_BYTES")):
        owed.fields[name] = (f[macro], f[width])
    return owed


def _measured(owed: Expected, f: Facts, measured: Measured) -> None:
    owed.put("measure_count", len(measured.log))
    owed.put("log", measured.log_bytes(f))
    owed.put("generation", measured.generation)
    owed.put("device", measured.device)
    owed.put("chain", measured.chain(f))


def boot_capture(f: Facts, case: Plan) -> Expected:
    """What R1's capture owes: section 9.11's head, the record, the state and the window."""
    owed = _rot_expected(f)
    boot = case.spec if case.spec.run == "joined" else SPECS[COLD_BOOT]
    reached = case.runtime is not None
    phase = ("CHAIN_PHASE_RELEASED" if case.released else
             "CHAIN_PHASE_RUNTIME" if reached else "CHAIN_PHASE_ROM")
    owed.put("verdict", f.codes[case.verdict])
    owed.put("phase", f[phase])
    owed.put("released", int(case.released))
    owed.put("lifecycle", case.lifecycle)
    owed.put("boot_target", boot.boot_target)
    owed.put("floor", f.floor)
    if case.entropy_ok:
        owed.put("health", f.health)
    else:
        owed.relate("the injected health word fails the start-up verdict", ("health",),
                    lambda v: (v["health"] >> 32) & 3 != 1)
    late, steps = f.late, f["CHAIN_RESET_STEPS"]
    owed.relate("the tick door read last is inside the window", ("ticks_at_end",),
                lambda v: v["ticks_at_end"] <= late)
    owed.put("bitten", 0)
    if case.runtime is None:
        _measured(owed, f, case.rom.measured)
        checked = case.rom.checked
        if checked is not None and checked.verdict == "refuse-digest":
            owed.admit("runtime_digest", checked.digest)
        return owed
    runtime_out = case.runtime
    _measured(owed, f, runtime_out.measured)
    rom_checked = case.rom.checked
    if rom_checked is None or rom_checked.digest is None:
        raise ValueError("a run that reached the runtime has no stage-0 digest")
    owed.put("runtime_digest", rom_checked.digest)
    owed.put("slot_initial", boot.slot)
    owed.put("attempts_initial", case.attempts)
    if runtime_out.selection is not None:
        owed.put("slot_selected", runtime_out.selection.selected)
        owed.put("slot_final", runtime_out.selection.slot)
        owed.put("attempts_final", runtime_out.selection.attempts)
    owed.put("steps_completed", steps)
    owed.relate("the challenge read at arming is nonzero", ("nonce_at_arm",),
                lambda v: v["nonce_at_arm"] != 0)
    owed.put("state", runtime_out.state)
    checked = runtime_out.checked
    if case.released and checked is not None and checked.digest is not None:
        owed.put("mmode_digest", checked.digest)
        owed.put("mmode_security_version", checked.version or 0)
        owed.put("mmode_payload_length", checked.length or 0)
        owed.put("record", runtime_out.record)
        owed.put("window", runtime_out.window)
        owed.relate("a release records an accepted pet at every pet point the period admits "
                    "and skips only the step completions", ("pets_accepted", "pets_skipped"),
                    lambda v: v["pets_accepted"] >= 1 and v["pets_skipped"] <= steps
                    and v["pets_accepted"] + v["pets_skipped"] == steps + 1)
        return owed
    if checked is not None:
        owed.admit("mmode_security_version", checked.version)
        owed.admit("mmode_payload_length", checked.length)
        if checked.verdict == "refuse-digest":
            owed.admit("mmode_digest", checked.digest)
    owed.relate("a runtime refusal reaches the step completions and at most the verification's "
                "pet point", ("pets_accepted", "pets_skipped"),
                lambda v: v["pets_accepted"] + v["pets_skipped"] in (steps, steps + 1))
    return owed


def service_capture(f: Facts, case: Plan) -> Expected:
    """What R2's capture owes: its verdict and phase, and the response, the request it
    read and the state after item 6, which section 9.11 compares; nothing else of the
    head is compared."""
    if case.service is None or case.request is None:
        raise ValueError(f"{case.spec.name} has no service run")
    owed = _rot_expected(f)
    owed.put("verdict", f.codes[case.service.verdict])
    owed.put("phase", f["CHAIN_PHASE_SERVICE"])
    owed.put("released", 0)
    owed.ignored |= set(HEAD) - {"verdict", "phase", "released"}
    owed.put("response", case.service.response)
    owed.put("request", case.request)
    owed.put("state", case.service.state)
    return owed


def main_capture(f: Facts, case: Plan) -> Expected:
    """What R3's signature region owes on `SUCCESS`: the mailbox as the M-mode stage
    leaves it, its request beside the placed response, and the M-mode capture. A
    refusal ends on `FAILURE: n`, on which the emulator writes no capture (section
    9.2), so its exit code is what the run decides."""
    out = case.mmode
    checked = out.checked if out is not None else None
    if (out is None or case.response is None or out.verdict != "release" or checked is None
            or checked.digest is None or checked.version is None or checked.length is None):
        raise ValueError(f"{case.spec.name} has no main-die capture to compare")
    owed = Expected(bytearray(f["CHAIN_MAIN_SIGNATURE_BYTES"]))
    owed.fields["request"] = (f["CHAIN_MAILBOX_REQUEST_AT"], f["CHAIN_REQUEST_BYTES"])
    owed.fields["response"] = (f["CHAIN_MAILBOX_RESPONSE_AT"], f["CHAIN_RESPONSE_BYTES"])
    base = f["CHAIN_MMODE_CAPTURE_BASE"] - f["CHAIN_MAILBOX_BASE"]
    for name in MCAPTURE:
        at, width = head_field(f, name, "CHAIN_MCAPTURE")
        owed.fields[f"mcapture.{name}"] = (base + at, width)
    owed.put("request", out.request)
    owed.put("response", case.response)
    owed.put("mcapture.verdict", f.codes[out.verdict])
    owed.put("mcapture.kernel_digest", checked.digest)
    owed.put("mcapture.security_version", checked.version)
    owed.put("mcapture.payload_length", checked.length)
    owed.put("mcapture.request_written", 1)
    owed.put("mcapture.response_bound", int(out.bound))
    return owed


# --- the staged directory -----------------------------------------------------------


def listing(root: Path, directory: str) -> list[str]:
    """Every file under one search directory by name, outside both staged trees."""
    base = root.resolve() / directory
    excluded = tuple((root.resolve() / tree).resolve()
                     for tree in (STAGED, boot_crypto_target.STAGED))
    return sorted(path.relative_to(base).as_posix() for path in base.rglob("*")
                  if path.is_file() and not any(path.resolve().is_relative_to(tree)
                                                for tree in excluded))


def freeze_findings(root: Path, manifest: Mapping[str, Any]) -> list[str]:
    """Section 9.13: the chain's verifier identities against M7.1f's staged manifest."""
    crypto = json.loads((root / boot_crypto_target.MANIFEST).read_text(encoding="utf-8"))
    found: list[str] = []
    sources = manifest.get("sources_sha256", {})
    crypto_sources = crypto.get("sources_sha256", {})
    for path in FROZEN:
        if path not in sources:
            found.append(f"no chain unit compiled {path}")
        elif sources[path] != crypto_sources.get(path):
            found.append(f"{path} as the chain compiled it is not {boot_crypto_target.MANIFEST}'s")
    chain_compiler = manifest.get("compiler_provenance", {})
    crypto_compiler = crypto.get("compiler_provenance", {})
    found += [f"the chain's compiler {key} is not {boot_crypto_target.MANIFEST}'s"
              for key in ("revision", "compiler_sha256")
              if not chain_compiler.get(key) or chain_compiler.get(key) != crypto_compiler.get(key)]
    ini = manifest.get("compiler_inputs_sha256", {}).get("compcert.ini")
    if ini is None or ini != crypto.get("compiler_inputs_sha256", {}).get("compcert.ini"):
        found.append(f"the chain's compcert.ini is not {boot_crypto_target.MANIFEST}'s")
    for unit, entry in manifest.get("units", {}).items():
        argv = entry.get("argv", []) if isinstance(entry, dict) else []
        missing = [argument for argument in REQUIRED_ARGUMENTS if argument not in argv]
        if missing:
            found.append(f"the {unit} unit was compiled without {', '.join(missing)}")
    return found


def _image_findings(f: Facts, name: str, data: bytes, entry: Mapping[str, Any]) -> list[str]:
    """One staged image against its manifest entry and its own header."""
    found: list[str] = []
    if hashlib.sha256(data).hexdigest() != entry.get("sha256"):
        found.append(f"{name} differs from its manifest")
    stage = entry.get("stage")
    kernel = stage == f["BOOT_STAGE_CORE_KERNELS"]
    size = f["CHAIN_KSTAGE_HEADER_BYTES"] if kernel else f["BOOT_HEADER_BYTES"]
    region = {f["BOOT_STAGE_ROT_RUNTIME"]: f["CHAIN_ROT_RUNTIME_REGION_BYTES"],
              f["BOOT_STAGE_MMODE_IMAGE"]: f["CHAIN_MMODE_REGION_BYTES"],
              f["BOOT_STAGE_CORE_KERNELS"]: f["CHAIN_KERNEL_REGION_BYTES"]}.get(cast("int", stage))
    if region is None or len(data) < size:
        return [*found, f"{name} is not a stage-0, -1 or -2 image"]
    magic = f["CHAIN_KSTAGE_MAGIC"] if kernel else f["BOOT_MAGIC"]
    length = _word(data, f["BOOT_HDR_PAYLOAD_LENGTH"])
    at = f["BOOT_HDR_PAYLOAD_DIGEST"]
    if (_word(data, f["BOOT_HDR_MAGIC"]) != magic or _word(data, f["BOOT_HDR_STAGE"]) != stage
            or _word(data, f["BOOT_HDR_PAYLOAD_OFFSET"]) != size or not 0 < length <= region
            or len(data) != size + length
            or data[at:at + f["BOOT_DIGEST_BYTES"]] != shake(f, data[size:])
            or _word(data, f["BOOT_HDR_SECURITY_VERSION"]) != entry.get("security_version")
            or length != entry.get("payload_length")):
        found.append(f"{name}'s header does not describe its payload and manifest entry")
    return found


@dataclass(frozen=True)
class Staged:
    """The staged directory, held to its manifest: streams, images and keys."""

    manifest: dict[str, Any]
    streams: dict[str, str]
    images: dict[str, bytes]
    roots: dict[int, bytes]
    kernel_root: bytes

    def inputs(self) -> Inputs:
        return Inputs(self.images, self.roots, self.kernel_root, recorded_verify(self.manifest))


def present(root: Path) -> bool:
    """Whether anything of the staged directory exists in this checkout."""
    directory = root / STAGED
    return directory.is_dir() and any(directory.iterdir())


def staged(root: Path) -> Staged:
    """The staged directory against its manifest, this checkout's sources, section 9.13's
    freeze and `boot-crypto verify`. No composer runs here; `boot_chain_target.layouts`
    re-derives the payloads where the composers are."""
    root = root.resolve()
    directory = root / STAGED
    if not directory.is_dir():
        raise ValueError(f"{STAGED} is not staged; run {GENERATOR}")
    present_files = sorted(path.name for path in directory.iterdir())
    if present_files != sorted(STAGED_FILES):
        raise ValueError(f"{STAGED} must hold exactly {sorted(STAGED_FILES)}, not {present_files}")
    manifest = json.loads((root / MANIFEST).read_text(encoding="utf-8"))
    if (not isinstance(manifest, dict) or manifest.get("schema") != 1
            or manifest.get("generator") != GENERATOR or manifest.get("contract") != bh.CONTRACT
            or not isinstance(manifest.get("floor"), int)):
        raise ValueError("the staged manifest does not describe this campaign")
    f = facts(root, cast("int", manifest["floor"]))
    files = manifest.get("files_sha256")
    if not isinstance(files, dict) or set(files) != set(STAGED_FILES) - {"manifest.json"}:
        raise ValueError("the staged manifest does not bind every staged file")
    for name, value in files.items():
        if receipts.digest(directory / name) != value:
            raise ValueError(f"{STAGED}/{name} differs from its manifest")
    sources = manifest.get("sources_sha256")
    if not isinstance(sources, dict) or not sources:
        raise ValueError("the staged manifest binds no source")
    for name, value in sources.items():
        path = (root / name).resolve()
        if not path.is_relative_to(root) or path.is_relative_to(directory):
            raise ValueError(f"invalid staged source: {name}")
        if not path.is_file() or receipts.digest(path) != value:
            raise ValueError(f"the staged chain is stale: {name} changed since staging; "
                             f"rerun {GENERATOR}")
    searched = manifest.get("search_directories")
    if (not isinstance(searched, dict)
            or not {PurePosixPath(name).parent.as_posix() for name in sources} <= set(searched)):
        raise ValueError("the staged manifest does not list every include search directory")
    for name, names in searched.items():
        path = (root / name).resolve()
        if not path.is_relative_to(root) or not path.is_dir():
            raise ValueError(f"invalid staged search directory: {name}")
        if listing(root, name) != names:
            raise ValueError(f"the staged chain is stale: the files in {name} changed since "
                             f"staging; rerun {GENERATOR}")
    units = manifest.get("units")
    if not isinstance(units, dict) or set(units) != set(UNITS):
        raise ValueError(f"the staged manifest must hold exactly the units {list(UNITS)}")
    header = HEADER.encode("utf-8")
    streams: dict[str, str] = {}
    for unit in UNITS:
        entry = units[unit]
        if not isinstance(entry, dict) or entry.get("file") != f"{unit}.s":
            raise ValueError(f"{unit} staged entry names another file")
        data = (directory / f"{unit}.s").read_bytes()
        if not data.startswith(header):
            raise ValueError(f"{unit} staged stream lacks its generated header")
        raw = data[len(header):]
        if hashlib.sha256(raw).hexdigest() != entry.get("assembly_sha256"):
            raise ValueError(f"{unit} staged stream differs from its manifest")
        stream = raw.decode("utf-8")
        if cd.refusals(stream):
            raise ValueError(f"{unit} staged stream is outside the accepted dialect")
        streams[unit] = stream
    stored = json.loads((root / IMAGES).read_text(encoding="utf-8"))
    entries = manifest.get("images")
    if (not isinstance(stored, dict) or stored.get("schema") != 1
            or not isinstance(stored.get("images"), dict) or not isinstance(entries, dict)
            or set(stored["images"]) != set(IMAGE_NAMES) or set(entries) != set(IMAGE_NAMES)):
        raise ValueError(f"{IMAGES} and the manifest must hold exactly {list(IMAGE_NAMES)}")
    images = {name: bytes.fromhex(cast("str", stored["images"][name])) for name in IMAGE_NAMES}
    problems = [problem for name in IMAGE_NAMES
                for problem in _image_findings(f, name, images[name], entries[name])]
    keys = manifest.get("keys", {})
    rom_roots = keys.get("rom_roots", {}) if isinstance(keys, dict) else {}
    if not isinstance(rom_roots, dict) or set(rom_roots) != set(bh.ROOT_STATES):
        raise ValueError(f"the staged manifest must carry one ROM root for each of {bh.ROOT_STATES}")
    roots = {bh.LIFECYCLES.index(state): bytes.fromhex(value) for state, value in rom_roots.items()}
    kernel_root = bytes.fromhex(cast("str", keys.get("kernel_root", "")))
    if any(len(key) != f["BOOT_PUBLIC_KEY_BYTES"] for key in roots.values()):
        problems.append("a ROM root is not an SLH-DSA-SHAKE-256s public key")
    if len(kernel_root) != f["CHAIN_KSTAGE_PUBLIC_KEY_BYTES"]:
        problems.append("the kernel-stage root is not an ML-DSA-87 public key")
    header_bytes = f["BOOT_HEADER_BYTES"]
    for name, tag in (("mmode-a", f.tags[0]), ("mmode-b", f.tags[1]),
                      ("mmode-recovery", f.tags[2]), ("mmode-a-below-floor", f.tags[0])):
        payload = images[name][header_bytes:]
        if not payload.endswith(tag) or kernel_root not in payload:
            problems.append(f"{name}'s payload does not carry the kernel-stage root and its tag")
    if images["mmode-a-below-floor"][header_bytes:] != images["mmode-a"][header_bytes:]:
        problems.append("the below-floor image does not carry slot A's payload")
    verify = recorded_verify(manifest)
    production = roots.get(f.lifecycle)
    try:
        for name in IMAGE_NAMES:
            image, kernel = images[name], name == "kernel"
            key = kernel_root if kernel else production
            if key is None or not verify(MLDSA if kernel else SLH, key,
                                         image[:f["BOOT_SIGNED_BYTES"]],
                                         image[f["BOOT_HDR_SIGNATURE"]:(f["CHAIN_KSTAGE_HEADER_BYTES"]
                                               if kernel else header_bytes)]):
                problems.append(f"OpenSSL did not accept {name} under its root")
    except ValueError as exc:
        problems.append(str(exc))
    problems += freeze_findings(root, manifest)
    if problems:
        raise ValueError("; ".join(problems))
    boot_crypto_target.staged(root)
    return Staged(manifest, streams, images, roots, kernel_root)


# --- the join -------------------------------------------------------------------------

# Every shard of one joined campaign must agree on these (F-718's identities).
SHARED = ("source_sha256", "model_source_sha256", "staged_manifest_sha256", "compiler_provenance",
          "compiler_inputs_sha256", "freeze", "periods_ns", "inst_limits", "timeouts", "floor",
          "watchdog_bounds", "contract", "scope")


def join(root: Path, reports: Mapping[str, Any], digests: Mapping[str, str]) -> dict[str, Any]:
    """One campaign receipt from shard receipts of the same inputs.

    The case set is section 9.12's table exactly; each case comes from at most one
    shard, every shared identity agrees, a main-die shard's `cold-boot` inputs are the
    ones `cold-boot`'s own shard recorded, and a case no shard executed is listed. The
    campaign passes only when every case executed and passed, `cold-boot` first.
    """
    universe = [row.name for row in require_cases(root)]
    if not reports:
        raise ValueError("a joined campaign needs shard reports")
    reference = next(iter(reports.values()))
    owners: dict[str, str] = {}
    rows: dict[str, dict[str, Any]] = {}
    shards: dict[str, object] = {}
    for name, report in reports.items():
        if isinstance(report, dict) and "error" in report:
            raise ValueError(f"{name} stopped before its cases completed: {report['error']}")
        if not isinstance(report, dict) or report.get("status") not in ("passed", "failed"):
            raise ValueError(f"{name} is not a completed chain report")
        for key in SHARED:
            if report.get(key) != reference.get(key):
                raise ValueError(f"{name} differs from the other shards in {key}")
        selection, cases = report.get("selection"), report.get("cases")
        if (not isinstance(selection, list) or not selection or not isinstance(cases, list)
                or not all(isinstance(row, dict) for row in cases)):
            raise ValueError(f"{name} lacks its selection or cases")
        for case in selection:
            if case not in universe:
                raise ValueError(f"{name} selects {case}, which section 9.12 does not name")
            if case in owners:
                raise ValueError(f"{name} repeats {case}, which {owners[case]} selected")
            owners[case] = name
        executed = [row.get("case") for row in cases]
        if len(set(executed)) != len(executed) or not set(executed) <= set(selection):
            raise ValueError(f"{name} executed a case twice or outside its selection")
        if report.get("unexecuted_cases") != [case for case in selection if case not in executed]:
            raise ValueError(f"{name} misstates its unexecuted cases")
        if report.get("passed") is not (len(executed) == len(selection)
                                        and all(row.get("passed") is True for row in cases)):
            raise ValueError(f"{name} states a verdict its cases do not support")
        for row in cases:
            rows[str(row["case"])] = {**row, "shard": name}
        shards[name] = {key: report.get(key) for key in (
            "selection", "status", "seconds", "jobs", "inputs_sha256", "cold_boot")}
    cold = rows.get(COLD_BOOT)
    for name, report in reports.items():
        imported = report.get("cold_boot")
        if imported is None:
            continue
        if not isinstance(imported, dict):
            raise TypeError(f"{name} records its cold-boot inputs in no readable form")
        if cold is None:
            raise ValueError(f"{name} ran main-die cases over a cold-boot no shard reports")
        if (imported.get("report_sha256") != digests.get(cold["shard"])
                or imported.get("r1_capture_sha256") != cold.get("r1_capture_sha256")
                or imported.get("r2_response_sha256") != cold.get("r2_response_sha256")):
            raise ValueError(f"{name}'s cold-boot inputs are not the ones cold-boot's receipt records")
    ordered = [rows[case] for case in universe if case in rows]
    unexecuted = [case for case in universe if case not in rows]
    cold_passed = cold is not None and cold.get("passed") is True
    passed = cold_passed and not unexecuted and all(row.get("passed") is True for row in ordered)
    return {"passed": passed, "status": "passed" if passed else "failed", "cases": ordered,
            "case_set": universe, "unexecuted_cases": unexecuted, "cold_boot_passed": cold_passed,
            **{key: reference.get(key) for key in SHARED}, "shards": shards,
            "shard_reports_sha256": dict(digests), "milestone_acceptance": "open"}


def configuration_variant(root: Path, base: str, changes: Mapping[tuple[str, ...], object],
                          path: Path) -> dict[str, object]:
    """A copy of a shipped configuration with only `changes` made, written to `path`.

    Every changed key must already be declared, and the variant's every other leaf must
    be the shipped file's; the record names the base, both digests and the changes.
    """
    shipped = jsonc.load(root / base)
    variant = json.loads(json.dumps(shipped))
    for keys, value in changes.items():
        node = _walk(variant, *keys[:-1])
        if not isinstance(node, dict) or keys[-1] not in node:
            raise ValueError(f"{base} declares no {'.'.join(keys)}; the variant would add it")
        cast("dict[str, object]", node)[keys[-1]] = value
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(variant, indent=2) + "\n", encoding="utf-8", newline="\n")
    before, after = config.flat(shipped), config.flat(jsonc.load(path))
    changed = {key for key in before.keys() | after.keys() if before.get(key) != after.get(key)}
    if not changed <= {".".join(keys) for keys in changes}:
        raise ValueError(f"the variant of {base} changes {sorted(changed)} beyond its keys")
    return {"base": base, "base_sha256": receipts.digest(root / base), "file": path.name,
            "sha256": receipts.digest(path),
            "changes": {".".join(keys): value for keys, value in changes.items()}}
