# SPDX-License-Identifier: Apache-2.0
"""Source-bound purecap target comparisons for the real signature interfaces."""

import hashlib
import json
import re
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, cast

from vos import asm, boot_crypto, boot_handoff, boot_target, image, kernel_restore, receipts
from vos.cli import compiler_diff as cd

SOURCE = "firmware/crypto/signature_target.c"
MODES = ("slh", "slh-internal", "mldsa", "mldsa-internal", "mldsa-mu")
STACK_BYTES = 32768
SOURCES = ("firmware", "tools/vos", "tools/generated/dialect-table.json")
# The contained compiler's stream for SOURCE, one per interface, tracked so that a
# machine without that compiler can execute it. Each file is HEADER followed by the
# stream's exact bytes; the manifest binds those bytes to the compiler build, its
# configuration and the checkout files the preprocessor read.
STAGED = "firmware/crypto/target"
MANIFEST = f"{STAGED}/manifest.json"
HEADER = ("# SPDX-License-Identifier: Apache-2.0\n"
          f"# Generated by run.py boot-crypto stage from {SOURCE}.\n"
          "# The contained compiler's stream follows byte for byte; manifest.json binds it.\n")
_MARKER = re.compile(r'^# \d+ "([^"]+)"', re.MULTILINE)
# Every shard of one joined campaign must agree on these fields.
SHARED = ("source_sha256", "model_source_sha256", "compiler_provenance", "compiler_inputs_sha256",
          "compilation", "staged_manifest_sha256", "acvp_revision", "acvp_sources",
          "acvp_notice_sha256", "stack_bytes", "population_scope", "scope", "limits")


def compiler_provenance(ccomp: Path) -> tuple[dict[str, object], dict[str, str]]:
    """Bind the selected executable to its successful contained source build."""
    ccomp = ccomp.resolve()
    result_path, inputs_path = ccomp.parent / "build-result.json", ccomp.parent / "build-inputs.json"
    result = json.loads(result_path.read_text(encoding="utf-8"))
    inputs = json.loads(inputs_path.read_text(encoding="utf-8"))
    if (not isinstance(result, dict) or result.get("passed") is not True
            or result.get("inputs_unchanged") is not True
            or result.get("compiler_sha256") != receipts.digest(ccomp)
            or not isinstance(result.get("revision"), str)):
        raise ValueError("signature target requires a successful source-bound compiler build")
    if not isinstance(inputs, dict) or not inputs:
        raise ValueError("signature target compiler source manifest is absent")
    for name, identity in inputs.items():
        path = (ccomp.parent / name.removeprefix("native:")).resolve()
        if not path.is_relative_to(ccomp.parent) or not isinstance(identity, dict):
            raise ValueError("invalid compiler source manifest entry")
        expected = identity.get("sha256" if name.startswith("native:") else "canonical_sha256")
        if receipts.digest(path) != expected:
            raise ValueError(f"compiler build source changed: {name}")
    return ({"revision": result["revision"], "kind": result.get("kind"),
             "compiler_sha256": result["compiler_sha256"], "source_count": len(inputs)},
            {str(path): receipts.digest(path) for path in (result_path, inputs_path)})


def population(work: Path) -> list[boot_crypto.Case]:
    """Pinned ACVP positives with every applicable authored refusal family."""
    result: list[boot_crypto.Case] = []
    boot_crypto.fetch(boot_crypto.BASE + "README.md", work / "NIST-NOTICE.md", boot_crypto.NOTICE_SHA)
    for scheme, (directory, digest) in boot_crypto.SOURCES.items():
        data = boot_crypto.fetch(boot_crypto.BASE +
            f"gen-val/json-files/{directory}/internalProjection.json", work / (scheme + ".json"), digest)
        selected, _ = boot_crypto.cases(json.loads(data), scheme)
        for mode in MODES:
            if not mode.startswith(scheme):
                continue
            positive = next(case for case in selected if case.mode == mode and case.expected)
            result.extend([positive, *boot_crypto.refusals(positive)])
    return result


def select(cases: list[boot_crypto.Case], modes: tuple[str, ...],
           first: bool) -> list[boot_crypto.Case]:
    """The selected interfaces' population, or with `first` their positives alone."""
    chosen = [case for case in cases if case.mode in modes]
    if first:
        chosen = [next(case for case in chosen if case.mode == mode and case.expected)
                  for mode in modes]
    return chosen


def interface(mode: str) -> tuple[int, int]:
    """The scheme and interface selectors that SOURCE's preprocessor reads."""
    return (1 if mode.startswith("slh") else 2,
            3 if mode.endswith("-mu") else 2 if mode.endswith("-internal") else 1)


def accept(mode: str, stream: str) -> int:
    """Hold one stream to the accepted dialect and stack; no compiler is needed."""
    if cd.refusals(stream):
        raise ValueError(f"{mode} target stream is outside the accepted dialect")
    frames = boot_target.stack_ceiling(stream)
    if frames > STACK_BYTES:
        raise ValueError(f"{mode} frame sum {frames} exceeds stack {STACK_BYTES}")
    return frames


def compile_mode(root: Path, out: Path, ccomp: Path, compiler_args: list[str],
                 mode: str) -> tuple[cd.Compiled, str, int]:
    """Compile one interface through the contained compiler and accept its stream."""
    scheme, selected = interface(mode)
    unit = cd.compile_c([str(ccomp), *compiler_args, "-fverifiedos-typed",
        "-I" + str(root / "firmware/include"), f"-DVOS_TARGET_SCHEME={scheme}",
        f"-DVOS_TARGET_INTERFACE={selected}"], root / SOURCE, out / mode / "compiled")
    if unit.stream is None or unit.exit_code:
        raise ValueError(f"{mode} target compilation refused: {unit.said}")
    return unit, unit.stream, accept(mode, unit.stream)


def read_sources(root: Path, unit: cd.Compiled) -> dict[str, str]:
    """This checkout's files that the preprocessor read, from the unit's line markers."""
    base = root.resolve()
    text = unit.preprocessed.path.read_text(encoding="utf-8", errors="replace")
    found: dict[str, str] = {}
    for name in dict.fromkeys(_MARKER.findall(text)):
        if name.startswith("<"):
            continue
        path = (Path(unit.preprocessed.cwd) / name).resolve()
        if path.is_relative_to(base):
            found[path.relative_to(base).as_posix()] = receipts.digest(path)
    if SOURCE not in found:
        raise ValueError("the preprocessed unit does not name its own source")
    return found


def portable(argv: tuple[str, ...], root: Path) -> list[str]:
    """A compile argv without this machine's paths: the compiler by role, its
    configuration files by name and the include directory relative to the checkout."""
    include = "-I" + str(root / "firmware/include")
    result = ["ccomp"]
    for index, argument in enumerate(argv[1:], start=1):
        if argv[index - 1] in ("-conf", "-stdlib", "-include"):
            result.append(Path(argument).name)
        else:
            result.append("-Ifirmware/include" if argument == include else argument)
    return result


def _named(files: dict[str, str]) -> dict[str, str]:
    named = {Path(path).name: digest for path, digest in files.items()}
    if len(named) != len(files):
        raise ValueError("compiler inputs and receipts need distinct file names")
    return dict(sorted(named.items()))


def _json(payload: object) -> bytes:
    """The bytes receipts.write publishes, so a comparison sees what a write stores."""
    return (json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def stage(root: Path, out: Path, ccomp: Path, compiler_args: list[str],
          check: bool = False) -> dict[str, Any]:
    """Compile every interface and write STAGED, or with `check` compare it.

    The staged files are the only compiler output a hosted runner receives. Staging
    runs where the contained compiler is provisioned and binds its provenance, its
    configuration and the exact checkout files the preprocessor read; the stream
    acceptance checks run again wherever the files are executed.
    """
    root, out, ccomp = (path.resolve() for path in (root, out, ccomp))
    provenance, provenance_files = compiler_provenance(ccomp)
    compiler_files = boot_target.compiler_inputs(compiler_args)
    directory = root / STAGED
    tracked = ({path.name: path.read_bytes() for path in directory.iterdir()}
               if directory.is_dir() else {})
    files: dict[str, bytes] = {}
    modes: dict[str, object] = {}
    sources: dict[str, str] = {}
    native: dict[str, object] = {}
    for mode in MODES:
        unit, stream, frames = compile_mode(root, out, ccomp, compiler_args, mode)
        raw = (out / mode / "compiled" / f"{Path(SOURCE).stem}.s").read_bytes()
        if hashlib.sha256(raw).hexdigest() != unit.stream_sha256:
            raise ValueError(f"{mode} stream changed after compilation")
        sources.update(read_sources(root, unit))
        files[f"{mode}.s"] = HEADER.encode("utf-8") + raw
        # The unit's line markers name this checkout's absolute include paths, so its
        # digest stays in the native receipt rather than in the portable manifest.
        native[mode] = {"argv": list(unit.argv), "preprocessed_sha256": unit.preprocessed.sha256}
        modes[mode] = {"file": f"{mode}.s", "assembly_sha256": unit.stream_sha256,
                       "argv": portable(unit.argv, root), "sum_of_function_frames": frames,
                       "lines": len(stream.splitlines())}
    if (compiler_provenance(ccomp) != (provenance, provenance_files)
            or boot_target.compiler_inputs(compiler_args) != compiler_files
            or any(receipts.digest(root / name) != value for name, value in sources.items())):
        raise ValueError("staging inputs changed during compilation")
    manifest = {"schema": 1, "generator": "run.py boot-crypto stage", "source": SOURCE,
                "stack_bytes": STACK_BYTES, "compiler_provenance": provenance,
                "compiler_receipts_sha256": _named(provenance_files),
                "compiler_inputs_sha256": _named(compiler_files),
                "sources_sha256": dict(sorted(sources.items())), "modes": modes}
    files["manifest.json"] = _json(manifest)
    differences = sorted(name for name in files.keys() | tracked.keys()
                         if files.get(name) != tracked.get(name))
    if not check:
        if unexpected := sorted(tracked.keys() - files.keys()):
            raise ValueError(f"{STAGED} holds files staging does not own: {unexpected}")
        for name, data in files.items():
            with receipts.atomic_path(directory / name) as pending:
                pending.write_bytes(data)
    return {"passed": not check or not differences, "check": check, "differences": differences,
            "manifest": manifest, "native_units": native,
            "native_compiler_inputs_sha256": compiler_files,
            "native_compiler_receipts_sha256": provenance_files,
            "compiler_path": str(ccomp)}


def staged(root: Path) -> tuple[dict[str, Any], dict[str, str]]:
    """The tracked streams, held to their manifest, header and this checkout's sources."""
    root = root.resolve()
    directory = root / STAGED
    manifest = json.loads((root / MANIFEST).read_text(encoding="utf-8"))
    if (not isinstance(manifest, dict) or manifest.get("schema") != 1
            or manifest.get("source") != SOURCE or manifest.get("stack_bytes") != STACK_BYTES
            or not isinstance(manifest.get("compiler_provenance"), dict)
            or not isinstance(manifest.get("compiler_inputs_sha256"), dict)):
        raise ValueError("the staged manifest does not describe this campaign")
    modes, sources = manifest.get("modes"), manifest.get("sources_sha256")
    if not isinstance(modes, dict) or set(modes) != set(MODES):
        raise ValueError("the staged manifest must hold exactly the five interfaces")
    if not isinstance(sources, dict) or SOURCE not in sources:
        raise ValueError("the staged manifest binds no source")
    expected = {"manifest.json", *(f"{mode}.s" for mode in MODES)}
    if (present := {path.name for path in directory.iterdir()}) != expected:
        raise ValueError(f"{STAGED} must hold exactly {sorted(expected)}, not {sorted(present)}")
    for name, value in sources.items():
        path = (root / name).resolve()
        if not path.is_relative_to(root) or path.is_relative_to(directory):
            raise ValueError(f"invalid staged source: {name}")
        if not path.is_file() or receipts.digest(path) != value:
            raise ValueError(f"the staged streams are stale: {name} changed since staging; "
                             "rerun run.py boot-crypto stage")
    header = HEADER.encode("utf-8")
    streams: dict[str, str] = {}
    for mode in MODES:
        entry = modes[mode]
        if not isinstance(entry, dict) or entry.get("file") != f"{mode}.s":
            raise ValueError(f"{mode} staged entry names another file")
        data = (directory / f"{mode}.s").read_bytes()
        if not data.startswith(header):
            raise ValueError(f"{mode} staged stream lacks its generated header")
        raw = data[len(header):]
        if hashlib.sha256(raw).hexdigest() != entry.get("assembly_sha256"):
            raise ValueError(f"{mode} staged stream differs from its manifest")
        stream = raw.decode("utf-8")
        if accept(mode, stream) != entry.get("sum_of_function_frames"):
            raise ValueError(f"{mode} staged frame sum differs from its manifest")
        streams[mode] = stream
    return manifest, streams


def compose(stream: str, case: boot_crypto.Case) -> str:
    """Supply all eight real arguments, with no generated expected result in C."""
    setup = ""
    objects: list[tuple[str, bytes, int]] = []
    for register, label, data in ((10, "pk", case.pk), (12, "message", case.message),
                                  (14, "context", case.context), (16, "signature", case.signature)):
        extent = 1 << max(0, (len(data) - 1).bit_length())
        objects.append((label, data, extent))
        setup += (f"        li t0, vos_crypto_{label}\n"
                  f"        csetaddr c{register}, c4, t0\n"
                  f"        li t0, {extent}\n"
                  f"        csetbounds c{register}, c{register}, t0\n"
                  "        li t0, 3\n"
                  f"        candperm c{register}, c{register}, t0\n"
                  f"        li x{register + 1}, {len(data)}\n")
    anchor = "        call    main\n"
    if cd.PROLOGUE.count(anchor) != 1:
        raise ValueError("compiler harness must have exactly one main call")
    stack_size = f"        li      t1, {cd.STACK_BYTES}\n"
    stack_space = f"        .space  {cd.STACK_BYTES}\n"
    stack_alignment = "        .align  8\n__vos_stack:\n"
    if (cd.PROLOGUE.count(stack_size) != 1 or cd.EPILOGUE.count(stack_space) != 1
            or cd.EPILOGUE.count(stack_alignment) != 1):
        raise ValueError("compiler harness stack anchors changed")
    prologue = cd.PROLOGUE.replace(stack_size, f"        li      t1, {STACK_BYTES}\n")
    epilogue = cd.EPILOGUE.replace(stack_space, f"        .space  {STACK_BYTES}\n").replace(
        stack_alignment, f"        .balign {STACK_BYTES}\n__vos_stack:\n")
    composite = prologue.replace(anchor, setup + anchor, 1) + cd.normalize(stream) + "\n" + epilogue
    for label, data, extent in objects:
        composite += f"\n        .balign {extent}\nvos_crypto_{label}:\n"
        composite += "\n".join("        .byte " + ",".join(map(str, data[i:i+32]))
                                for i in range(0, len(data), 32)) + "\n"
        if extent > len(data):
            composite += f"        .space {extent - len(data)}\n"
    return composite


def target_verdict(log: str, process_exit: int | None, expected: bool) -> tuple[bool, str, int | None, str]:
    if process_exit is None:
        return False, "no-verdict", None, "target timed out"
    markers = [line.strip() for line in log.splitlines() if "SUCCESS" in line or "FAILURE" in line]
    if len(markers) != 1:
        return False, "no-verdict", None, "target must report exactly one HTIF decision"
    match = re.fullmatch(r"FAILURE: (\d+) \(0x([0-9a-fA-F]+)\)", markers[0])
    if markers[0] != "SUCCESS" and (match is None or int(match[1]) != int(match[2], 16)):
        return False, "no-verdict", None, "malformed HTIF decision"
    verdict, code, diagnostic = cd.htif_verdict(log, process_exit)
    wanted = 0 if expected else 1
    return (verdict == ("pass" if expected else "fail") and code == wanted and process_exit == wanted,
            verdict, code, diagnostic)


def run(root: Path, out: Path, ccomp: Path | None, compiler_args: list[str], simulator: Path,
        build_receipt: Path, timeout: int, inst_limit: int, first: bool = False,
        jobs: int = 1, modes: tuple[str, ...] = MODES) -> dict[str, Any]:
    """Execute the selected interfaces; without `ccomp`, from the staged streams."""
    started = time.monotonic()
    if not 1 <= jobs <= 6 or timeout < 1 or inst_limit < 1:
        raise ValueError("target requires 1..6 jobs and positive timeout/instruction limits")
    if not modes or len(set(modes)) != len(modes) or not set(modes) <= set(MODES):
        raise ValueError(f"target modes must be distinct members of {', '.join(MODES)}")
    if ccomp is None and compiler_args:
        raise ValueError("staged streams take no compiler arguments")
    modes = tuple(mode for mode in MODES if mode in modes)
    root, out, simulator, build_receipt = (
        path.resolve() for path in (root, out, simulator, build_receipt))
    out.mkdir(parents=True, exist_ok=True)
    sources = receipts.inputs(root, *SOURCES)
    model = receipts.inputs(root, "model")
    identities = {str(path): receipts.digest(path) for path in (simulator, build_receipt)}
    streams: dict[str, str] = {}
    compiled_records: dict[str, object] = {}
    manifest_sha256: str | None = None
    provenance: dict[str, object]
    provenance_files: dict[str, str] = {}
    compiler_files: dict[str, str]
    if ccomp is None:
        manifest, available = staged(root)
        manifest_sha256 = receipts.digest(root / MANIFEST)
        identities[str(root / MANIFEST)] = manifest_sha256
        provenance = cast("dict[str, object]", manifest["compiler_provenance"])
        compiler_files = cast("dict[str, str]", manifest["compiler_inputs_sha256"])
        for mode in modes:
            entry = manifest["modes"][mode]
            streams[mode] = available[mode]
            compiled_records[mode] = {"staged": True, **{key: entry[key] for key in (
                "assembly_sha256", "argv", "sum_of_function_frames")}}
    else:
        ccomp = ccomp.resolve()
        identities[str(ccomp)] = receipts.digest(ccomp)
        provenance, provenance_files = compiler_provenance(ccomp)
        identities.update(provenance_files)
        compiler_files = boot_target.compiler_inputs(compiler_args)
    kernel_restore.require_build(json.loads(build_receipt.read_text(encoding="utf-8")),
                                  identities[str(simulator)], model)
    cases = select(population(out), modes, first)
    host = boot_crypto.build(root, out / "host")
    host_identity = receipts.digest(host)
    host_compiler = receipts.executables("gcc")
    if ccomp is not None:
        for mode in modes:
            unit, streams[mode], frames = compile_mode(root, out, ccomp, compiler_args, mode)
            compiled_records[mode] = {"assembly_sha256": unit.stream_sha256,
                "preprocessed_sha256": unit.preprocessed.sha256, "argv": list(unit.argv),
                "sum_of_function_frames": frames}
    rows: list[dict[str, object]] = []

    def execute(case: boot_crypto.Case) -> dict[str, object]:
        work = out / case.name
        work.mkdir(parents=True, exist_ok=True)
        host_answer = boot_crypto.invoke(host, work, case)
        if host_answer != case.expected:
            raise ValueError(f"host C disagrees with expected input: {case.name}")
        composite = compose(streams[case.mode], case)
        (work / "target.s").write_text(composite, encoding="utf-8", newline="\n")
        assembler = asm.Assembler(composite, case.name)
        sections, symbols, entry = assembler.assemble()
        addresses = assembler.symbols
        if (addresses["__vos_stack_top"] - addresses["__vos_stack"] != STACK_BYTES
                or addresses["__vos_stack"] % STACK_BYTES):
            raise ValueError("signature target stack allocation is not exactly aligned and bounded")
        text = next(section for section in sections if section.name == ".text")
        if text.addr + len(text.data) > asm.DATA_BASE:
            raise ValueError("target signature text reaches the data section")
        elf, log = work / "target.elf", work / "target.log"
        image.write_elf(elf, sections, symbols, entry)
        argv = [str(simulator), "--config", str(root / boot_handoff.ROT_CONFIG),
                "--inst-limit", str(inst_limit), str(elf)]
        began = time.monotonic()
        exit_code: int | None = None
        try:
            with log.open("w", encoding="utf-8") as output:
                completed = subprocess.run(argv, cwd=out, stdout=output, stderr=subprocess.STDOUT,
                                           timeout=timeout, check=False)
                exit_code = completed.returncode
        except subprocess.TimeoutExpired:
            pass
        passed, verdict, code, diagnostic = target_verdict(log.read_text(encoding="utf-8"),
                                                         exit_code, case.expected)
        return {"case": case.name, "mode": case.mode, "expected": case.expected,
            "host": host_answer, "passed": passed, "verdict": verdict, "code": code,
            "process_exit": exit_code, "diagnostic": diagnostic, "argv": argv,
            "seconds": round(time.monotonic() - began, 3), "elf_sha256": receipts.digest(elf),
            "log_sha256": receipts.digest(log), "inputs_sha256": {
                field: boot_crypto.sha(getattr(case, field)) for field in ("pk", "message", "context", "signature")}}

    order = {case.name: index for index, case in enumerate(cases)}
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        positives = [case for case in cases if case.expected]
        for phase in (positives, [case for case in cases if not case.expected]):
            accepted_modes = {row["mode"] for row in rows if row["expected"] and row["passed"]}
            runnable = [case for case in phase if case.expected or case.mode in accepted_modes]
            pending = [pool.submit(execute, case) for case in runnable]
            for completed in as_completed(pending):
                rows.append(completed.result())
                rows.sort(key=lambda row: order[str(row["case"])])
                receipts.write(out / "progress.json", {"status": "incomplete", "cases": rows})
    if sources != receipts.inputs(root, *SOURCES) or model != receipts.inputs(root, "model"):
        raise ValueError("target crypto sources changed during campaign")
    if any(receipts.digest(Path(path)) != value for path, value in identities.items()):
        raise ValueError("target crypto tool or model receipt changed")
    if ccomp is not None:
        if compiler_files != boot_target.compiler_inputs(compiler_args):
            raise ValueError("target crypto compiler configuration or headers changed")
        if compiler_provenance(ccomp) != (provenance, provenance_files):
            raise ValueError("target crypto retained compiler sources changed")
    if host_identity != receipts.digest(host) or host_compiler != receipts.executables("gcc"):
        raise ValueError("target crypto host reference changed")
    return {"passed": len(rows) == len(cases) and all(row["passed"] for row in rows), "cases": rows,
        "modes": list(modes),
        "selection": {mode: [case.name for case in cases if case.mode == mode] for mode in modes},
        "first_positive_only": first, "complete_selected_population": not first and modes == MODES,
        "population_scope": "one ACVP positive per interface and every applicable authored refusal family",
        "all_acvp_vectors_executed": False,
        "unexecuted_cases": [case.name for case in cases if case.name not in {row["case"] for row in rows}],
        "source_sha256": sources, "model_source_sha256": model, "inputs_sha256": identities,
        "compilation": "direct" if ccomp is not None else "staged",
        "staged_manifest_sha256": manifest_sha256,
        "compiler_inputs_sha256": compiler_files, "compiled": compiled_records,
        "compiler_provenance": provenance,
        "host_binary_sha256": host_identity, "host_compiler": host_compiler,
        "acvp_revision": boot_crypto.REVISION, "acvp_sources": boot_crypto.SOURCES,
        "acvp_notice_sha256": boot_crypto.NOTICE_SHA,
        "stack_bytes": STACK_BYTES, "jobs": jobs, "seconds": round(time.monotonic() - started, 3),
        "scope": "real signature interfaces on the scalar RoT profile",
        "milestone_acceptance": "open", "limits": ["firmware release join separate",
            "no binary refinement, constant-time or masking claim"]}


def join(reports: dict[str, Any]) -> dict[str, Any]:
    """One campaign receipt from interface shards of the same inputs, keyed by source.

    Each interface must come from exactly one shard, every shard must have selected
    its interfaces' whole population and every shared identity must agree. A failed
    or unexecuted case keeps the joined receipt failed; an inconsistent set refuses.
    """
    if not reports:
        raise ValueError("a joined campaign needs shard reports")
    # The loop refuses a non-object report, the reference included, before reading it.
    reference = next(iter(reports.values()))
    owners: dict[str, str] = {}
    rows: dict[str, list[dict[str, Any]]] = {}
    selection: dict[str, list[str]] = {}
    compiled: dict[str, object] = {}
    shards: dict[str, object] = {}
    for name, report in reports.items():
        if isinstance(report, dict) and "error" in report:
            raise ValueError(f"{name} stopped before its cases completed: {report['error']}")
        if not isinstance(report, dict) or report.get("status") not in ("passed", "failed"):
            raise ValueError(f"{name} is not a completed target report")
        if report.get("first_positive_only") is not False:
            raise ValueError(f"{name} selected positives only")
        for key in SHARED:
            if report.get(key) != reference.get(key):
                raise ValueError(f"{name} differs from the other shards in {key}")
        modes, chosen, cases, records = (report.get(key) for key in (
            "modes", "selection", "cases", "compiled"))
        if (not isinstance(modes, list) or not modes or not isinstance(chosen, dict)
                or not isinstance(cases, list) or not isinstance(records, dict)
                or not set(modes) == set(chosen) == set(records)
                or not all(isinstance(row, dict) for row in cases)):
            raise ValueError(f"{name} lacks its interfaces, selection, cases or compilation")
        for mode in modes:
            if mode not in MODES or mode in owners:
                raise ValueError(f"{name} repeats or invents interface {mode}")
            if not isinstance(chosen[mode], list) or not chosen[mode]:
                raise ValueError(f"{name} selected nothing for {mode}")
            owners[mode] = name
            selection[mode] = list(chosen[mode])
            rows[mode] = []
            compiled[mode] = records[mode]
        for row in cases:
            mode = row.get("mode")
            if mode not in modes or row.get("case") not in chosen[mode]:
                raise ValueError(f"{name} executed a case outside its selection")
            rows[mode].append(row)
        executed = [row.get("case") for row in cases]
        if len(set(executed)) != len(executed):
            raise ValueError(f"{name} executed a case twice")
        ordered = [case for mode in modes for case in chosen[mode]]
        if report.get("unexecuted_cases") != [case for case in ordered if case not in executed]:
            raise ValueError(f"{name} misstates its unexecuted cases")
        if report.get("passed") is not (len(executed) == len(ordered)
                                        and all(row.get("passed") is True for row in cases)):
            raise ValueError(f"{name} states a verdict its cases do not support")
        shards[name] = {key: report.get(key) for key in (
            "modes", "status", "seconds", "jobs", "inputs_sha256", "host_binary_sha256",
            "host_compiler")}
    if missing := [mode for mode in MODES if mode not in owners]:
        raise ValueError(f"no shard ran {', '.join(missing)}")
    order = {case: index for index, case in enumerate(
        case for mode in MODES for case in selection[mode])}
    cases_out = sorted((row for mode in MODES for row in rows[mode]),
                       key=lambda row: order[row["case"]])
    executed_out = {row["case"] for row in cases_out}
    passed = all(report.get("passed") is True for report in reports.values())
    return {"passed": passed, "status": "passed" if passed else "failed", "cases": cases_out,
            "modes": list(MODES), "selection": {mode: selection[mode] for mode in MODES},
            "first_positive_only": False, "complete_selected_population": True,
            "unexecuted_cases": [case for case in order if case not in executed_out],
            **{key: reference.get(key) for key in SHARED}, "compiled": compiled,
            "shards": shards, "all_acvp_vectors_executed": False, "milestone_acceptance": "open"}
