# SPDX-License-Identifier: Apache-2.0
"""Generate the simulation wrappers' register constants from their owners."""

import re
from pathlib import Path

UART = "upstream/mocha/hw/vendor/lowrisc_ip/ip/uart/rtl/uart_reg_pkg.sv"
UART_SPEC = "upstream/mocha/hw/vendor/lowrisc_ip/ip/uart/data/uart.hjson"
BLOCK = "interfaces/block-device-contract.md"
BLOCK_MODEL = "model/model/sys/block_device.sail"
ARTIFACT = "rtl/vos_device_regs_pkg.sv"


def _one(pattern: str, text: str, label: str) -> str:
    matches = list(re.finditer(pattern, text))
    if len(matches) != 1:
        raise ValueError(f"{label}: expected one owner declaration, found {len(matches)}")
    value = matches[0].group(1)
    if not isinstance(value, str):
        raise TypeError(f"{label}: owner declaration has no string value")
    return value


def emit(root: Path) -> str:
    uart = (root / UART).read_text(encoding="utf-8")
    spec = (root / UART_SPEC).read_text(encoding="utf-8")
    block = (root / BLOCK).read_text(encoding="utf-8")
    model = (root / BLOCK_MODEL).read_text(encoding="utf-8")
    lines = ["// SPDX-License-Identifier: Apache-2.0",
             "// Generated by vos.device_regs from the owners below; rtl devicescheck checks it.",
             f"// UART: {UART}", f"// Status fields: {UART_SPEC}", f"// Block: {BLOCK}",
             f"// Model bounds: {BLOCK_MODEL}",
             "package vos_device_regs_pkg;"]
    for name in ("STATUS", "RDATA", "WDATA"):
        value = _one(r"\bUART_" + name + r"_OFFSET\s*=\s*\d+'h\s*([0-9a-fA-F]+)\s*;", uart, name)
        lines.append(f"  localparam logic [63:0] UART_{name} = 64'h{int(value, 16):x};")
    for name in ("TXFULL", "RXFULL", "TXEMPTY", "TXIDLE", "RXIDLE", "RXEMPTY"):
        value = _one(r'bits:\s*"(\d+)"\s+name:\s*"' + name + '"', spec, name)
        lines.append(f"  localparam int unsigned UART_{name}_BIT = {int(value)};")
    for name in ("VERSION", "BLOCK_BYTES", "BLOCK_COUNT", "STATUS", "RESULT", "BLOCK", "COMMAND", "ACK"):
        value = _one(r"(?m)^\| `0x([0-9a-fA-F]+)` \| `" + name + r"` \|", block, name)
        lines.append(f"  localparam logic [63:0] BLK_{name} = 64'h{int(value, 16):x};")
    value = _one(r"(?m)^\| `0x([0-9a-fA-F]+) \+ 8\*i`,", block, "DATA")
    lines.append(f"  localparam logic [63:0] BLK_DATA = 64'h{int(value, 16):x};")
    for name in ("max_bytes", "max_block_bytes"):
        value = _one(r"(?m)^let blkdev_" + name + r"\s*:\s*int\(\d+\)\s*=\s*(\d+)$", model, name)
        lines.append(f"  localparam int unsigned BLK_{name.upper()} = {int(value)};")
    lines.extend(["endpackage", ""])
    return "\n".join(lines)
