# SPDX-License-Identifier: Apache-2.0
"""Generate actual finite allocator histories for independent Gallina checking."""

from vos import elastic_pool as p


def histories() -> list[list[p.Event]]:
    result = p.generated_histories(4)
    for cls in (0, 1):
        for holder in (1, 2, 3):
            for count in (1, 2, 3):
                pool = p.fixture()
                grant = pool.allocate(holder, cls, 0)
                for _ in range(count):
                    pool.write(grant, 0, 7)
                    pool.release(grant)
                    pool.clear_registers(grant.slot)
                    pool.barrier()
                    pool.sweep_begin()
                    pool.sweep_end()
                    grant = pool.allocate(holder + 1, cls, 0)
                result.append(pool.history)
    for barrier_during_sweep in (False, True):
        pool = p.fixture()
        first, second = pool.allocate(1, 0, 0), pool.allocate(2, 0, 0)
        pool.release(first)
        pool.clear_registers(first.slot)
        pool.barrier()
        pool.sweep_begin()
        pool.release(second)
        pool.clear_registers(second.slot)
        if barrier_during_sweep:
            pool.barrier()
        pool.sweep_end()
        pool.allocate(3, 0, 0)
        if not barrier_during_sweep:
            pool.barrier()
        pool.sweep_begin()
        pool.sweep_end()
        pool.allocate(4, 0, 0)
        result.append(pool.history)
    unique: dict[tuple[p.Event, ...], list[p.Event]] = {}
    for history in result:
        errors = p.history_errors(p.fixture().plan, history)
        if errors:
            raise p.PoolError(f"campaign violates {sorted(errors)}: {history}")
        unique[tuple(history)] = history
    return list(unique.values())


def gallina_event(event: p.Event) -> str:
    name, args = event
    if name == "Grant":
        holder, cls, base, cap_base, cap_length = args
        return f"Grant {holder} {cls} {base} (chunk_cap {cap_base} {cap_length})"
    return name + (" " + " ".join(str(n) for n in args) if args else "")


def render() -> str:
    # Generated headers omit requirement ids: ElasticPool owns the scope and
    # the generator's byte check must not race the shared header generator.
    lines = [
        "(* SPDX-License-Identifier: Apache-2.0 *)",
        "(* =========================================================================",
        "   Generated by vos.elastic_pool_campaign.render. Do not edit.",
        "   Finite allocator traces checked against the original pool contract.",
        "   This is finite trace evidence, not the allocator refinement theorem.",
        "   ========================================================================= *)",
        "From Stdlib Require Import List.",
        "Require Import CyclicExecutive MemoryPlan ElasticDomain ElasticPool.",
        "Import ListNotations.",
        "",
    ]
    for index, history in enumerate(histories()):
        lines.extend([
            f"Definition pool_trace_{index} : list AllocEvent :=",
            "  [" + "; ".join(gallina_event(event) for event in history) + "].",
            f"Example pool_trace_{index}_safe :",
            f"  PoolGuarantees pool_reference_arena pool_trace_{index}.",
            "Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.",
            "",
        ])
    return "\n".join(lines)
