# SPDX-License-Identifier: Apache-2.0
"""Scalar lifecycle context-slot layout and its generated C interface.

These are aligned scalar cells in an existing partition context, not an IDL
message or a C struct overlay. The fixed formats and values have one owner here;
the unit capacity is read from the existing supervisor source interface.
"""

import re
from pathlib import Path

ARTIFACT = "supervisor/include/vos_context_layout.h"
REQUEST = ("SEQUENCE", "OPERATION", "EPOCH", "MEMBERS", "COUNT", "ATTEMPTS")
ACK = ("SEQUENCE", "STATUS", "OPERATION", "EPOCH", "PHASE", "MEMBERS",
       "STARTED", "COUNT", "REFUSED", "ATTEMPTS", "NOW", "DEADLINE")
OPERATIONS = ("NONE", "RETIRE", "START")
PHASES = ("INITIAL", "RETIRED", "RUNNING", "FAILED")
STATUS = ("OK", "INVALID", "STALE", "INCOMPLETE", "EARLY", "START_REFUSED")


def layout(root: Path) -> dict[str, int]:
    source = (root / "supervisor/include/vos_supervisor.h").read_text(encoding="utf-8")
    counts = re.findall(r"^#define VOS_SUPERVISOR_UNITS (\d+)U$", source, re.MULTILINE)
    if len(counts) != 1 or not 1 <= int(counts[0]) <= 16:
        raise ValueError("context slots require one supervisor capacity in [1, 16]")
    units = int(counts[0])
    values: dict[str, int] = {"WORD_BYTES": 8, "UNITS": units}
    for prefix, names in (("REQ", REQUEST), ("ACK", ACK), ("OP", OPERATIONS),
                           ("PHASE", PHASES), ("STATUS", STATUS)):
        values.update({f"{prefix}_{name}": index for index, name in enumerate(names)})
    values["REQ_STARTS"] = len(REQUEST)
    values["START_UNIT"] = 0
    values["START_GRANTS"] = 1
    values["START_WORDS"] = 2
    values["REQ_USED"] = len(REQUEST) + 2 * units
    values["ACK_RETIRED"] = len(ACK)
    values["ACK_USED"] = len(ACK) + units
    for prefix in ("REQ", "ACK"):
        values[f"{prefix}_WORDS"] = 1 << (values[f"{prefix}_USED"] - 1).bit_length()
        values[f"{prefix}_BYTES"] = values[f"{prefix}_WORDS"] * values["WORD_BYTES"]
    return values


def header(root: Path) -> str:
    lines = ["// SPDX-License-Identifier: Apache-2.0",
             "/* Generated by tools/vos/supervisor_context.py; do not edit. */",
             "#ifndef VOS_CONTEXT_LAYOUT_H", "#define VOS_CONTEXT_LAYOUT_H", ""]
    lines.extend(f"#define VOS_CTX_{key} {value}U" for key, value in layout(root).items())
    return "\n".join([*lines, "", "#endif", ""])
