(* SPDX-License-Identifier: Apache-2.0 *)
(* GENERATED by python tools/run.py device-registers emit; K-88 checks it.
   Owner: interfaces/device-registers.json. R-05-083: pure field access, no MMIO authority.
   R-05-138 and R-15-002b: offsets alone never construct a capability.
   These theorems check layouts, not device behavior or HAL refinement. *)
From Stdlib Require Import NArith.
Open Scope N_scope.

Definition declared_extract (word shift width : N) : N :=
  (word / 2 ^ shift) mod 2 ^ width.

Lemma shift_mask_correct : forall word shift width : N,
  N.land (N.shiftr word shift) (N.ones width) = declared_extract word shift width.
Proof. intros; rewrite N.land_ones, N.shiftr_div_pow2; reflexivity. Qed.

(* clint: registers. *)
Definition clint_mtimecmp_offset : N := 16384.
Definition clint_mtime_offset : N := 49144.
(* imsic: registers. *)
Definition imsic_seteipnum_offset : N := 0.
Definition imsic_eip_offset : N := 8.
(* revocation: registers. *)
Definition revocation_bitmap_word_offset : N := 0.
(* memory_sequencer: refused. *)
(* otp: registers. *)
Definition otp_state_offset : N := 0.
Definition otp_burn_offset : N := 8.
Definition otp_dm_gate_offset : N := 16.
Definition otp_fuse_count_offset : N := 24.
Definition otp_fuse_word_offset : N := 256.
(* trng: registers. *)
Definition trng_draw_offset : N := 0.
Definition trng_health_offset : N := 8.
Definition trng_sources_offset : N := 16.
Definition trng_budget_offset : N := 24.
Definition trng_startup_offset : N := 32.
(* monotonic_counters: registers. *)
Definition monotonic_counters_counter_offset : N := 0.
Definition monotonic_counters_advance_offset : N := 32.
Definition monotonic_counters_count_offset : N := 40.
(* watchdog: registers. *)
Definition watchdog_nonce_offset : N := 0.
Definition watchdog_ticks_offset : N := 8.
Definition watchdog_pet_offset : N := 16.
Definition watchdog_bitten_offset : N := 24.
Definition watchdog_early_offset : N := 32.
Definition watchdog_late_offset : N := 40.
Definition watchdog_arm_offset : N := 48.
(* boot_rom: memory. *)
(* uart: external. *)
(* blkdev: registers. *)
Definition blkdev_version_offset : N := 0.
Definition blkdev_block_bytes_offset : N := 8.
Definition blkdev_block_count_offset : N := 16.
Definition blkdev_status_offset : N := 24.
Definition blkdev_result_offset : N := 32.
Definition blkdev_block_offset : N := 40.
Definition blkdev_command_offset : N := 48.
Definition blkdev_ack_offset : N := 56.
Definition blkdev_data_offset : N := 256.
(* htif: registers. *)
Definition htif_tohost_offset : N := 0.

Definition clint_mtimecmp_lo_shift : N := 0.
Definition clint_mtimecmp_lo_width : N := 32.
Definition clint_mtimecmp_lo_get (word : N) : N :=
  N.land (N.shiftr word 0) 4294967295.
Theorem clint_mtimecmp_lo_correct : forall word : N,
  clint_mtimecmp_lo_get word = declared_extract word clint_mtimecmp_lo_shift clint_mtimecmp_lo_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 32)
  = declared_extract word 0 32); apply shift_mask_correct. Qed.

Definition clint_mtimecmp_hi_shift : N := 32.
Definition clint_mtimecmp_hi_width : N := 32.
Definition clint_mtimecmp_hi_get (word : N) : N :=
  N.land (N.shiftr word 32) 4294967295.
Theorem clint_mtimecmp_hi_correct : forall word : N,
  clint_mtimecmp_hi_get word = declared_extract word clint_mtimecmp_hi_shift clint_mtimecmp_hi_width.
Proof. intro word; change (N.land (N.shiftr word 32) (N.ones 32)
  = declared_extract word 32 32); apply shift_mask_correct. Qed.

Definition clint_mtime_lo_shift : N := 0.
Definition clint_mtime_lo_width : N := 32.
Definition clint_mtime_lo_get (word : N) : N :=
  N.land (N.shiftr word 0) 4294967295.
Theorem clint_mtime_lo_correct : forall word : N,
  clint_mtime_lo_get word = declared_extract word clint_mtime_lo_shift clint_mtime_lo_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 32)
  = declared_extract word 0 32); apply shift_mask_correct. Qed.

Definition clint_mtime_hi_shift : N := 32.
Definition clint_mtime_hi_width : N := 32.
Definition clint_mtime_hi_get (word : N) : N :=
  N.land (N.shiftr word 32) 4294967295.
Theorem clint_mtime_hi_correct : forall word : N,
  clint_mtime_hi_get word = declared_extract word clint_mtime_hi_shift clint_mtime_hi_width.
Proof. intro word; change (N.land (N.shiftr word 32) (N.ones 32)
  = declared_extract word 32 32); apply shift_mask_correct. Qed.

Definition imsic_seteipnum_value_shift : N := 0.
Definition imsic_seteipnum_value_width : N := 64.
Definition imsic_seteipnum_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem imsic_seteipnum_value_correct : forall word : N,
  imsic_seteipnum_value_get word = declared_extract word imsic_seteipnum_value_shift imsic_seteipnum_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition imsic_seteipnum_identity_shift : N := 0.
Definition imsic_seteipnum_identity_width : N := 6.
Definition imsic_seteipnum_identity_get (word : N) : N :=
  N.land (N.shiftr word 0) 63.
Theorem imsic_seteipnum_identity_correct : forall word : N,
  imsic_seteipnum_identity_get word = declared_extract word imsic_seteipnum_identity_shift imsic_seteipnum_identity_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 6)
  = declared_extract word 0 6); apply shift_mask_correct. Qed.

Definition imsic_eip_value_shift : N := 0.
Definition imsic_eip_value_width : N := 64.
Definition imsic_eip_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem imsic_eip_value_correct : forall word : N,
  imsic_eip_value_get word = declared_extract word imsic_eip_value_shift imsic_eip_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition revocation_bitmap_word_value_shift : N := 0.
Definition revocation_bitmap_word_value_width : N := 64.
Definition revocation_bitmap_word_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem revocation_bitmap_word_value_correct : forall word : N,
  revocation_bitmap_word_value_get word = declared_extract word revocation_bitmap_word_value_shift revocation_bitmap_word_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition otp_state_value_shift : N := 0.
Definition otp_state_value_width : N := 64.
Definition otp_state_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem otp_state_value_correct : forall word : N,
  otp_state_value_get word = declared_extract word otp_state_value_shift otp_state_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition otp_burn_value_shift : N := 0.
Definition otp_burn_value_width : N := 64.
Definition otp_burn_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem otp_burn_value_correct : forall word : N,
  otp_burn_value_get word = declared_extract word otp_burn_value_shift otp_burn_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition otp_dm_gate_gated_shift : N := 0.
Definition otp_dm_gate_gated_width : N := 1.
Definition otp_dm_gate_gated_get (word : N) : N :=
  N.land (N.shiftr word 0) 1.
Theorem otp_dm_gate_gated_correct : forall word : N,
  otp_dm_gate_gated_get word = declared_extract word otp_dm_gate_gated_shift otp_dm_gate_gated_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 1)
  = declared_extract word 0 1); apply shift_mask_correct. Qed.

Definition otp_fuse_count_value_shift : N := 0.
Definition otp_fuse_count_value_width : N := 64.
Definition otp_fuse_count_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem otp_fuse_count_value_correct : forall word : N,
  otp_fuse_count_value_get word = declared_extract word otp_fuse_count_value_shift otp_fuse_count_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition otp_fuse_word_value_shift : N := 0.
Definition otp_fuse_word_value_width : N := 64.
Definition otp_fuse_word_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem otp_fuse_word_value_correct : forall word : N,
  otp_fuse_word_value_get word = declared_extract word otp_fuse_word_value_shift otp_fuse_word_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition trng_draw_value_shift : N := 0.
Definition trng_draw_value_width : N := 64.
Definition trng_draw_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem trng_draw_value_correct : forall word : N,
  trng_draw_value_get word = declared_extract word trng_draw_value_shift trng_draw_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition trng_health_started_shift : N := 0.
Definition trng_health_started_width : N := 4.
Definition trng_health_started_get (word : N) : N :=
  N.land (N.shiftr word 0) 15.
Theorem trng_health_started_correct : forall word : N,
  trng_health_started_get word = declared_extract word trng_health_started_shift trng_health_started_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 4)
  = declared_extract word 0 4); apply shift_mask_correct. Qed.

Definition trng_health_complete_shift : N := 32.
Definition trng_health_complete_width : N := 1.
Definition trng_health_complete_get (word : N) : N :=
  N.land (N.shiftr word 32) 1.
Theorem trng_health_complete_correct : forall word : N,
  trng_health_complete_get word = declared_extract word trng_health_complete_shift trng_health_complete_width.
Proof. intro word; change (N.land (N.shiftr word 32) (N.ones 1)
  = declared_extract word 32 1); apply shift_mask_correct. Qed.

Definition trng_health_stopped_shift : N := 33.
Definition trng_health_stopped_width : N := 1.
Definition trng_health_stopped_get (word : N) : N :=
  N.land (N.shiftr word 33) 1.
Theorem trng_health_stopped_correct : forall word : N,
  trng_health_stopped_get word = declared_extract word trng_health_stopped_shift trng_health_stopped_width.
Proof. intro word; change (N.land (N.shiftr word 33) (N.ones 1)
  = declared_extract word 33 1); apply shift_mask_correct. Qed.

Definition trng_sources_value_shift : N := 0.
Definition trng_sources_value_width : N := 64.
Definition trng_sources_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem trng_sources_value_correct : forall word : N,
  trng_sources_value_get word = declared_extract word trng_sources_value_shift trng_sources_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition trng_budget_value_shift : N := 0.
Definition trng_budget_value_width : N := 64.
Definition trng_budget_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem trng_budget_value_correct : forall word : N,
  trng_budget_value_get word = declared_extract word trng_budget_value_shift trng_budget_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition monotonic_counters_counter_value_shift : N := 0.
Definition monotonic_counters_counter_value_width : N := 64.
Definition monotonic_counters_counter_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem monotonic_counters_counter_value_correct : forall word : N,
  monotonic_counters_counter_value_get word = declared_extract word monotonic_counters_counter_value_shift monotonic_counters_counter_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition monotonic_counters_advance_value_shift : N := 0.
Definition monotonic_counters_advance_value_width : N := 64.
Definition monotonic_counters_advance_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem monotonic_counters_advance_value_correct : forall word : N,
  monotonic_counters_advance_value_get word = declared_extract word monotonic_counters_advance_value_shift monotonic_counters_advance_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition monotonic_counters_count_value_shift : N := 0.
Definition monotonic_counters_count_value_width : N := 64.
Definition monotonic_counters_count_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem monotonic_counters_count_value_correct : forall word : N,
  monotonic_counters_count_value_get word = declared_extract word monotonic_counters_count_value_shift monotonic_counters_count_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition watchdog_nonce_value_shift : N := 0.
Definition watchdog_nonce_value_width : N := 64.
Definition watchdog_nonce_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem watchdog_nonce_value_correct : forall word : N,
  watchdog_nonce_value_get word = declared_extract word watchdog_nonce_value_shift watchdog_nonce_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition watchdog_ticks_value_shift : N := 0.
Definition watchdog_ticks_value_width : N := 64.
Definition watchdog_ticks_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem watchdog_ticks_value_correct : forall word : N,
  watchdog_ticks_value_get word = declared_extract word watchdog_ticks_value_shift watchdog_ticks_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition watchdog_pet_value_shift : N := 0.
Definition watchdog_pet_value_width : N := 64.
Definition watchdog_pet_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem watchdog_pet_value_correct : forall word : N,
  watchdog_pet_value_get word = declared_extract word watchdog_pet_value_shift watchdog_pet_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition watchdog_bitten_latched_shift : N := 0.
Definition watchdog_bitten_latched_width : N := 1.
Definition watchdog_bitten_latched_get (word : N) : N :=
  N.land (N.shiftr word 0) 1.
Theorem watchdog_bitten_latched_correct : forall word : N,
  watchdog_bitten_latched_get word = declared_extract word watchdog_bitten_latched_shift watchdog_bitten_latched_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 1)
  = declared_extract word 0 1); apply shift_mask_correct. Qed.

Definition watchdog_early_value_shift : N := 0.
Definition watchdog_early_value_width : N := 64.
Definition watchdog_early_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem watchdog_early_value_correct : forall word : N,
  watchdog_early_value_get word = declared_extract word watchdog_early_value_shift watchdog_early_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition watchdog_late_value_shift : N := 0.
Definition watchdog_late_value_width : N := 64.
Definition watchdog_late_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem watchdog_late_value_correct : forall word : N,
  watchdog_late_value_get word = declared_extract word watchdog_late_value_shift watchdog_late_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_version_value_shift : N := 0.
Definition blkdev_version_value_width : N := 64.
Definition blkdev_version_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_version_value_correct : forall word : N,
  blkdev_version_value_get word = declared_extract word blkdev_version_value_shift blkdev_version_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_block_bytes_value_shift : N := 0.
Definition blkdev_block_bytes_value_width : N := 64.
Definition blkdev_block_bytes_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_block_bytes_value_correct : forall word : N,
  blkdev_block_bytes_value_get word = declared_extract word blkdev_block_bytes_value_shift blkdev_block_bytes_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_block_count_value_shift : N := 0.
Definition blkdev_block_count_value_width : N := 64.
Definition blkdev_block_count_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_block_count_value_correct : forall word : N,
  blkdev_block_count_value_get word = declared_extract word blkdev_block_count_value_shift blkdev_block_count_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_status_value_shift : N := 0.
Definition blkdev_status_value_width : N := 64.
Definition blkdev_status_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_status_value_correct : forall word : N,
  blkdev_status_value_get word = declared_extract word blkdev_status_value_shift blkdev_status_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_result_value_shift : N := 0.
Definition blkdev_result_value_width : N := 64.
Definition blkdev_result_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_result_value_correct : forall word : N,
  blkdev_result_value_get word = declared_extract word blkdev_result_value_shift blkdev_result_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_block_value_shift : N := 0.
Definition blkdev_block_value_width : N := 64.
Definition blkdev_block_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_block_value_correct : forall word : N,
  blkdev_block_value_get word = declared_extract word blkdev_block_value_shift blkdev_block_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_command_value_shift : N := 0.
Definition blkdev_command_value_width : N := 64.
Definition blkdev_command_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_command_value_correct : forall word : N,
  blkdev_command_value_get word = declared_extract word blkdev_command_value_shift blkdev_command_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_ack_value_shift : N := 0.
Definition blkdev_ack_value_width : N := 64.
Definition blkdev_ack_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_ack_value_correct : forall word : N,
  blkdev_ack_value_get word = declared_extract word blkdev_ack_value_shift blkdev_ack_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition blkdev_data_value_shift : N := 0.
Definition blkdev_data_value_width : N := 64.
Definition blkdev_data_value_get (word : N) : N :=
  N.land (N.shiftr word 0) 18446744073709551615.
Theorem blkdev_data_value_correct : forall word : N,
  blkdev_data_value_get word = declared_extract word blkdev_data_value_shift blkdev_data_value_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 64)
  = declared_extract word 0 64); apply shift_mask_correct. Qed.

Definition htif_tohost_payload_shift : N := 0.
Definition htif_tohost_payload_width : N := 48.
Definition htif_tohost_payload_get (word : N) : N :=
  N.land (N.shiftr word 0) 281474976710655.
Theorem htif_tohost_payload_correct : forall word : N,
  htif_tohost_payload_get word = declared_extract word htif_tohost_payload_shift htif_tohost_payload_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 48)
  = declared_extract word 0 48); apply shift_mask_correct. Qed.

Definition htif_tohost_cmd_shift : N := 48.
Definition htif_tohost_cmd_width : N := 8.
Definition htif_tohost_cmd_get (word : N) : N :=
  N.land (N.shiftr word 48) 255.
Theorem htif_tohost_cmd_correct : forall word : N,
  htif_tohost_cmd_get word = declared_extract word htif_tohost_cmd_shift htif_tohost_cmd_width.
Proof. intro word; change (N.land (N.shiftr word 48) (N.ones 8)
  = declared_extract word 48 8); apply shift_mask_correct. Qed.

Definition htif_tohost_device_shift : N := 56.
Definition htif_tohost_device_width : N := 8.
Definition htif_tohost_device_get (word : N) : N :=
  N.land (N.shiftr word 56) 255.
Theorem htif_tohost_device_correct : forall word : N,
  htif_tohost_device_get word = declared_extract word htif_tohost_device_shift htif_tohost_device_width.
Proof. intro word; change (N.land (N.shiftr word 56) (N.ones 8)
  = declared_extract word 56 8); apply shift_mask_correct. Qed.

Definition htif_tohost_lo_shift : N := 0.
Definition htif_tohost_lo_width : N := 32.
Definition htif_tohost_lo_get (word : N) : N :=
  N.land (N.shiftr word 0) 4294967295.
Theorem htif_tohost_lo_correct : forall word : N,
  htif_tohost_lo_get word = declared_extract word htif_tohost_lo_shift htif_tohost_lo_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 32)
  = declared_extract word 0 32); apply shift_mask_correct. Qed.

Definition htif_tohost_hi_shift : N := 32.
Definition htif_tohost_hi_width : N := 32.
Definition htif_tohost_hi_get (word : N) : N :=
  N.land (N.shiftr word 32) 4294967295.
Theorem htif_tohost_hi_correct : forall word : N,
  htif_tohost_hi_get word = declared_extract word htif_tohost_hi_shift htif_tohost_hi_width.
Proof. intro word; change (N.land (N.shiftr word 32) (N.ones 32)
  = declared_extract word 32 32); apply shift_mask_correct. Qed.

Definition htif_tohost_payload_hi_shift : N := 32.
Definition htif_tohost_payload_hi_width : N := 16.
Definition htif_tohost_payload_hi_get (word : N) : N :=
  N.land (N.shiftr word 32) 65535.
Theorem htif_tohost_payload_hi_correct : forall word : N,
  htif_tohost_payload_hi_get word = declared_extract word htif_tohost_payload_hi_shift htif_tohost_payload_hi_width.
Proof. intro word; change (N.land (N.shiftr word 32) (N.ones 16)
  = declared_extract word 32 16); apply shift_mask_correct. Qed.

Definition htif_tohost_terminal_byte_shift : N := 0.
Definition htif_tohost_terminal_byte_width : N := 8.
Definition htif_tohost_terminal_byte_get (word : N) : N :=
  N.land (N.shiftr word 0) 255.
Theorem htif_tohost_terminal_byte_correct : forall word : N,
  htif_tohost_terminal_byte_get word = declared_extract word htif_tohost_terminal_byte_shift htif_tohost_terminal_byte_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 8)
  = declared_extract word 0 8); apply shift_mask_correct. Qed.

Definition htif_tohost_exit_flag_shift : N := 0.
Definition htif_tohost_exit_flag_width : N := 1.
Definition htif_tohost_exit_flag_get (word : N) : N :=
  N.land (N.shiftr word 0) 1.
Theorem htif_tohost_exit_flag_correct : forall word : N,
  htif_tohost_exit_flag_get word = declared_extract word htif_tohost_exit_flag_shift htif_tohost_exit_flag_width.
Proof. intro word; change (N.land (N.shiftr word 0) (N.ones 1)
  = declared_extract word 0 1); apply shift_mask_correct. Qed.

Print Assumptions shift_mask_correct.
