(* SPDX-License-Identifier: Apache-2.0 *)
(* =========================================================================
   Generated by vos.elastic_pool_campaign.render. Do not edit.
   Finite allocator traces checked against the original pool contract.
   This is finite trace evidence, not the allocator refinement theorem.
   ========================================================================= *)
From Stdlib Require Import List.
Require Import CyclicExecutive MemoryPlan ElasticDomain ElasticPool.
Import ListNotations.

Definition pool_trace_0 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16)].
Example pool_trace_0_safe :
  PoolGuarantees pool_reference_arena pool_trace_0.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_1 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_1_safe :
  PoolGuarantees pool_reference_arena pool_trace_1.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_2 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Write 64 7; Release 64 0].
Example pool_trace_2_safe :
  PoolGuarantees pool_reference_arena pool_trace_2.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_3 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 64 7; Release 64 0].
Example pool_trace_3_safe :
  PoolGuarantees pool_reference_arena pool_trace_3.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_4 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Write 64 7; Release 64 0; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_4_safe :
  PoolGuarantees pool_reference_arena pool_trace_4.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_5 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Write 64 7; Release 64 0; Write 80 7; Release 80 0].
Example pool_trace_5_safe :
  PoolGuarantees pool_reference_arena pool_trace_5.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_6 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16)].
Example pool_trace_6_safe :
  PoolGuarantees pool_reference_arena pool_trace_6.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_7 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Write 64 7; Release 64 0].
Example pool_trace_7_safe :
  PoolGuarantees pool_reference_arena pool_trace_7.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_8 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_8_safe :
  PoolGuarantees pool_reference_arena pool_trace_8.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_9 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 64 7; Release 64 0].
Example pool_trace_9_safe :
  PoolGuarantees pool_reference_arena pool_trace_9.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_10 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 64 7; Release 64 0; Zero 80 16; Grant 1 0 80 (chunk_cap 80 16)].
Example pool_trace_10_safe :
  PoolGuarantees pool_reference_arena pool_trace_10.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_11 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 64 7; Release 64 0; Write 96 7; Release 96 1].
Example pool_trace_11_safe :
  PoolGuarantees pool_reference_arena pool_trace_11.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_12 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; Zero 80 16; Grant 1 0 80 (chunk_cap 80 16)].
Example pool_trace_12_safe :
  PoolGuarantees pool_reference_arena pool_trace_12.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_13 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_13_safe :
  PoolGuarantees pool_reference_arena pool_trace_13.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_14 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Write 80 7; Release 80 0].
Example pool_trace_14_safe :
  PoolGuarantees pool_reference_arena pool_trace_14.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_15 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16)].
Example pool_trace_15_safe :
  PoolGuarantees pool_reference_arena pool_trace_15.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_16 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_16_safe :
  PoolGuarantees pool_reference_arena pool_trace_16.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_17 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1].
Example pool_trace_17_safe :
  PoolGuarantees pool_reference_arena pool_trace_17.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_18 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0].
Example pool_trace_18_safe :
  PoolGuarantees pool_reference_arena pool_trace_18.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_19 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone].
Example pool_trace_19_safe :
  PoolGuarantees pool_reference_arena pool_trace_19.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_20 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16)].
Example pool_trace_20_safe :
  PoolGuarantees pool_reference_arena pool_trace_20.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_21 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16)].
Example pool_trace_21_safe :
  PoolGuarantees pool_reference_arena pool_trace_21.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_22 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16); Write 64 7; Release 64 0].
Example pool_trace_22_safe :
  PoolGuarantees pool_reference_arena pool_trace_22.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_23 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 64 16; Grant 1 0 64 (chunk_cap 64 16)].
Example pool_trace_23_safe :
  PoolGuarantees pool_reference_arena pool_trace_23.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_24 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0].
Example pool_trace_24_safe :
  PoolGuarantees pool_reference_arena pool_trace_24.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_25 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; Zero 80 16; Grant 1 0 80 (chunk_cap 80 16)].
Example pool_trace_25_safe :
  PoolGuarantees pool_reference_arena pool_trace_25.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_26 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; Write 96 7; Release 96 1].
Example pool_trace_26_safe :
  PoolGuarantees pool_reference_arena pool_trace_26.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_27 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_27_safe :
  PoolGuarantees pool_reference_arena pool_trace_27.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_28 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1].
Example pool_trace_28_safe :
  PoolGuarantees pool_reference_arena pool_trace_28.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_29 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; Zero 64 16; Grant 1 0 64 (chunk_cap 64 16)].
Example pool_trace_29_safe :
  PoolGuarantees pool_reference_arena pool_trace_29.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_30 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 1 0 80 (chunk_cap 80 16)].
Example pool_trace_30_safe :
  PoolGuarantees pool_reference_arena pool_trace_30.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_31 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0].
Example pool_trace_31_safe :
  PoolGuarantees pool_reference_arena pool_trace_31.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_32 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone].
Example pool_trace_32_safe :
  PoolGuarantees pool_reference_arena pool_trace_32.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_33 : list AllocEvent :=
  [].
Example pool_trace_33_safe :
  PoolGuarantees pool_reference_arena pool_trace_33.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_34 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 2 0 64 (chunk_cap 64 16)].
Example pool_trace_34_safe :
  PoolGuarantees pool_reference_arena pool_trace_34.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_35 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 2 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 2 0 64 (chunk_cap 64 16)].
Example pool_trace_35_safe :
  PoolGuarantees pool_reference_arena pool_trace_35.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_36 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 2 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 2 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 2 0 64 (chunk_cap 64 16)].
Example pool_trace_36_safe :
  PoolGuarantees pool_reference_arena pool_trace_36.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_37 : list AllocEvent :=
  [Zero 64 16; Grant 2 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 3 0 64 (chunk_cap 64 16)].
Example pool_trace_37_safe :
  PoolGuarantees pool_reference_arena pool_trace_37.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_38 : list AllocEvent :=
  [Zero 64 16; Grant 2 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 3 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 3 0 64 (chunk_cap 64 16)].
Example pool_trace_38_safe :
  PoolGuarantees pool_reference_arena pool_trace_38.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_39 : list AllocEvent :=
  [Zero 64 16; Grant 2 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 3 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 3 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 3 0 64 (chunk_cap 64 16)].
Example pool_trace_39_safe :
  PoolGuarantees pool_reference_arena pool_trace_39.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_40 : list AllocEvent :=
  [Zero 64 16; Grant 3 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 4 0 64 (chunk_cap 64 16)].
Example pool_trace_40_safe :
  PoolGuarantees pool_reference_arena pool_trace_40.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_41 : list AllocEvent :=
  [Zero 64 16; Grant 3 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 4 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 4 0 64 (chunk_cap 64 16)].
Example pool_trace_41_safe :
  PoolGuarantees pool_reference_arena pool_trace_41.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_42 : list AllocEvent :=
  [Zero 64 16; Grant 3 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 4 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 4 0 64 (chunk_cap 64 16); Write 64 7; Release 64 0; BarrierDone; SweepBegin; SweepEnd; Zero 64 16; Grant 4 0 64 (chunk_cap 64 16)].
Example pool_trace_42_safe :
  PoolGuarantees pool_reference_arena pool_trace_42.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_43 : list AllocEvent :=
  [Zero 96 32; Grant 1 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_43_safe :
  PoolGuarantees pool_reference_arena pool_trace_43.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_44 : list AllocEvent :=
  [Zero 96 32; Grant 1 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_44_safe :
  PoolGuarantees pool_reference_arena pool_trace_44.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_45 : list AllocEvent :=
  [Zero 96 32; Grant 1 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 2 1 96 (chunk_cap 96 32)].
Example pool_trace_45_safe :
  PoolGuarantees pool_reference_arena pool_trace_45.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_46 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 3 1 96 (chunk_cap 96 32)].
Example pool_trace_46_safe :
  PoolGuarantees pool_reference_arena pool_trace_46.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_47 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 3 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 3 1 96 (chunk_cap 96 32)].
Example pool_trace_47_safe :
  PoolGuarantees pool_reference_arena pool_trace_47.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_48 : list AllocEvent :=
  [Zero 96 32; Grant 2 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 3 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 3 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 3 1 96 (chunk_cap 96 32)].
Example pool_trace_48_safe :
  PoolGuarantees pool_reference_arena pool_trace_48.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_49 : list AllocEvent :=
  [Zero 96 32; Grant 3 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 4 1 96 (chunk_cap 96 32)].
Example pool_trace_49_safe :
  PoolGuarantees pool_reference_arena pool_trace_49.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_50 : list AllocEvent :=
  [Zero 96 32; Grant 3 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 4 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 4 1 96 (chunk_cap 96 32)].
Example pool_trace_50_safe :
  PoolGuarantees pool_reference_arena pool_trace_50.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_51 : list AllocEvent :=
  [Zero 96 32; Grant 3 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 4 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 4 1 96 (chunk_cap 96 32); Write 96 7; Release 96 1; BarrierDone; SweepBegin; SweepEnd; Zero 96 32; Grant 4 1 96 (chunk_cap 96 32)].
Example pool_trace_51_safe :
  PoolGuarantees pool_reference_arena pool_trace_51.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_52 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 2 0 80 (chunk_cap 80 16); Release 64 0; BarrierDone; SweepBegin; Release 80 0; SweepEnd; Zero 64 16; Grant 3 0 64 (chunk_cap 64 16); BarrierDone; SweepBegin; SweepEnd; Zero 80 16; Grant 4 0 80 (chunk_cap 80 16)].
Example pool_trace_52_safe :
  PoolGuarantees pool_reference_arena pool_trace_52.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.

Definition pool_trace_53 : list AllocEvent :=
  [Zero 64 16; Grant 1 0 64 (chunk_cap 64 16); Zero 80 16; Grant 2 0 80 (chunk_cap 80 16); Release 64 0; BarrierDone; SweepBegin; Release 80 0; BarrierDone; SweepEnd; Zero 64 16; Grant 3 0 64 (chunk_cap 64 16); SweepBegin; SweepEnd; Zero 80 16; Grant 4 0 80 (chunk_cap 80 16)].
Example pool_trace_53_safe :
  PoolGuarantees pool_reference_arena pool_trace_53.
Proof. apply pool_checked_history. vm_compute. reflexivity. Qed.
