#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Emit one self-contained C translation unit of a stated size, deterministically.

Usage: gen.py <functions> [--body <statements>]

The unit includes no header, so its preprocessed form is its own bytes and the
compiler under measurement is handed exactly what this file emits. Every function
has the same shape and the same statement count, differing only in the constants
its name derives, so the ladder's only free variable is the number of functions:
a peak that grows across the ladder grows with the size of the unit and not with
some other property of the text. One function calls the one before it, so the
call graph is a chain rather than a set of leaves and an inliner has somewhere to
work; the chain is bounded by `--body`, which fixes the statements per function.

This is a size ladder and not a workload. It carries no roster and stands in for
none: what it decides is whether the compiler's peak resident set is a function of
the unit's size, which is the question a declared pool has to be sized against and
which no fixed corpus file answers on its own.
"""
import sys


def unit(functions: int, body: int) -> str:
    out = ["/* generated by gen.py; do not edit */", "", "int f0(int x) { return x + 1; }", ""]
    for i in range(1, functions):
        lines = [f"int f{i}(int x) {{", f"  int a = f{i - 1}(x);"]
        for j in range(body):
            lines.append(f"  a = a * {2 * j + 3} + {i % 97} - (a >> {j % 13 + 1});")
        lines.append("  return a;")
        lines.append("}")
        out.append("\n".join(lines))
        out.append("")
    out.append(f"int top(int x) {{ return f{max(functions - 1, 0)}(x); }}")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__, file=sys.stderr)
        return 2
    functions = int(argv[0])
    body = 8
    if len(argv) >= 3 and argv[1] == "--body":
        body = int(argv[2])
    sys.stdout.write(unit(functions, body))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
