// SPDX-License-Identifier: Apache-2.0
#ifndef VOS_LIFECYCLE_H
#define VOS_LIFECYCLE_H

#include "vos_effects.h"
#include "vos_context_layout.h"

#define VOS_LIFECYCLE_NONE 0U
#define VOS_LIFECYCLE_ACK 1U
#define VOS_LIFECYCLE_RETIRE 2U
#define VOS_LIFECYCLE_START 3U
#define VOS_LIFECYCLE_PUBLISH 4U

/* Kernel-private state. One prepare/finish/acknowledge/published chain runs
 * entirely in the current boundary handler, with the supervisor stopped.
 * It must never return to dispatch with a pending action or held exclusion. */
struct vos_kernel_lifecycle {
    uint64_t last_sequence, pending_sequence, request_epoch, mask;
    uint64_t now, deadline, completion_epoch;
    uint32_t initialized, action, held, initial_consumed;
    uint32_t operation, status, phase, members, count, prefix, refused, attempts;
    struct vos_supervisor_start starts[VOS_CTX_UNITS];
};

/* Init requires the bound effect state before any unit has been started.
 * It writes acknowledgment fields except sequence; composition publishes 0. */
int vos_kernel_lifecycle_init(struct vos_kernel_lifecycle *context,
                              struct vos_kernel_effect_state *effects,
                              uint8_t *acknowledgment);
/* Request/acknowledgment are exact generated byte regions. Scalar fields are
 * decoded little endian, without struct overlays or alignment assumptions.
 * now comes from the admitted clock. A fresh malformed request returns ACK;
 * zero/replay/gap/exhausted publication returns NONE without changing its
 * recorded effect result. All start entries are checked before START. */
uint32_t vos_kernel_lifecycle_prepare(struct vos_kernel_lifecycle *context,
                                      struct vos_kernel_effect_state *effects,
                                      const uint8_t *request, uint64_t now);
uint64_t vos_kernel_lifecycle_mask(const struct vos_kernel_lifecycle *context);
/* Root assembly publishes the returned mask to the actual bitmap, reads it
 * back, and establishes resident_clean from architectural teardown. It also
 * validates authentic fresh roots, bounds and masks before this pure call.
 * This call checks the one-use publication, semantic teardown and epoch before
 * replenishment. Its clock sample is a lower bound; acknowledge takes another
 * actual sample after clearing and replenishment to anchor the deadline. */
int vos_kernel_lifecycle_retire_finish(struct vos_kernel_lifecycle *context,
                                       struct vos_kernel_effect_state *effects,
                                       uint64_t observed,
                                       const vos_cap_t *fresh_roots,
                                       const uint64_t *fresh_masks,
                                       uint64_t completion_now);
int vos_kernel_lifecycle_start_finish(struct vos_kernel_lifecycle *context,
                                      struct vos_kernel_effect_state *effects);
/* Assembly clears the acknowledgment publication, calls acknowledge, orders
 * the fields, then stores the returned 64-bit sequence last. It calls published
 * immediately afterward, before dispatch, to release any start exclusion.
 * NONE refreshes only NOW and current snapshot/epoch, retaining the previous
 * result and watermark. For successful retirement, now is sampled after finish
 * and defines acknowledged completion time and the backoff deadline. All paths
 * are bounded and never wait for a deadline. */
uint64_t vos_kernel_lifecycle_acknowledge(struct vos_kernel_lifecycle *context,
                                         struct vos_kernel_effect_state *effects,
                                         uint8_t *acknowledgment, uint64_t now);
int vos_kernel_lifecycle_published(struct vos_kernel_lifecycle *context,
                                   struct vos_kernel_effect_state *effects,
                                   uint64_t sequence);
/* The fault boundary invalidates publication before prepare. No partial
 * supervisor reaction is resumed. Assembly may use an aligned zero store. */
void vos_kernel_lifecycle_fault(uint8_t *request);

#endif
