# SPDX-License-Identifier: Apache-2.0
# Opt-in CMake overlay. The curated model and ordinary build recipes stay intact.
function(vos_modular_overlay)
  if(NOT TARGET riscv_model OR NOT VOS_MODULAR_COUNT MATCHES "^[0-9]+$")
    message(FATAL_ERROR "sail-modular requires the supported riscv_model target")
  endif()
  get_target_property(original_sources riscv_model SOURCES)
  set(original_model "${CMAKE_BINARY_DIR}/sail_riscv_model.cpp")
  list(FIND original_sources "${original_model}" model_index)
  if(model_index LESS 0)
    message(FATAL_ERROR "sail-modular did not find the generated model translation unit")
  endif()
  list(REMOVE_ITEM original_sources "${original_model}")
  get_target_property(model_source_dir riscv_model SOURCE_DIR)
  set(support_sources)
  foreach(source IN LISTS original_sources)
    if(IS_ABSOLUTE "${source}")
      list(APPEND support_sources "${source}")
    elseif(source MATCHES "^\\$<")
      message(FATAL_ERROR "sail-modular does not accept unevaluated source expressions")
    else()
      list(APPEND support_sources "${model_source_dir}/${source}")
    endif()
  endforeach()
  # The support wrappers call methods and the methods call wrappers (SoftFloat
  # is one example), so support and generated archives share one rescan group.
  file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/sail_modular_anchor.cpp"
       CONTENT "// Empty facade preserves the upstream riscv_model target.\n")
  set_property(TARGET riscv_model PROPERTY SOURCES "${CMAKE_BINARY_DIR}/sail_modular_anchor.cpp")
  get_target_property(model_includes riscv_model INCLUDE_DIRECTORIES)
  add_library(sail_modular_support STATIC ${support_sources})
  add_library(sail_modular_owner STATIC "${VOS_MODULAR_DIR}/owner.cpp")
  set(modular_targets sail_modular_support sail_modular_owner)
  math(EXPR last_part "${VOS_MODULAR_COUNT} - 1")
  foreach(part RANGE 0 ${last_part})
    add_library(sail_modular_part${part} STATIC "${VOS_MODULAR_DIR}/part${part}.cpp")
    list(APPEND modular_targets sail_modular_part${part})
  endforeach()
  foreach(target IN LISTS modular_targets)
    target_include_directories(${target} PRIVATE ${model_includes} "${VOS_MODULAR_DIR}")
    target_link_libraries(${target} PRIVATE elfio softfloat sail_runtime jsoncons default_config)
    target_compile_options(${target} PRIVATE -Wno-extra -Wno-unused -Wno-uninitialized)
    add_dependencies(${target} generated_sail_riscv_model generated_config_schema)
  endforeach()
  list(JOIN modular_targets "," link_group)
  target_link_libraries(riscv_model PUBLIC "$<LINK_GROUP:RESCAN,${link_group}>")
endfunction()

# CMAKE_PROJECT_INCLUDE runs before targets exist; defer to this project's end.
if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
  cmake_language(DEFER CALL vos_modular_overlay)
endif()
